### ISSUE TITLE
No "password reset" email

### ISSUE THREAD

**Issue by andreicek** [keybase/keybase-issues#1171]
I just got my invitation, registred with my email and my username; and I promptly forgot to write down the password I set.

But, asking for the reset email with my address will output that the email dosen't exist, but with my username I never get a email.

Help and thank you

**Comment by andreicek** [comment]
Anyone here?

**Comment by zQueal** [comment]
Interesting scenario. I just tested this and it seems to be working fine. Did you sign up with a separate email from that which you're using now?

**Comment by andreicek** [comment]
No, I don't think so! I tried every email I have and no dice. When I enter my username - andreicek it says that it send it. The email I remember using is crnkovic.a.z(a)gmail.com.

I could have made a typo? Is there any other way to regain my username and invitation?

Thank you for your help.

**Comment by zQueal** [comment]
Well, it may or may not be possible for a developer to manually change the database in which usernames and passwords are stored in, but don't quote me on that because I highly doubt they'd be willing to do that anyways.

Other than that, I'd just ensure that you check the email that you used to sign up with. It's always a possibility that something went wrong with changing it?

**Comment by oconnor663** [comment]
@andreicek I see what happened. I'll email you.
