### ISSUE TITLE
CSRF Token Response Inconsistencies

### ISSUE THREAD

**Issue by CodingAnarchy** [keybase/keybase-issues#1347]
My attempts to kill the sessions open for a user with the `https://keybase.io/_/api/1.0/session/killall.json` URL are all being stymied by a claim that the "CSRF-token verification failed for post".

On the other hand, the other POST API call I have set up so far (login) doesn't seem to care about the CSRF token at all (it works either with or without it).

Seems like something is going wrong, although I'm not sure what.

**Comment by malgorithms** [comment]
login is special in that the CSRF token is not required. So I don't think that should be related.

this is the first instance I've heard of a legit CSRF being rejected anywhere. can you walk us through the process of getting the token and then using it? I will try to reproduce it.

**Comment by CodingAnarchy** [comment]
I obtained the CSRF token from the previous call. Usually the login, but I also threw in a user lookup call in between to see if there was a special case with the login.

Basic step through was to get salt, login, then try to kill the session. Tried both the CSRF tokens obtained at that point. Always returned a CSRF token error. If needed, I can provide the actual code snippets involved when I get home from work (on lunch break now).

**Comment by malgorithms** [comment]
so unusual. some thoughts...  looking up a user is a GET that doesn't require a CSRF token, so it seems the only request tried that's failing so far is specifically this killall request. I wonder if other POSTS that require csrf's would also fail for you.

A simple one to try would be editing your profile. It's not in the docs yet, but it's a good test since it doesn't require any crypto or anything.

You'll post to `https://keybase.io/_/api/1.0/profile-edit.json`

And pass some subset of these params:

- `bio`
- `location`
- `full_name`

Either way, your code would be cool to see.

**Comment by CodingAnarchy** [comment]
Well, that worked quite nicely.  And then looking at my code and the differences between the two, I can see the error, which was on my end.  (Don't I feel the fool now.)

I had:

```python
def kill_sessions(session, csrf):
    ks_url = kb_url + 'session/killall.json'
    # print csrf
    r = requests.post(ks_url, params={'session': session, 'csrf_token': csrf})
    data = json.loads(r.text)
    if data['status']['code'] != 0:
       raise Exception("Attempt to kill user login sessions error: " + str(data["status"]["name"]) +
                       '\nDescription: ' + str(data["status"]["desc"]))
    return
```
This should have been:

```python
r = requests.post(ks_url, data={'session': session, 'csrf_token': csrf})
```

Sorry about that.  Guess it only arose because that was the only POST where I had made that mistake.  I'll go ahead and close this one so it's not cluttering up things any longer.
