### ISSUE TITLE
Website search - can't go to user quickly

### ISSUE THREAD

**Issue by joozek78** [keybase/keybase-issues#1354]
1. I know my friend's keybase login (chris) and want to go directly to his profile
1. I enter 'chris' in search box and press enter
1. Before I even finish typing 'chris' autocomplete kicks in and presents me results for 'ch'. When I press enter I land on ch's profile (instead of chris'es)

**Comment by malgorithms** [comment]
This should be fixed. Pressing enter only submits+jumps if the results have come back since you changed the form. That is, if you've typed "ch" and are looking at the result for that, and you quickly type "ris<enter>" and the enter is submitted before the results come back for the "ris" addition, it just won't do anything. (Since this is clearly an ambiguous case.)

Your friend,
chris
