### ISSUE TITLE
Verifying base64 encoded hashes

### ISSUE THREAD

**Issue by nilbus** [keybase/keybase-issues#1388]
With Twitter and web verifications, a base64 encoded SHA-256(binary(statement_contents)) is calculated. I haven't been able to reproduce this same hash, so I'm probably mangling the input somehow. I find it interesting that you add that _binary()_ function—I don't know its purpose.

I tried this, but it produced a different hash:

    cat statement_contents | shasum -a 256 | base64

Could you either explain that or point to where in the code the twitter hash is verified?

**Comment by timbray** [comment]
Here's some sample Java code that does it: https://github.com/timbray/KeybaseLib/blob/master/Lib/src/main/java/com/textuality/keybase/lib/prover/Prover.java#L124

**Comment by dtiersch** [comment]
since you're working with bash (or similar) I found you a one liner by @maxtaco from [here](https://github.com/keybase/keybase-issues/issues/174#issuecomment-40470030) which should calculate that hash:
```
pbpaste | openssl base64 -d | openssl dgst -sha256 | awk '{ print $2 } ' | xxd -r -p | openssl base64 -e
```
This relevant difference is converting the hash into a binary form before applying base64.

The purpose is that in binary you can stuff a lot more information into one byte (~256 possible characters) compared to hex (16 characters. Converting to base64 reduces this to 64 characters but this still needs a lot less room than with hex.

**Comment by nilbus** [comment]
Thank you! That's exactly what I was hoping to be able to do. I should have searched here before posting. Tested, and it works. :-D

**Comment by nilbus** [comment]
Sorry, I take that back. On OSX, the command I got to work was this:

    pbpaste | openssl base64 -d | openssl dgst -sha256 | xxd -r -p | openssl base64 -e

or alternatively

    pbpaste | base64 -D | shasum -a 256 | awk '{print $1}' | xxd -r -p | base64

`openssl dgst -sha256` only returned the hash, so I had to get rid of the awk pipe.
