### ISSUE TITLE
Two factor authentication?

### ISSUE THREAD

**Issue by jlb1234** [keybase/keybase-issues#1402]
Is there a chance of getting two-factor auth for site login & even the keybase cli?

**Comment by malgorithms** [comment]
yes, this'll happen. It's discussed elsewhere in these issues. it will happen sometime after we make our switch to the new clients.

**Comment by jlb1234** [comment]
Good to hear. This is the go client?

**Comment by malgorithms** [comment]
yeah, well, it'll be for the go client and the website (and hopefully not too far off, mobile clients). We're making a bunch of changes to how keys work -- for example, in addition to your PGP key, you'll have device-specific key for each device you use for keybase. How 2-factor fits into this is important, since the ultimate goal of 2FA with keybase won't be to protect sessions but to protect (1) your public signature chain, and (2) your key, if you store it encrypted/serverside.

**Comment by jlb1234** [comment]
That sounds great. I think it might be a good idea if you guys had a blog or something where this kind of information - new updates, plans, etc. - was made more transparent.

**Comment by malgorithms** [comment]
eventually....I have draft blog posts describing (1) our Go client, (2) a filesystem, (3) device specific keys, and (4) orgs. All of it will come in time, but writing the posts is a lot of work too. Bear with us!
