### ISSUE TITLE
Basic usage example

### ISSUE THREAD

**Issue by ianopolous** [keybase/keybase-issues#1415]
Hi guys, Love the work you've done. I'm trying to get a basic usage example working with kbpgp: 
http://jsfiddle.net/nuxffL6x/

The decryption fails because it thinks the buffer returned from the encrypt isn't a buffer. 
Also the commented lines exporting the keys fail with a null argument somewhere deep in kbpgp. Any help would be greatly appreciated. This is with version 1.0.0.

**Comment by malgorithms** [comment]
It's a bug, and @maxtaco is working on a fix! Expect an update here shortly. (I am but a messenger.)

It's nice to see someone else using kbpgp. Doing anything interesting? Is it your peergos project?

**Comment by ianopolous** [comment]
Fantastic! Did you guys already know about this? Indeed, we are hoping to use it for the client side crypto in Peergos (served from localhost, or from a machine the user trusts over https). Keybase has been a breath of fresh air in my search for a comprehensive, fast, Javascript crypto library that uses buffers under the hood, and it has a nice API to boot!

**Comment by malgorithms** [comment]
No, we didn't know about it. We'd only been using it with armored input, but as you can tell, it was supposed to work with buffers too. (It looks like Max just got his fix pushed.)

Anyway, that's great! I should warn you there's no streaming interface to kbpgp box/unbox, as we haven't needed it. So you've gotta fit everything in those buffers. If you're going to encrypt a 5GB file, kbpgp in its current state won't get that for you, because everything will have to fit in memory. You'll have to either (1) break a file up into pieces (maybe this is part of your protocol anyway), or (2) implement kbpgp's streaming interface for us :-) .

**Comment by ianopolous** [comment]
Yep, just trying it out now. :-) No streaming is fine, Peergos splits everything into 5 MiB chunks to encrypt anyway. Thanks again!

**Comment by maxtaco** [comment]
BTW, not live yet, give me a few more...

**Comment by ianopolous** [comment]
No worries.

**Comment by maxtaco** [comment]
Ok, I believe I just got your fiddle to work.  Give it a try now?

It turns out we didn't use the `raw` parameter much, but it's fixed now (and there's a regtest in place too).

BTW, I recommend changing `generate_rsa` to `generate_ecc` at least for testing, since it's much faster to generate ECC keys as compared to RSA keys.

Thanks!

**Comment by malgorithms** [comment]
oh excellent. Btw, you might consider switching to Keybase's ECC keys instead of RSA, if you're not making something that needs to be backwards compatible with old PGP clients. Then you don't have to wait for the big prime hunt; keygen is instantaneous.

**Comment by ianopolous** [comment]
Thanks guys! I definitely want to switch to ECC, especially once curve 25519 is implemented. 

The latest seems to work fine with generate_ecc, but for RSA the decryption throws:
Error: We don't have a key for the requested PGP ops
The export of the keys seems to return undefined for both ecc and rsa.

**Comment by maxtaco** [comment]
Ah, I see.  I think you need to call `keys.sign({}, function(err) { .... })` first. Otherwise, your subkeys won't appear "registered" as far as the software is concerned.

**Comment by maxtaco** [comment]
(this process signs the subkeys with the primary key)

**Comment by ianopolous** [comment]
Yep, that does the trick. All is working perfectly now. Many thanks, Max and Chris!
