### ISSUE TITLE
Update command fails when installed via homebrew

### ISSUE THREAD

**Issue by ahaarnos** [keybase/keybase-issues#1477]
I installed keybase via homebrew a couple months ago, but I had forgotten I'd done it that way, since the keybase docs don't seem to mention homebrew (at least not on the initial installation page).

When I tried to run `keybase update`, I saw the following error:
```bash
$ keybase update
info: Computed npm install prefix: /usr/local
error: Can't find `keybase-installer` in your path: spawn keybase-installer ENOENT
```

It's obvious to me now that I need to update it via the standard `brew update && brew upgrade keybase` way, but I think the failure message keybase yields when trying to perform its own update in this situation is lacking.

If `keybase-installer` isn't present, this most likely indicates it was installed via a package manager, no?

**Comment by dtiersch** [comment]
Won't happen. The Homebrew package is not by the keybase team and therefore neither official nor in the documentations. (see #934)
My first intention would have been to ask @xu-cheng to modify the brew package to intercept the update call, but when I looked into the [formula](https://github.com/Homebrew/homebrew/blob/3e35f1880b29cdd93129b94ed634b72d0e68945d/Library/Formula/keybase.rb) itself, I saw it is only checking out the copy directly from github without a way to modify it first.

**Comment by ahaarnos** [comment]
I can definitely see where you don't specifically want to support homebrew, but is a hard-failure the correct behavior when `keybase update` can't find `keybase-installer`?

Is update even a sensible command for keybase itself to have, if it can't perform the update without a dependency that isn't present when all other commands are used (and which isn't declared as an actual dependency in [package.json](https://github.com/keybase/node-client/blob/master/package.json))?

**Comment by dtiersch** [comment]
I think you're right. I proposed a PR to include `keybase-installer` as a dependency: https://github.com/keybase/node-client/pull/189

**Comment by maxtaco** [comment]
Merged, great suggestion. Thanks!

**Comment by dtiersch** [comment]
@ahaarnos: you need to update the next keybase release again with `brew upgrade`, but afterwards you should be set to use `keybase update` as well.

**Comment by ahaarnos** [comment]
Thanks, I think we can go ahead and close this issue now.

**Comment by maxtaco** [comment]
I hoped to look into some of the GPG 2.1 problems before cutting the next release, so it might be a little bit before 0.7.8 is ready.

**Comment by xu-cheng** [comment]
Sorry about the delay in reply. 

> therefore neither official nor in the documentations.

I deeply believe `brew` should be the official installation method unless for OS X(it works with Linuxbrew as well). Homebrew can handle node and gpg dependency automatically. @maxtaco What's the keybase team's thought about it. 

> without a way to modify it first.

That's incorrect. Formula is very flexible. I can modify it on the brew side. The simplest solution is to remove the `keybase update` command.  

> but afterwards you should be set to use keybase update as well.

This won't work well for brew installation. Since homebrew installs package in the sandbox with version control, we don't like it can be updated self. 

Feel free to ask me anything related to Homebrew. :wink:

**Comment by malgorithms** [comment]
I personally know very little about brew, but let me offer a quick summary of where we are:

1. we're switching the "official" Keybase client to Go, and it'll be on feature parity with the Node client soon.
2. the Mac release will come with 2 new things:
   - a GUI
   - a service, `keybased`, which handles crypto operations. For example, identity lookups, things like that.  There are a number of performance and convenience reasons this can/should exist as a service, even though the CLI will be able to bypass it

I bring up this summary because I don't know how it affects brew. For example, is it possible to install via Brew a GUI app that shows up in the Applications folder, that starts up automatically with a menubar item?  

Our non-developer installation expectation is that Keybase no longer requires any prerequisites, and it's a simple dmg install. Still, we do want devs to get Keybase as easily as possible, and while I don't know anything about managing brew packages, I do love its convenience.

**Comment by xu-cheng** [comment]
@malgorithms Thanks for the summary.

1. About the switching, keybase need to decide which version is the primary one(that is what will user expect when running `brew install keybase`). If you choose make go version as the official client, Homebrew has no problem to make such transition. As long as the first go client has the larger version number than node client, users won't notice anything when they run `brew upgrade keybase`. We have the same experience on [hub](https://github.com/Homebrew/homebrew/commit/69096c85c710679a83fbc32d9950d42668707aec) when it switched from ruby to go. After that, we can store node client somewhere else. Maybe a `keybase/homebrew-keybase` tap.

2. <blockquote> is it possible to install via Brew a GUI app that shows up in the Applications folder that starts up automatically with a menubar item?</blockquote>
The answer is yes. Homebrew will create a symlink in the Applications folder. As for the auto start-up, Homebrew allows to create a plist file then let user decide whether they want it auto start up.

3. <blockquote>Our non-developer installation expectation is that Keybase no longer requires any prerequisites, and it's a simple dmg install.</blockquote>
In such case, we can offer the installation thought [brew-cask](https://github.com/caskroom/homebrew-cask).
