### ISSUE TITLE
Want more information about what Keybase is going to do with my public key

### ISSUE THREAD

**Issue by spwhitton** [keybase/keybase-issues#1478]
Just signed up with an invitation.  Keybase seems like a really great idea.  I'd like to be involved in testing it.

However, almost immediately I was asked to sign my public key myself in order to prove something to Keybase, and I wasn't given enough information about what I was doing to be comfortable enough to proceed.  My public key is of course already signed by my private key, so it wasn't clear why I was doing this: am I just signing a message saying something like "my keybase ID is spwhitton"?  If so, the website should make that clear.

I really want to avoid extra signatures on my keys relating to keybase that might end up on the unscrubbable public key server network.

Thanks!

**Comment by malgorithms** [comment]
Hi, sorry this is unclear, and we'll try to make it clearer in the future.

In that step, you're not actually putting a new signature into your public key, you're signing a new statement, claiming your Keybase username, which in turn goes into your signature chain on the site. 

On Keybase, public announcements are designed to be orderable, and they are chained together (each one references the last) so that the server can't leave some signed statement out, to lie by omission, without leaving out the rest of a chain.

Hope that helps. Here's some more info:

https://keybase.io/docs/server_security
