### ISSUE TITLE
Feature request: An HTML page proof for web identity entries

### ISSUE THREAD

**Issue by noelmarkham** [keybase/keybase-issues#1485]
It would be nice to be able to have a nicely formatted HTML page for the proof on a website, rather than just a txt file. You could still match for a regex signature, much like you do for tweets.

**Comment by zQueal** [comment]
I'm all for ubiquity, but I really think this would be unnecessary. Or at least I can't think of any situations where you would gain any real benefits from using HTML over TXT. Anything HTML does, a simple text file can also do--aside from formatting--which is totally unnecessary. Especially when you have a web crawler that can just load the text file instead of having to truncate HTML and then process plain text.

I'm not trying to shit on your idea--just trying to play devils advocate.

**Comment by noelmarkham** [comment]
Hey, no worries, don't see it as shitting on my idea :)

My thought process behind it is that it could be included in a home page, for example something like this - https://firstlook.org/theintercept/staff/glenn-greenwald/ - I suppose it gives the site owner a little more "editorial freedom" as to how that file is hosted on their site.

I'd definitely incorporate it in an "about me" page on my own site if I could.

**Comment by zQueal** [comment]
> I suppose it gives the site owner a little more "editorial freedom" as to how that file is hosted on their site.

Now that, I can get behind.

**Comment by noelmarkham** [comment]
cleaning up my Github issues
