### ISSUE TITLE
Private Twitter Accounts?

### ISSUE THREAD

**Issue by metaclassing** [keybase/keybase-issues#1524]
Is there any way to know where the verification bot checks from? Does the account NEED to be public? Or can we recip follow the verification bot providing it access?

Thanks!

**Comment by zQueal** [comment]
As of now the account does __need_ to be public. It defeats the purpose of keybase which is _publicly_ auditable proofs. If I wanted to make sure, independent of both you and keybase, that you actually own your twitter account I can by simply viewing your public twitter feed (in relation to your actual keybase verification post). With a closed or private twitter account, I can't do this.

This is by design and it has already been said that it will not change.

**Comment by malgorithms** [comment]
yes, as @zQueal said, it's because anyone, anywhere, has to be able to run a Keybase client and verify the check. The premise is that no one trusts the Keybase server. 

(Sorry!)

If you tweet privately, you can still just tweet your keybase username and key fingerprint to your private followers. It isn't exactly the same, but it does get them your key.
