### ISSUE TITLE
Twitter validation fails if Tweet Privacy is enabled

### ISSUE THREAD

**Issue by editedbaseline** [keybase/keybase-issues#1536]
To allow Twitter validation I had to disable Tweet Privacy in Twitter (Settings > Security and privacy - see attachment). Turning this back on subsequently fails the regular validation checks as presumably as the account being used to check isn't following me. 

Suggest some type of mechanism where I can follow an account (i.e. @keybaseValidation) which automatically follows me back (if there is a function in the Twitter API to allow auto follow back, otherwise this could turn into an administrative nightmare!) and this account would be used to conduction the regular validation checks. 

Just a thought....!

![2015-04-17 19_53_30-twitter _ settings](https://cloud.githubusercontent.com/assets/11998657/7208951/1dea1224-e53c-11e4-8231-d788227a5ec9.png)

**Comment by zQueal** [comment]
This has been discussed probably more than any other issue we have. This is by design and not a lacking feature. The idea of keybase is __public__ly auditable proofs. If your tweets are private I need to trust you (a person I've never met) and Keybase (essentially a machine controlled by people) that you're all doing your due diligence to ensure my safety. In the end that's too much of you to ask of other people.

It has been stated by the developers that there are no plans for this to change.

**Comment by jcolebrand** [comment]
Actually it doesn't require you to trust me to ask me to give you access to my tweets. It would ask me to trust you. 

The assumption of trust is mis-bestowed above.

I personally think that it's fine to accept that you have to let people follow you for them to verify your data. Some data should be private on the internet. Them's the breaks.
