### ISSUE TITLE
Can't receive an invitation as my email is already on Keybase's DDBB

### ISSUE THREAD

**Issue by msx** [keybase/keybase-issues#1540]
Hi,
Doing some 'testing' I closed my account and now I'm unable to receive any more invitations from friends to my actual email address - no matter my account is gone.

How should I proceed to be able to receive invitations again?

Thanks.

**Comment by zQueal** [comment]
This is by design. A quick way around this, if you have gmail is by using a gmail postfix. For example, if your gmail address is `msx@gmail.com` then you can use `msx+keybase@gmail.com` and the mail will still be routed to your original gmail address.

Without gmail it becomes more difficult, however, the gist is the same. Simply send the invite to another email address, sign up, and then change it once you have.

**Comment by msx** [comment]
Thank you for the clear explanation :)

**Comment by dtiersch** [comment]
Also: the invitation code is not bound to the email address. You can send the invitation to another address but use the sent code with your original address.
