### ISSUE TITLE
Starting to track a user in multiple tabs may fail

### ISSUE THREAD

**Issue by jrecursive** [keybase/keybase-issues#1561]
I was on one user's page and opened several tabs, one for each user I wanted to track.  I switched to the first tab, started the tracking request, and proceeded to the next tab and started that one before the first one had finished (and/or was halted by the javascript engine when I changed tabs, or... :) ).  I was using Safari 8.0 (10600.1.25).  When I subsequently retried each one, waiting for them to individually finish, it functioned as expected.  

I haven't dug into cookies, shady js engine stuff, etc. to diagnose, but I thought the least I could do was report what I've got.  If I had to guess, the hash it "got" (that it was not expecting) was the hash from the last successfully computed tracking request (which was tab 4, somewhat curiously, out of my 5 tabs, though that could make sense given the right conditions) and the hash it "wanted" is probably correct insofar as it relates to the user I wished to track.

The first two tabs (though there were five in total, I only screencap'd the first two), in the order they were started:

1st

![screen shot 2015-04-29 at 5 42 56 pm](https://cloud.githubusercontent.com/assets/237272/7404482/26b207ee-ee98-11e4-9845-18dc00726f7a.png)

2nd

![screen shot 2015-04-29 at 5 43 31 pm](https://cloud.githubusercontent.com/assets/237272/7404486/39ae5b22-ee98-11e4-9711-70c56f960702.png)

**Comment by malgorithms** [comment]
Thanks for posting this. We need better error messages here, clearly. (I'm happy to report this is the first case I know of it happening.)  

The background: it isn't possible to do 2 tracks in parallel due to the fact that every public announcement you make on Keybase has to, in its signed announcement, reference the last announcement you made. This makes all your announcements ordered into an auditable chain.

**Comment by jrecursive** [comment]
Oh, right!  Makes sense.  Thanks for the explanation.
