### ISSUE TITLE
Twitter prove fails when twitter account is protected

### ISSUE THREAD

**Issue by kavanista** [keybase/keybase-issues#1570]
If a twitter account is in "protected mode", which cause tweets to be private, proving ownership fails, as keybase cannot view proof. 

There should probably be validation for twitter accounts in protected mode , or better error message notifications ie. in the notification mail :  "We've been checking it repeatedly, and from our perspective, it's either (a) not there, or (b) not posted precisely" could be improved to highlight this edge case.

**Comment by zQueal** [comment]
> If a twitter account is in "protected mode", which cause tweets to be private, proving ownership fails ,as keybase cannot view proof.

This is entirely by design. The concept of Keybase is publicly verifiable proofs. If tweets, and subsequently the proof itself is private, the public cannot verify it--defeating the entire purpose of Keybase. Hence, by design. It's already been discussed (I'll try and find the thread for you), and decided that this behavior will not change.

As for the error message. I totally agree. It's pretty vague and doesn't touch that proofs must be public at all times.

**Comment by kavanista** [comment]
I fully understand the design motivations and agree with you. Perhaps a quick tweak of the email template is the solution. No need to dig out the thread :-) 

Cheers !

**Comment by selfagency** [comment]
Wouldn't it make more sense if there were a secondary account like @KeybaseVerify or some such that could verify account proofs on Twitter by following the user and requiring the user to grant access to the account? The fact is that there is a lot of harassment on Twitter and that individuals are more and more often choosing to protect their accounts while granting selective access to the public. I just chose to do that this week myself.

**Comment by pkirkovsky** [comment]
Maybe Keybase can offer some kind of "low assurance" proof for protected Twitter accounts? The trust model is built on Keybase being a conduit/repository for proofs rather than a trustworthy entity itself, so a proof for a protected account (which only Keybase has access to) would require trusting Keybase itself.

Having a protected Twitter account shouldn't be an impediment to using Keybase, IMHO.
