### ISSUE TITLE
Email support

### ISSUE THREAD

**Issue by tvvocold** [keybase/keybase-issues#1628]
Like provide a email verify /show emails in public / Send someone a email in keybase.io ...

BTW, I do not like Passwd everywhere...(like track people)

**Comment by tvvocold** [comment]
@FiloSottile

**Comment by tvvocold** [comment]
@malgorithms

**Comment by Sidnicious** [comment]
Email is tricky, since every verified identity on Keybase requires a public proof. There isn't a way to publicly post some text associated with your email address.

You won't need to enter your password as much if you use the command line client. The website requires it because we need to decrypt your private key for things like tracking.
