### ISSUE TITLE
Unable to sign my own public key

### ISSUE THREAD

**Issue by kes4** [keybase/keybase-issues#1660]
Hi,
I just opened a keybase-account, and uploaded my public key.
I then installed keybase, so that I can verify myself by uploading a signature on my public key.

I tried **keybase login** with my email address, and entered my password.

However, then I receive the error message:
**error: key [some long identifier] is not owned by [my user name]@keybase.io**

config.json contains my email-address and my user name (as I logged in with my email-address, there was no typo etc. here), some salt and some id.
Also, when I encrypt a message to myself on keybase, I can decrypt it using the standard gpg command line, so I really uploaded the correct key.

And ideas what's going wrong here?

--- update ---
PS: Everything worked fine with gpg + curl, but I'm still wondering what went wrong with the keybase installation...

**Comment by oconnor663** [comment]
It looks like our latest update to the sigchain parsing code might've broken this flow. My fault. In general we expect your PGP keys to either 1) have your keybase account signed into them as an identity or 2) have made at least one signature in your sigchain, to show you control the private key. But obviously if you don't have (1), then your client needs to ignore requirement (2) so that it can actually *make* that first signature. Fingers crossed for a simple fix...

**Comment by oconnor663** [comment]
I just pushed `keybase-0.8.9`, which should fix this issue. Please reopen if you're still seeing it.
