### ISSUE TITLE
I can decrypt my own message meant for someone else. 

### ISSUE THREAD

**Issue by Xavdidtheshadow** [keybase/keybase-issues#1665]
Logged in and using the website, I can decrypt messages that I've previously encrypted for other people.

Is this expected behavior? I was under the impression that the only person who would be able to read the encrypted message was the intended recipient.

**Comment by maxtaco** [comment]
Intended. The mail is encrypted for you and them if you are logged in so
you can read it later.

**Comment by laebshade** [comment]
Expected behavior in most cases for most GUI and web based encryption clients.  If you don't want to be able to decrypt messages you encrypt for others, I recommend using the keybase command line client, which does not encrypt against your public key by default.

$ keybase encrypt -m 'test encrypt' -o out_file.asc chris
info: ...all remote checks are up-to-date
✔ public key fingerprint: 94AA 3A5B DBD4 0EA5 49CA BAF9 FBC0 7D6A 9701 6CB3
✔ "malgorithms" on twitter: https://twitter.com/malgorithms/status/433640580220874754 (you've recently OK'ed this proof)
✔ "malgorithms" on github: https://gist.github.com/8852373 (you've recently OK'ed this proof)
✔ "malgorithms" on reddit: https://www.reddit.com/r/KeybaseProofs/comments/2kpa4r/my_keybase_proof_redditmalgorithms_keybasechris/ (you've recently OK'ed this
 proof)
✔ "bitcoyne" on coinbase: https://coinbase.com/bitcoyne/public-key (you've recently OK'ed this proof)
✔ "malgorithms" on hackernews: https://news.ycombinator.com/user?id=malgorithms (you've recently OK'ed this proof)
✔ admin of keybase.io via HTTPS: https://keybase.io/.well-known/keybase.txt (you've recently OK'ed this proof)
✔ admin of chriscoyne.com via HTTPS: https://chriscoyne.com/keybase.txt (you've recently OK'ed this proof)
✔ admin of the DNS zone for chriscoyne.com (you've recently OK'ed this proof)
info: ✔ Wrote tracking info to local database
$
```

I receive an error when I try to decrypt:

```
 $ keybase decrypt out_file.asc
warn: [GNUPG:] ENC_TO D224413B1CFA6490 1 0
warn: gpg: encrypted with 4096-bit RSA key, ID D224413B1CFA6490, created 2013-10-07
warn:       "Chris Coyne <chris@chriscoyne.com>"
warn: [GNUPG:] NO_SECKEY D224413B1CFA6490
warn: [GNUPG:] BEGIN_DECRYPTION
warn: [GNUPG:] DECRYPTION_FAILED
warn: gpg: decryption failed: No secret key
warn: [GNUPG:] END_DECRYPTION
error: `gpg` exited with code 2
```

**Comment by Xavdidtheshadow** [comment]
Oh, ok. Thanks a ton!






~DB

**Comment by laebshade** [comment]
You're welcome.
