### ISSUE TITLE
Website should not use client-side password hashing

### ISSUE THREAD

**Issue by multiwebinc** [keybase/keybase-issues#1694]
I wouldn't have known this is what's happening otherwise, however when I went to sign up, I see the following message:

> Security: your keybase.io passphrase is not sent to Keybase's servers. It's salted & stretched with scrypt, in the browser.

My first thought is that salting and stretching with scrypt should be done server-side, not client side and that this *could* mean a major security issue is happening. When hashing client-side, the hash essentially becomes the new "password" (i.e. what will grant the user access). If this hash is stored directly in the database and the database is ever compromised, hackers would have easy access to any user they want by simply providing the hash stored in the database in plain text without ever needing the individual passwords because they are authenticated with the hash, not with the password. The only way that this would be as secure as hashing server-side is if it is hashed both client-side *and* server-side. If this is what is being done currently, I would propose the following change to the above line:

> Security: your keybase.io passphrase is not sent to Keybase's servers. It's hashed by your browser and the hash is salted & stretched with scrypt when stored on the server.

... Or just forget about client-side hashing. You've got an SSL certificate installed. People shouldn't be able to eavesdrop the data transmitted between the client and server. And if the client has a virus, the virus could just as easily sniff the hash as it could the original password.

See also: 

- http://security.stackexchange.com/questions/53594/why-is-client-side-hashing-of-a-password-so-uncommon
- http://stackoverflow.com/questions/3715920/about-password-hashing-system-on-client-side
- http://security.stackexchange.com/questions/23006/client-side-password-hashing

**Comment by multiwebinc** [comment]
On another note, if hashing is done by the browser, scrypt is probably an overkill. [sha-256 should suffice](http://security.stackexchange.com/a/6627/3499).

**Comment by maxtaco** [comment]
Keybase does a lot of things different from most sites.  The passphrase is hashed into a stream of data, some of which is shared with the server, and some of which is explicitly hidden from the server, since it contains secrets the server should not see.  Like the symmetric key used to protect the user's passphrase.

Moreover, after the initial signup, the server tests the client's knowledge of the passphrase hash slice by: (1) issuing a random challenge to the client; and (2) asking the client to HMAC the challenge with the passphrase hash slice as a shared key.  So it's resilient to replay attack even if TLS is broken (as it was during heartbleed).

Hashing on the client is central to this protocol.  We don't want the server to ever see plaintext passphrases, as that would blast apart a lot of our security precautions.

From a philosophical perspective, I further disagree with that SE story (link 1).  Why let the server see anything it doesn't need to see?  The plaintext passphrase is one such example.

**Comment by DavisNT** [comment]
@maxtaco In addition to HMAC based authentication (if this is not done already) I suggest:

1. Taking part (e.g. 256 bits) of scrypt output (stream of data to which user's password is hashed) that is not used anywhere else
2. Sending it to server
3. Hashing it (e.g. by SHA-256) on the server and comparing against data saved in DB

The existing HMAC-based together with suggested hash-based authentication together would prevent replay attacks (due to existing HMAC-based auth) **and** prevent authentication using data that are stored on (i.e. can be leaked from) Keybase servers (due to suggested hash-based authentication).
As the output of scrypt is already cryptographically pseudo-random I think it should not be very computationally-feasible to brute-force the last SHA-256 round done on the server. 

Is such hash-based authentication already implemented (in addition to described HMAC-based approach)? 
If this is not (yet) done **and** there are unused parts (256 or more bits) of scrypt output then implementing this should be very straight-forward (for existing users the hash could be saved in DB upon first successful HMAC-only authentication). What do you think about this?

**Comment by maxtaco** [comment]
Thanks for the comment DavisNT, but I don't see what your protocol addition proves that isn't already proven. The whole point of the protocol is for the client to prove to the server knowledge of a shared secret.  So some secret must be shared.

A potentially better protocol would be to use part of the passphrase stream as a secret EdDSA key, and send the corresponding public key on signup.  The login is that the server sends the client a random challenge, and the client just signs it.  The server of course can verify.  We implement something like this in our client we're preparing for release.

**Comment by DavisNT** [comment]
Additional benefit from my protocol is the fact that data stored on server cannot be used for authentication (I am talking about authentication to Keybase, not about decryption of stored private key) without expensive/infeasible brute-forcing.

Of course public-key cryptography is more sophisticated (more standardized and, if implemented correctly, generally better) solution for this.
