### ISSUE TITLE
Expired key requires re-proving identity again

### ISSUE THREAD

**Issue by metalivedev** [keybase/keybase-issues#1695]
Is there a better way to handle expired keys than to ask the user to re-prove their identity again on all their sites?

**Comment by metalivedev** [comment]
Note: not an urgent issue for me -- I figured out how to `gpg --edit-key` and `expire` my key to extend it. But some day I'll probably want to revoke my key and issue a new one, and it would be nice if I didn't have to go through all the proofs again. But I don't have a secure alternative to suggest.

**Comment by oconnor663** [comment]
Yes, in the future this won't be as much of an issue for people. You'll have an evolving set of keys that have mutually signed each other, and even if one expires in the future, the signatures it made in the past will still be valid (because they live in a timestamped signature chain; take a look at https://keybase.io/rufus/chain).

Key expiration in general is something we're still kind of debating how to handle. To me it seems like a concept from the old world, where key exchange was time-consuming, and where you might lose your key material and never be able to revoke it. But with signature chains this is less of an issue: Any valid key of yours will be able to revoke another one that you might've lost, and locally cached key info will have a lifetime of hours instead of years.

Whatever we end up doing with expirations, it'll have to be something transparent that ordinary people never need to worry about. (The same applies to whole concept of *keys* too :) )
