### ISSUE TITLE
not able to locate message

### ISSUE THREAD

**Issue by wdhodges** [keybase/keybase-issues#1700]
So after I make a message using the cmd prompt, I have no idea where it went or if it auto sent to the other person or what have you. Is there a certain place I should be looking for said messages?

**Comment by oconnor663** [comment]
Could you give more detail about exactly what commands you ran, and what you wanted them to do? It's hard to tell from your description.

**Comment by wdhodges** [comment]
I run the following command:
`keybase encrypt mystacx -m 'Testing for Git'`

Then I get the output:

-----BEGIN PGP MESSAGE-----
Version: GnuPG/MacGPG2 v2.0.22 (Darwin)
Comment: GPGTools - https://gpgtools.org

hQIMA9IkQTsc+mSQARAAoeIqoS7D+C3aWuymUomVJWU
e1FiqMNWJDyTzT4I5cRkiwKWLCLmPlYIO1oLhNl670l
tfp+Qof7CJDGIUx02vRydT5coUwt8MtEhJUPDGi3cAG
-some-extra-lines-omitted-here :-)
0LUvVNuYCvjR4Rt7fkfeVcSuakEpUfufGnFqow==
=4DrQ
-----END PGP MESSAGE-----

But for some reason I can't copy the actual pgp message, nor does it write to an actual file where I can get the save from. Have I set it up wrong or am I just doing something wrong / missing something?

**Comment by oconnor663** [comment]
Copying the PGP message is a matter of figuring out how your terminal handles highlighting text and copy/pasting, so it depends on what terminal program you're using. In my case on Linux with gnome-terminal, I need to use Ctrl-Shift-C to copy, for example.

To output the encrypted message to a file instead of the terminal, use the `--output`/`-o` flag. To get help about this and other flags, run `keybase help encrypt`.
