### ISSUE TITLE
keybase.io internal keyrings should sync with keyserver network

### ISSUE THREAD

**Issue by grant-olson** [keybase/keybase-issues#1771]
See #1770 for background.

If someone issues a key expiration update, or even more importantly a key revocation, and sends it off with `gpg --send-keys` keybase.io should probably know about this without any further action on the user's part.

**Comment by grant-olson** [comment]
Doh! #1770 is the issue I meant to cross reference.

**Comment by Sidnicious** [comment]
We don't pull updates from other keyservers. In fact, we're making changes that'll ask you to sign a statement into your Keybase sigchain whenever you want to update your PGP key.

We reason that if a keyserver (including ours) can create its own version of a key by combining updates, it can also maliciously omit updates. Here's an example:

1. Alice publishes a new subkey to the keyserver network. The subkey expires in one year.

2. Mallory briefly gains access to Alice's keyboard and publishes an updated version of the subkey that never expires (you can also choose to imagine Alice doing the update herself in a drunken fit of generosity to people who are lazy about keeping their keyrings up to date).

3. Alice recovers and publishes another update to the key restoring its original expiration date (or, if she's feeling particularly cautious, revokes it).

4. Mallory, who works at Keybase, sets things up so that Bob fetches Alice's key we return an older version of the key that never expires (or hasn't been revoked).

Asking you to publish key updates to your sigchain (which is publicly auditable via our merkle tree) ensures that we, as a keyserver, can never lie by omission.

Does this all sound reasonable from your point of view?

**Comment by grant-olson** [comment]
So to summarize what you're saying, keybase only wants to advertise notarized versions of your public key? I think that is an interesting idea.

I think my perspective might be a bit skewed, because I'm using gpg as my primary tool, and using keybase as a tool to assist in key authentication. And it sounds like you guys are trying to make keybase the primary tool, with OpenPGP as the crypto behind the scenes.

I've got mixed feelings on ignoring a published revocation on the main keyserver network. On the one hand, I feel like I should be able to revoke once and hope that info makes it out there on the internet. On the other hand, it's a known issue that the sks keyservers don't actually perform any crypto to verify the data they're getting. A tool that does more validation of the data itself and somehow signs off on it could ultimately be more useful.

**Comment by Sidnicious** [comment]
Correct, except your key does the signing just like now.

The difference is that Keybase-style updates and revocations each have a sequence number and a pointer to the previous statement. The `keybase` command line client builds its view of you by playing back your ordered chain of signed statements (called your sigchain), and it needs to validate the old statements that were signed by since-revoked keys.

Our new client will support multiple keys, and you'll be able to use a key to sign a statement which delegates to a new key. Both keys can stay equally valid, or either key can sign a statement revoking the other at any time. This'll hopefully solve PGP's "how to migrate to a new key" problem.

Getting back to your question: unfortunately, PGP revocation statements aren't timestamped or sequenced relative to the sigchain, so there's no way for Keybase-compatible clients to know when a key stops being valid. Which is the first non-trustworthy chain link? That's why, unfortunately, we can't find a way to use revocations that we find in the wild on the existing keyserver network.

And you're right, this does require some buyin to the Keybase way of doing things.

**Comment by Sidnicious** [comment]
I'm going to close this issue for now, since I don't think we can implement it (unless you have any suggestions), but I'd be happy to keep discussing.

**Comment by grant-olson** [comment]
Sounds good. I was just going to close it myself.
