### ISSUE TITLE
After generating keys, no way of saving private key locally.

### ISSUE THREAD

**Issue by KidPluto** [keybase/keybase-issues#1773]
The option for saving my private key to your server was selected by default.  Oh, if I had unselected that option, would I have been prompted to save my private key locally?  It appeared like I would be able to save it to your server, or not get the private key at all.  Which didn't make any sense to me.

**Comment by KidPluto** [comment]
Actually, how do I get my private key?  You have it. Can I get a copy of it from you?

**Comment by zQueal** [comment]
>  would I have been prompted to save my private key locally?

To the best of my knowledge you're _always_ given the option during generation to export your private key. However, now that I actually inspect it, the option for exporting your private key from your profile seems to be removed:
![o4eo05w](https://cloud.githubusercontent.com/assets/239193/9974897/935ff846-5e74-11e5-8e03-8ec40e70a7dd.png)

That's not cool. Hopefully this'll be fixed soon. @malgorithms @maxtaco 

> You have it. Can I get a copy of it from you?

It's not really appropriate to say that Keybase has your private key. Because they don't. They have an encrypted copy of your private key which can only be decrypted by your Keybase password. You could assume that decrypting these keys would be trivial, but the Keybase codebase is public--so you can inspect it if you want.

**Comment by malgorithms** [comment]
To clarify, we changed it because you can actually have more than 1 PGP key on Keybase now, not just device keys. Technically speaking you can, I mean...the website doesn't encourage it.  So it is no longer a top-level option, but as @zqueal said, something next to each key.
