### ISSUE TITLE
HTTP proof doesn't follow redirect

### ISSUE THREAD

**Issue by ysangkok** [keybase/keybase-issues#1801]
I can't enter https://xn--kn-1ia.guru/keybase.txt as proof. The existing proof I have doesn't work anymore, assumingly because keybase doesn't follow the redirect from the http-site. If I try and replace the domain as Unicode or IDN encoded, it doesn't work either.

**Comment by sebastiannielsen** [comment]
No, for security reasons, it shouldn't follow redirects.
It would be too easy to convince a webmaster to host a redirect for something X to something Y. Asking a webmaster to host the text file, is much more harder, since it contains human readable text, like a legal contract, that tells the webmaster that he is going to do something bad if he host it. The problem with redirects is that the target can change the documents at will, so the redirect target could be some ad for keybase (to convince the webmaster to host it), that is later changed into a keybased signed proof.

So I vote no here. For the same reason keybase isn't following CNAME's (or shouldn't if it does)

**Comment by ysangkok** [comment]
Thanks for the response, I'll close this since it is unactionable.
