### ISSUE TITLE
My friend send invite code to me, but to the email that doesn't exist

### ISSUE THREAD

**Issue by VDenis** [keybase/keybase-issues#1802]
My friend send invite code to me, but to the email that doesn't exist (wrong domain, @ google). But right domain is @ gmail.
I checked this email address -> "*Gmail:The email account that you tried to reach does not exist.*"

If i didn't enter, the number of his invite codes, that he can sent like before or zero?

**Comment by zQueal** [comment]
Your text was very hard for me to read, but if I got it right your friend sent you an invite to the wrong email address _@google.com_ instead of _@gmail.com_. If that's right, then your friend can either send you the generated text string and you can manually enter it on the Keybase website to register and simply change your email address, or your friend can reclaim ("cancel and reclaim") the invite code and resend it to the correct email address.

Hope this helps.

**Comment by VDenis** [comment]
@zQueal Thanks!!!
