### ISSUE TITLE
Deleted Key, cannot re-add

### ISSUE THREAD

**Issue by sargun** [keybase/keybase-issues#1806]
I recently added two subkeys to my gpg:
```
3c075477e55e:Downloads sdhillon$ gpg -k sargun@sargun.me
pub   4096R/8A89DFE6 2014-08-15
uid       [ultimate] Sargun Dhillon <sargun@sargun.me>
uid       [ultimate] Sargun Dhillon <sargun@keybase.io>
sub   4096R/7BEB0802 2014-08-15
sub   4096R/451066C2 2015-10-07 [expires: 2016-10-06]
sub   4096R/24C95EF3 2015-10-07 [expires: 2016-10-06]
```

If I go to https://keybase.io/_/api/1.0/user/lookup.json?usernames=sargun, the two new fingerprints do not appears. If I try to run `keybase push -u sargun@sargun.me`, I get the following:
```
3c075477e55e:Downloads sdhillon$ keybase push -u sargun@sargun.me
info: Updating both remote keys with local version
error: This key has been your eldest key before (error #922)
```

In an effort to try to fix this, I deleted my key from keybase, but now when I try to push once more, I get the following:
```
3c075477e55e:Downloads sdhillon$ keybase push --update sargun@sargun.me 
info: Updating both remote keys with local version
Your keybase login passphrase: ********************
- run scrypt [==================================] 100%
info: Updated file: /Users/sdhillon/.cache/keybase/session.json
```

**Comment by sargun** [comment]
I tried to delete my key, and readd it on the website, and now I get "Server failure: This key has been your eldest key before" from keybase itself.

**Comment by oconnor663** [comment]
Several thoughts:
- The issue you ran into at first is by design: We only show the fingerprint of the primary key within your PGP bundle.
- I don't know why `push -u` gave you an error. I'm going to try to repro that. We've been updating those API endpoints recently, and there's a good chance I broke something.
- We do actually prohibit reusing the same key, once you've deleted it. The reasons for that aren't great, but the problem will mostly go away once we allow people to have [multiple keys on their account](https://keybase.io/blog/keybase-new-key-model). In the meantime, is it easy for you to generate a new key and upload that instead of reusing the old one?

**Comment by sargun** [comment]
@oconnor663 This is _my_ GPG key. I could always create a new GPG key, but it'll just be a dangling key. Given your new model, I'd probably like to add my new public and private key, as well as my current public-key, and cross sign my keys. This comes with the problem that now my GPG configuration would have two keys with sargun@sargun.me, and breaks all sorts of things from the gpg model.

It seems like in my effort to work around a bug, I've permanently crippled my account. Can I delete my account forever, and resurrect it?

**Comment by sargun** [comment]
In an effort to add a new key, I get an exciting error:

```
ERROR: {"status":{"code":908,"desc":"You need to delete your active key before uploading a new one","name":"KEY_NEED_REVOKE"},"csrf_token":"lgHZIDg2MzllN2IyNDA0MGViYjNiZDliYjc5NTdiY2YzZTE5zlYVby/OAAFRgMDEINRfKV/ekm6ADdy0dEexwz5oSWYno6AAeeDUkUSdeoDc"}
```

**Comment by oconnor663** [comment]
Ok, there are a lot of things going on here, apologies for the confusion. Could you clarify what command you ran to produce the last error you mentioned?

There are a lot of people running into error 922 right now. See issue https://github.com/keybase/keybase-issues/issues/1803 as well. As I mentioned in there, we're going to try to have a way for people to reuse their keys within the next few days.

Both you and the people in #1803 mention hitting errors with `keybase push --update` *before* you reset your account. If so, that would be a terrible bug, but I'm unable to repro it myself. Is it possible you've deleted your key from Keybase multiple times in the past, rather than just the one time that you mentioned in your report?

**Comment by sargun** [comment]
No. I've never deleted my key before this. The steps I had:
1. I created my keybase account with a boring, normal account a long time ago
2. I added a uid (sargun@keybase.io) last night and did `keybase push --update` -- this was successful
3. I really wanted to add a public subkey, and private subkey for signing and encryption, so I could tie into the keybase API for key management, so I added them, and tried to do a keybase push --update, and it failed to recognize my key was newer.
4. I ran: `gpg --export-secret-subkey  -a 451066C2! 24C95EF3!` and pasted that into the keybase private key import dialogue, this completed successfully, but when I went to the API, I didn't see my new subkeys
5. I ran `keybase push --update`, and it failed still. 
6. I ran `keybase revoke`

**Comment by zQueal** [comment]
I'm running into this issue now, too. I just updated the expiry for my key.

    C:\Users\zqueal\Desktop
    λ gpg -K
    C:/Users/zqueal/AppData/Roaming/gnupg/secring.gpg
    -------------------------------------------------
    sec   4096R/B73E8516 2014-03-28 [expires: 2017-12-31]
    uid                  Zachary Queal <zach.queal@gmail.com>
    uid                  keybase.io/zqueal <zqueal@keybase.io>
    uid                  Zachary Queal <zachary.queal@mycampus.apus.edu>
    
    C:\Users\zqueal\Desktop
    λ keybase push --update
    info: Updating both remote keys with local version
    error: This key has been your eldest key before (error #922)

Not really sure what the issue is...

**Comment by maxtaco** [comment]
I see the issue. We can fix it with a code change on our side.  Sorry about the bug, don't do anything for the time being, we'll update you when it makes sense to try again.

**Comment by maxtaco** [comment]
@zQueal try it again?  I just pushed a server-side fix.

**Comment by zQueal** [comment]
λ keybase push --update
    info: Updating both remote keys with local version
    error: This key has been your eldest key before (error #922)

Same error. Also, webpage looks weird, now:

![mr5ojgf](https://cloud.githubusercontent.com/assets/239193/10364910/45cfff0e-6d8d-11e5-83f9-05847c861b8c.png)
![98bixga](https://cloud.githubusercontent.com/assets/239193/10364909/45ce8c82-6d8d-11e5-9495-beafdd97835c.png)

Not sure if that's intended, so I figured I'd let you know.

**Comment by maxtaco** [comment]
Thanks for noticing that.  OK, both issues should be fixed, try one last time?  Thanks @zQueal, I really appreciate your help!

**Comment by zQueal** [comment]
Anytime!

    λ keybase push --update
    info: Updating both remote keys with local version
    info: Updated file: C:\Users\zqueal\AppData\Roaming\keybase\session.json
    info: success!

Off to a great morning!

**Comment by maxtaco** [comment]
Phew.  Thanks so much. Sorry for the multiple back-and-forths.  I think now we can repro it and add it to our test suite too. Thanks!!!

**Comment by sargun** [comment]
So, can I go ahead and try to push my old key back in? Or do I still have to wait for your new multi-key stuff?

**Comment by zQueal** [comment]
Hey @sargun, sorry to hijack your issue like that. It looked like we had the same issue (error 922) so I posted to get some more diagnostic information on the books. It looks like it's fixed now, so I'd give `keybase push --update` a try and see what magic happens.

Even if not, @oconnor663 [says here](https://github.com/keybase/keybase-issues/issues/1803#issuecomment-146574020) that the fix could be ongoing and to check back in a few days. Hope it works for you, though.

**Comment by oconnor663** [comment]
You won't have to wait for the full multi-key stuff, but we need to land a small feature on the site and then relax an assertion in our DB.

The short version of this story is that your sigchain is continuous across resets, and only ever contains statements signed by you. Since an account reset isn't a signature you make (because you might've lost your keys), it's not directly represented in the sigchain. Previously when replaying your chain, other clients would notice the reset by seeing that the "eldest key" referred to by new links had changed. The major downside there was that doing a reset and then reusing your old eldest key would confuse clients, which is why we had the restriction that you've run into. We're going to relax that by requiring that the first new signature after an account reset be of a specific "eldest" type, so that clients can recognize the reset even though the eldest key might not've changed.

I might've lied when I said that was short, sorry about that :p

**Comment by oconnor663** [comment]
Ok, reusing an eldest key should be possible now. You'll need to upload it via the website, either by having an your encrypted private key on our server, or by using the "command line with [bash + GPG + cURL]" option. (The command line `keybase` client won't work for this upload until the next major version is released.) Please try it and let me know if you run into any problems.

Known issue:
- The command line `keybase` client should generally work again after you get your key uploaded, but reusing the same BTC address runs into an error. As above, doing it in the browser is a workaround.
