### ISSUE TITLE
can't update my PGP key

### ISSUE THREAD

**Issue by oconnor663** [keybase/keybase-issues#1811]
Creating this issue in anticipation of people Googling this error:

    error: Tried to update a full-hash PGP key without a new full hash. (error #924)

You will see that if you've uploaded a PGP key using the website recently, and then you try to update it again using the NodeJS command line client. For now, the workaround is to use the website again. When we release the next major update to our command line client, key uploads from the client will work again. Apologies for the trouble in the meantime.

**Comment by jgravois** [comment]
granted, i have no idea what i'm doing, but i ran into the error above today.

#### STR:
1. i used keybase to create a new public key a few days ago.
2. i used GPG keychain to add an additional User ID afterward to attempt to associate an email address that i own.
3. i *hoped* that calling `keybase push --update` would ensure that the one person who tracks me could access the update and send me an encrypted email message

    > thats when i hit the error

4. afterward, i right clicked my own key in *GPG Keychain* and was able to copy/paste it in the keybase UI successfully.  

i'm not positive i'm even going about things correctly, but i wanted to let you know just in case it is and what i encountered isn't expected behavior.

**Comment by oconnor663** [comment]
Yes, I think that's expected, if I'm summarizing correctly:

1. You created an account and generated your initial PGP key using the website.
2. You later tried to upload a modified version of that key using the `keybase` command line, which failed.
3. But the same upload worked OK when you did it again on the website.

Sorry for the trouble in the meantime. All of this will work better when our new command line client is out; should just be a week or two.

**Comment by jgravois** [comment]
> All of this will work better when our new command line client is out; should just be a week or two.

thats good enough for me.  thanks for your work on the project!

**Comment by oconnor663** [comment]
Thanks for helping us test!
