### ISSUE TITLE
File-based PGP encrypt & decrypt hang indefinitely

### ISSUE THREAD

**Issue by redoPop** [keybase/keybase-issues#1868]
Encryption and decryption of whole files via `keybase pgp` are hanging indefinitely on both of my devices. e.g.:

```
$ echo 'This is a test.' > test1.original
$ keybase pgp encrypt test1.original
```

(Hangs.)

Piping the files as plain text however works just fine:

```
$ echo 'This is a test.' > test2.original
$ cat test2.original | keybase pgp encrypt > test2.encrypted
$ cat test2.encrypted | keybase pgp decrypt > test2.decrypted
$ cat test2.decrypted
This is a test.
```

…as does message encryption (using the `-m` option).

Encryption & decryption using GPG directly works fine, too:

```
$ echo 'This is a test.' > test3.original
$ gpg -r joe@redopop.com -o test3.encrypted -e test3.original
$ gpg -d test3.encrypted > test3.decrypted
```

(In both of the "working" scenarios I did make sure that the `.encypted` file was, in fact, encrypted!)

Client details:

* OS X El Cap (10.11.1)
* GPG Suite:
	* MacGPG2 (version 2.0.28)
	* GPGPreferences (version 1.5)
	* GPGServices (version 1.10.1)
	* GPG Keychain (version 1.2.1)

```
$ keybase version
Client:  1.0.0-47
Service: 1.0.0-47
```

Happy to share any other details that might help debug this issue! At first I thought this might be a passphrase issue as in #110, #515, #1053, #1240, but the fact that piped plain text and message-based encryption work just fine suggests that's probably not the case.

**Comment by maxtaco** [comment]
Are you sure they are not reading from standard input?

**Comment by redoPop** [comment]
You're right. Pressing `^D` returns to the terminal with the error:

```
▶ ERROR openpgp: invalid data: tag byte does not have MSB set
```

**Comment by patrickxb** [comment]
You need to specify the `-i` flag to encrypt a file.

`keybase pgp encrypt -i test1.original` in your first example.

Here's the help for the command:

NAME:
   keybase pgp encrypt - PGP encrypt messages or files for keybase users

USAGE:
   keybase pgp encrypt [command options] <usernames...>

DESCRIPTION:
   If encrypting with signatures, "keybase pgp encrypt" requires an
   imported PGP private key, and accesses the local Keybase keyring when producing
   the signature.

OPTIONS:
   -l, --local		Only track locally, don't send a statement to the server.
   -y			Approve remote tracking without prompting.
   --skip-track		Don't track.
   --no-self		Don't encrypt for self.
   -s, --sign		Sign in addition to encrypting.
   -m, --message 	Provide the message on the command line.
   -k, --key 		Specify a key to use (otherwise most recent PGP key is used).
   -b, --binary		Output in binary (rather than ASCII/armored).
   -i, --infile 	Specify an input file.
   -o, --outfile 	Specify an outfile (stdout by default).

**Comment by patrickxb** [comment]
Same goes for `pgp decrypt`.  Here's the help:

NAME:
   keybase pgp decrypt - PGP decrypt messages or files for keybase users

USAGE:
   keybase pgp decrypt [command options] 

DESCRIPTION:
   Use of this command requires at least one PGP secret key imported
   into the local Keybase keyring. It will try all secret keys in the local keyring that match the
   given ciphertext, and will succeed so long as one such key is available.

OPTIONS:
   -l, --local		Only track locally, don't send a statement to the server.
   -y			Approve remote tracking without prompting.
   -s, --signed		Assert signed.
   -S, --signed-by 	Assert signed by the given user (can use user assertion format).
   -m, --message 	Provide the message on the command line.
   -i, --infile 	Specify an input file.
   -o, --outfile 	Specify an outfile (stdout by default).

**Comment by redoPop** [comment]
D'oh! That's embarrassing. Thank you so much.

I was relying on [these docs](https://keybase.io/docs/command_line#encrypting-a-pgp-message) and those displayed on users' account pages, which may need to be updated. e.g.:

```
keybase pgp encrypt chris foo.txt -o bar.asc
```

Should be:

```
keybase pgp encrypt chris -i foo.txt -o bar.asc
```

Thanks again for your help!

**Comment by malgorithms** [comment]
thanks for catching this bug in the documentation, @redoPop  - I was unaware we changed this. Fixed!

**Comment by dulowski-marek** [comment]
`keybase pgp decrypt` problem still persists in latest version Git Bash  on Windows 10, regardless of having specified `-i` option.

### Workaround ###
When keybase is minimized to tray, it won't invoke the password prompt GUI. Solution is to open keybase window beforehand.

**Comment by zanderz** [comment]
I can't get a password prompt to appear in any use of `keybase pgp decrypt`. If I'm logged in, it works. If I'm logged out, it says at the CLI `- ERROR decrypt error: unable to find a PGP decryption key for this message`
Must be configured differently?
