### ISSUE TITLE
You can't delete your keybase.io username (error 915)

### ISSUE THREAD

**Issue by rEtSaMfF** [keybase/keybase-issues#1911]
https://keybase.io/retsam

1. Every key has expired.
1. I do have my private key.
1. I have updated the expiry on my private key (so now I want to update the public key).

`keybase -d --log-format file pgp update 2> update.txt`
[update.txt](https://github.com/keybase/keybase-issues/files/57123/update.txt)
> You can't delete your keybase.io username (error 915)

What do I need to do here? Maybe something related to subkeys?

**Comment by oconnor663** [comment]
You've hit something of a corner case where, because you previously had "retsam@keybase.io" in your public key, the server refuses to let you upload a new version of the key without that ID in it. The immediate workaround would be to use `gpg --edit-key` to add that ID back in, and then try the upload again.

The original rationale for that check was, there used to be two ways to claim ownership of a PGP key:
1) sign some proof with it that references your keybase account
2) have your keybase account in the set of key IDs (this is mostly obsolete, but still possible)
If you proved ownership of your key using approach (2), removing the ID could put your account into a weird state, and we have server logic to stop you from doing that. But that check should be smart enough to allow it once you've accomplished (1), and right now it isn't. We should be able to clean that up.

Sorry for the trouble here, and thanks for the report.

**Comment by rEtSaMfF** [comment]
Whee corner case.

Thanks for the explanation and resolution.
Everything works now!

Go ahead and close this.
Or leave it open until we have better error messages and such.

**Comment by oconnor663** [comment]
I just filed a couple internal issues for us (for my own reference):

https://keybase.atlassian.net/browse/CORE-2223
https://keybase.atlassian.net/browse/CORE-2224

**Comment by 00dani** [comment]
Please reopen - this is still an issue in current versions of Keybase. I'm running `1.0.20-20170309192151+e30557a` on MacOS and attempting to remove the `00dani@keybase.io` UID from my public key produces the same error, "You can't delete your keybase.io username".

**Comment by maxtaco** [comment]
@00dani can I set up mail forwarding for you?  That might be the easiest fix.

**Comment by 00dani** [comment]
@maxtaco That'd be excellent, if it's still possible! I'd thought @keybase.io email forwarding had been shut down?

**Comment by maxtaco** [comment]
We're making one-off exceptions!

**Comment by 00dani** [comment]
Great! In that case, yes please, I'd like `00dani@keybase.io` to forward to my primary email at `gopsychonauts@gmail.com`. ✨

**Comment by robison** [comment]
Not to piggyback too much but - should I open a separate issue if I have this precise same issue? Thanks!

**Comment by oconnor663** [comment]
@robinson one workaround here might be to `keybase pgp drop <your key>` from your account, and then do `keybase pgp select` over again with the newly-modified version of your key. Does that work for you?

**Comment by robison** [comment]
@oconnor663 I think you tagged the wrong user in there, but I think I solved my issue - will know shortly, and also share the results. Thanks!

**Comment by oconnor663** [comment]
Woops! Sorry at-robinson, thanks @robison :|

**Comment by imrehg** [comment]
Tried @oconnor663's workaround of `drop` and then `select`, that solved it for me.
