### ISSUE TITLE
Getting "your web proof just broke" after moving to CloudFront

### ISSUE THREAD

**Issue by tombrossman** [keybase/keybase-issues#1923]
I moved my previously self-hosted HTTPS site to CloudFront. It is still served via HTTPS, all is tested and working. My proof and its path/location remain unchanged, it is and has always been at https<span></span>://www.mydomain.tld/keybase.txt.

After logging in to my account at Keybase.io and trying "My proof is now live; retry!" I still get the same error. _"your previously-proven web identity https<span></span>://www.mydomain.tld just broke. We've been checking it repeatedly, and it's not working from our perspective."_

The only change at my end was the move from a VPS to CloudFront. I'm aware of bug #1711 which occurred after the user moved their proof to a different path, which is not the issue here. My path isn't changed. How can I troubleshoot this further please?

I've used generic examples above but my individual [proof is here](https://www.tombrossman.com/keybase.txt), if anyone wants to test it. Apologies in advance if this is a noob error in configuring CloudFront, it wouldn't be my first one.

**Comment by dhess** [comment]
I just did the same (moved a self-hosted site to CloudFront), and about 12 hours later I'm having the same problem as @tombrossman: Keybase claims it can't verify my web identity anymore, despite repeated attempts to re-verify.

You can check for yourself that my signed identity is still working, and the path is the same:

https://www.drewhess.com/keybase.txt

**Comment by dtiersch** [comment]
@tombrossman I accessed your proof via ´curl´ and it returned a gzip-compressed file. That *could* be an issue if it has to be cleartext.
But that wasn't an issue with @dhess, maybe there is additionally something weird going on on CloudFront. Your reply header looks rightish, though:
```
HTTP/1.1 200 OK
Content-Type: text/plain
Content-Length: 2842
Connection: keep-alive
Date: Tue, 26 Jan 2016 21:42:02 GMT
Last-Modified: Mon, 25 Jan 2016 04:15:20 GMT
[...]
```

**Comment by tombrossman** [comment]
@dtiersch Gzip on CloudFront was something I only just learned of and enabled this week. It might explain why proof fails now, but could not have been the original cause.

**Comment by dhess** [comment]
I believe I've resolved my issue. If I'm right, it was a configuration error by me.

I didn't understand how Cloudfront's Origin method works with S3. I had it set to Match, so that, if the web client making the request uses HTTPS, Cloudfront should also use HTTPS to retrieve the content from the origin. However, when S3 is configured as a website endpoint, it doesn't support HTTPS connections. (See http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/RequestAndResponseBehaviorS3Origin.html#RequestS3Protocol for confirmation.)

I've now changed the Origin method to HTTP, and now Keybase is able to verify my web-based identity again using the Cloudfront CDN. I'm not sure why I was able to retrieve *any* content from my Cloudfront-hosted site before I made this change, so that's odd, but in any case, I think the issue is resolved for me.

**Comment by tombrossman** [comment]
I've moved my site off CloudFront and am now self-hosting as before, and verification works again, so I'll close this issue. Still have no clue what went wrong with using CloudFront.

**Comment by maximz** [comment]
I continue to have this issue -- it should be reopened. After a move to Cloudfront, my verification fails. I replaced with a new verification and it continues to fail. I am using a Cloudfront custom SSL certificate for my domain name, with S3 backing.

**Comment by oconnor663** [comment]
I think the issue in these cases is that servers are returning gzip data when the client did not send the `Accept-Encoding: gzip` header. That's why `curl https://www.maximzaslavsky.com/keybase.txt` prints a bunch of garbage to the terminal, for example.

**Comment by maximz** [comment]
Good catch, thanks @oconnor663 !
