### ISSUE TITLE
Ability to change username

### ISSUE THREAD

**Issue by litui** [keybase/keybase-issues#193]
There are many reasons one may want to change one's username, from an across-the-board change of handle on all services, to work/life separation, to change of employment, to a desire to use a different handle for just this service.

The ability to change username should probably break verifications given that it's a significant change and as noted in other issues the plan is to include <username>@keybase.io in the GPG key as well.

**Comment by lilyball** [comment]
I would like this to be reconsidered.

I'm changing my complete identity, both online and in person. I would really like to be able to change my keybase username as part of this. I recognize that doing so would be functionally equivalent to deleting the old account and creating and new one, and would require re-issuing proofs and whatnot, but I think that's acceptable in my case. What's stopping me from actually just doing that is the inability to link from my old name to my new one.

Here's my wishlist for account renaming:

* A new account would be created with the new name.
* The old account would publish a signed statement indicating that it's being replaced by the new account. Any information that can be moved to the new account would be (ideally including the public key), including files, git repos, and Stellar wallet(s).
* The old name would not be freed up. Visiting the old profile on keybase.io would redirect to the new one (either HTTP 301, or a landing page that explains that the profile was renamed, information what it was named to, and I guess access to the sigchain for the old account and any proofs that are still valid).
* I would be prompted to re-issue any proofs under the new name. Ideally the UI would retain this prompt for as long as I still have a proof on the old account that hasn't been re-issued for the new.
* Any valid following statements on my old account would be reissued with the new account (not updated for new proofs, just reissued as they existed before; this should include following statements that reference defunct proofs as well, it should be the exact same statement just signed with my new account).
* People who've followed my old account already should have that following statement marked as needing to be updated, in exactly the same fashion as a following statement that references a defunct proof. Attempting to update the statement should inform them that my account has been renamed and prompt them to move the follow to the new account instead (this would be equivalent to just unfollowing my old account and following my new one).
* All of my devices should be prompted the next time I open the app to switch to the new account. I assume this should be able to be seamless, if the new account still uses the same private key(s) as the old.
* Any teams I'm an owner of should be updated so the new account is the owner (and the old account probably removed entirely)
* Any teams I'm an admin of should be updated so the new account is an admin (and the old account probably removed entirely)
* Any teams I'm a member of, if possible it should add my new account and remove my old. If this isn't feasible (I'm not sure how teams actually work) then it should prompt the owner/admins to approve the new account.
* Any chats I'm participating in should update automatically to the new account. I'm not sure how to actually accomplish this, perhaps just by posting a special message to the chat indicating the account replacement and all participating clients understand to replace the account on any new messages.
* All chats I'm part of should presumably post a user-visible message indicating the name change.
* My new account should have access to the chat history from the old. Since it presumably has the same private key(s) that shouldn't be a problem.
* Accessing git repos over `keybase://` should just automatically redirect to the new username, such that accessing a repo with my old name works like accessing the repo with my new name.

I'm not sure about sharing files with other people. Ideally this could also update automatically to the new name, but I don't know how this actually works internally so I don't know if that's something my account could unilaterally do.

---

Now that I've typed this out, this sounds like a lot of stuff. Being able to do all this would be fantastic, but to be honest, I'd be willing to accept just "lock the old account and put up a statement that it's been replaced with the new one", as long as it's possible for me to migrate my data myself (even if this means losing chat history, that's not critical to me, though it may be to other people).

For some context, the reason I'm changing my identity is I'm a trans woman and am going through transition. Luckily my old username is not based on my old legal name, but it's still a username I'm trying to distance myself from. For any trans people whose username is based on their old legal name, the ability to rename their account is even more important.

**Comment by jdcrunchman** [comment]
I definitely would want to maintain two different identities with absolutely no links to each one.  And be able to switch from one to another.  I can see a need for that.  I wonder why they make it hard to do that?

**Comment by chindraba-work** [comment]
I wonder how easy they could make that?
Perhaps as easy as a click?
![Screenshot_20200605_063750](https://user-images.githubusercontent.com/35464762/83844837-44d27e80-a6f7-11ea-821f-70f459f0a3ce.png)
