### ISSUE TITLE
Keybase isn't asking for a password when I sign or encrypt messages

### ISSUE THREAD

**Issue by echosa** [keybase/keybase-issues#1930]
I don't know if I set something in the config or what, but Keybase isn't asking me for my gpg password when I sign or encrypt messages. If I use gpg itself, I have to put in my password, of course.

This seems like a security hazard. If someone gets access to a terminal on my computer, they can sign things as me.

Did I enable something without realizing it, or is this default Keybase behavior?

**Comment by maxtaco** [comment]
Which version?

**Comment by echosa** [comment]
keybase version 1.0.6-0 installed via homebrew running on OS X El Capitan 10.11.2.

**Comment by maxtaco** [comment]
Encryption we wouldn't expect any secrets to be needed, since it's public-key encryption.

For decryption and signing, we keep you secret key unlocked and in memory until you explicitly run `keybase logout`.  We know that in the past the case you brought up has attracted a lot of attention, but in our opinion, if someone can sit down at your terminal and start issuing commands, they can totally root your computer, and then there's nothing we can really do.  

The alternative of constantly asking people for passphrases is annoying.

BTW, GPG with agent running has much the same behavior, though it does have a shorter default timeout.

**Comment by echosa** [comment]
Fair enough, and good points. Just found it oddly "open" after using gpg itself (without agent). Closing this ticket. Thanks!
