### ISSUE TITLE
Graph lists PGP Update as "preformed no action"

### ISSUE THREAD

**Issue by BrandonIngalls** [keybase/keybase-issues#1947]
I realized that I had forgotten to set preferences on my public key just a bit ago and then did a 

```
keybase pgp update
```

That worked just fine, but when I went to look at the update on my [chain](https://keybase.io/bi/sigchain#b6c574b39748df068a6fccfa88267b6b2afc313121dc4c8034fab0c71a7e01590f), I noticed that it is titled as 'preformed no action'.

This is just a minor feature request to have 'pgp_update' actions listed as so.

**Comment by oconnor663** [comment]
Good catch, we need to fix that.

**Comment by loxley** [comment]
Actually, today I updated some of my uid's and sent them to the keyservers. So I figured I wanted to refresh the info on keybase aswell, but it seems `keybase pgp update` never updated the info of the uid changes. Because when I tried exporting my keys and then import them the OLD uid (i had only one, now i have 1 revoked and 2 new) was the one showing up. It would be nice if the uid's would have been updated. I know i can just do `gpg --refresh-keys` in gpg but I would like that info be in the exported output file from keybase.
