### ISSUE TITLE
Unable to add previous device name on reset account

### ISSUE THREAD

**Issue by BrandonIngalls** [keybase/keybase-issues#1952]
So I reset my account 2016-01-05 after encountering an error with my private key, I just got back home from a vacation and tried to add my Desktop as a device by typing in the verification code on my laptop.

The secret was successfully exchanged and I was asked to name my new device, so I named it what it was before and got the following error...

```
▶ ERROR Device name is already in use by this user (error 1408)
```

When I list my devices one with the name of ProdFox does not show up.

```
Name                         Type         ID
==========                   ==========   ==========
DevFox                       desktop      185700a54652f3f42bd48fd676161718
Paper Key (soap employ...)   backup       d9fdc043e6882ebffdc432d82de93418

```

I am pretty sure I used the name DevFox for my laptop in the past so it looks like the bug only shows itself when adding a new device -- not the first device.

**Comment by BrandonIngalls** [comment]
As an update, I just signed my new PGP key with my old key -- before I revoke my old key -- on my desktop and was unable to use the following keybase command...
```
$ keybase --debug pgp update
17:19:19.160685 ▶ [ERRO keybase main.go:48] 0df No device found for device ID f8aa88eed1494cca08fce6ef4ef37218
```

**Comment by maxtaco** [comment]
It's intentional that we don't allow device name reuse, but that second bug you hit is definitely a bug.  Very frustratingly, it's one that @patrickxb thought we had whipped.

Which machine did you get that `No device found for device ID` error on? One involved in the failed provisioning attempt? The one you tried to name `ProdFox`? Did you eventually get past this state by clearing your config files?

Thanks for you help, we greatly appreciate it

**Comment by BrandonIngalls** [comment]
Awesome, now keybase decided to kick me from my Desktop device...

```
[~]$ keybase status
▶ ERROR Not logged in.
[~]$ keybase login
▶ WARNING device id mismatch session <-> env
How would you like to sign this install of Keybase?

(1) Use an existing device
(2) Use a paper key
(3) Use my Keybase passphrase
(4) Use GPG

```

**Comment by maxtaco** [comment]
Urg, one sec, let me look for that error, I've never seen it before

**Comment by maxtaco** [comment]
Try a `keybase logout` and then try to login again?

**Comment by BrandonIngalls** [comment]
@maxtaco, so I can't rename a device even after resetting my account? I guess it makes sense to dissuade an attacker from pretending to be that device in the event of a takeover.

I got the ```No device found for device ID``` error on my Desktop ProdFoxV1, which I just used a paper key to readd the same machine as ```ProdFoxV2```

**Comment by maxtaco** [comment]
@patrickxb I think we should start to repro this issue by provisioning a new device and specifying a device name already in use. I'm not sure if we've tested that case.

**Comment by BrandonIngalls** [comment]
After the little hiccup where keybase logged me out and lost my device key for ```ProdFoxV1``` I removed my .config/keybase and .local/share/keybase folders -- which I did before installing 1.0.7 -- and then signed in with a paper key, before I used a previous device to sign in.

When I used the paper key everything worked as it should, and I was able to update my PGP key with ```ProdFoxV2```

```
[~]$ keybase pgp update
▶ INFO Posting update for key 7462593a58b93bbf2573a9cc9ee26a433ca32060.
▶ INFO Update succeeded for key 7462593a58b93bbf2573a9cc9ee26a433ca32060.

```

**Comment by patrickxb** [comment]
@maxtaco We have a test for duplicate device name already:

https://github.com/keybase/client/blob/master/go/engine/login_test.go#L836

**Comment by maxtaco** [comment]
Ok cool.  There's the additional detail of having reset an account, and having the conflicting device name from the previous subchain.

**Comment by seanfarley** [comment]
I just ran into this account reset / device reuse when experimenting with keybase. From an UI perspective, this is very unintuitive (especially since my sigchain lists a bunch of old / useless keys that I created just for testing). At the very least, there could be some explanation on the command line?

As for a practicality issue, I get a new laptop every ~1 year from work and use the same name for each new one. Should I begin naming each device uniquely?

**Comment by malgorithms** [comment]
@seanfarley  - we're pushing changes to make it clearer when you hit this error. As demonstrated by @BrandonIngalls  at top of this thread, it was unclear that revoked device names are still considered locked.

The reason of this restriction is pretty important: we want people to be able to think of devices by name - say, when seeing them in a list, or when talking about them - and never have to think about key fingerprints or id's. The only way to achieve this safely is to make a device<->name map immutable and global, using the sig chain. Otherwise there are endless caveats and visual explanations needed showing the evolution of a device name over time. 

Consider: if an intruder steals one or more of your keys and starts doing crap to your sig chain, they still can't change the definition of "iphone6s-white". It is set in stone, which is crucial to maintain the abstraction that "iphone6s-white" is a certain key.

But yeah, we will try to make this all clearer. thanks!

**Comment by seanfarley** [comment]
Fair enough. Thanks for making future better messages :-) I guess I'll go with my laptop-YEAR naming scheme then.

**Comment by sporkwitch** [comment]
I get the reasoning, but maybe include a datestamp of when the device was last changed?  I'm with the others, my current gaming desktop always has NameX, my current development laptop NameY, my current gaming laptop NameZ.  As a workaround I can just do that myself, NameX-[date of provision], but then the app isn't being used as you say you want it to, I'm no longer just thinking "ok, dev laptop, so NameX," I actually have to pull the list, read it, and enter it.  If the name of a device has changed, it could notify you the first time you try to refer to that device after that change (similar to "a new device has logged into your account, if this was not you..." emails).  Or, for that matter, we could send an email when a device changes, exactly like that.

This seems to achieve keybase's goal, while not disrupting the workflow and decades-long habits of its users.

**Comment by kitingChris** [comment]
I reinstalled my OS and want to reuse my device name. 
I do not want to rename my device... :O 
How can I reinitialise my device with the same name? Backup is still there. What does it need?

**Comment by jooize** [comment]
I want a summary of how to name devices with Keybase. How will the names be used?

What's the idea when a device is lost or compromised?

I'd like to be informed about not only the technical reason it has to be this way, but how to work with it.

People may have different setups including several similar devices. Can we develop a generic naming scheme?

`<DeviceType>-<ID>-<Iteration>` or `<DeviceName>-<Iteration>`?
First laptop: `Laptop-1-1`. After first recreation (lost/compromised/...): `Laptop-1-2`.
Third phone fourth iteration: `Phone-3-4`.
I imagine many people have a `Laptop-Work`. Third work laptop first iteration: `Laptop-Work-3-1`.
I call my laptop `HipAir` (which I initially used and then reset my Keybase account). `HipAir-2` would conceivably be the next name I use following that convention.

I guess we could omit the identifying `-1` on the first iteration, but will likely need a number eventually and consistency is often useful.

> we want people to be able to think of devices by name - say, when seeing them in a list, or when talking about them - and never have to think about key fingerprints or id's.

How compatible can a naming scheme be with that?

Loss and compromise shouldn't be more of a hassle than it already is. People shouldn't be discouraged to discontinue use of a compromised key for the sole purpose of keeping a clean device name.

Is there no way we can reuse names such as `Laptop` and `Phone`? Perhaps it's actually impossible, but can the sigchain not be used to track updates of device name to ID mappings? I realise there may be user experience difficulties, but the current situation seems to have issues as well.

**Comment by memiux** [comment]
Same, now my graph is ugly <sup>af</sup> 😭

**Comment by maxtaco** [comment]
Hi @kitingChris, sorry it took forever to reply.  You basically need to copy over `~/.config/keybase` on Linux or `~/Library/Application Support/Keybase` on OSX.  In particular, you need the `config.json` file, and *most importantly*, you need `secrets.you.mpack` for whatever "you" is.  That mpack file has your device-specific secret keys.

**Comment by kitingChris** [comment]
Thats much needed to know when migrating... unfortunately not known and now my naming scheme is fucked up :(

**Comment by allenbh** [comment]
Security is nice and all, "but it's my identity" is also a valid complaint.  It would be nice to have a clean reset option that not only resets the key, but also the sigchain for those of us who like to experiment with a few false starts before using the service for real.

I guess this issue is due to the sigchain not being reset.  If I `keybase sigs list` after a reset, the first sig is not zero or one.  On a related note, I also can't find a way to get keybase to print the earlier sigs, not `keybase sigs list --all` or `keybase sigs list --revoked`.

**Comment by jcreigh** [comment]
I agree, my sigchain is all kinds of messed up because I was testing things and it was _not_ clear that resetting didn't actually reset everything, and it was _not_ clear that I wouldn't be able to reuse device names. I would like to completely start from scratch now that I've gotten used to the service, but I see no way of doing that, other than deleting my account and eventually creating a new one with a different username.

"Start from scratch" should mean just that. If I can delete my account from the web interface, I should be able to clear my sigchain and all the history.

**Comment by jcreigh** [comment]
Nevermind about the sigchain, I just needed to start readding stuff for it to actually show up reset. Still annoying you can't reuse device names after a reset.

**Comment by algesten** [comment]
Seriously. I was just testing stuff and realised I built a bad chain, and wanted to start over. At no point was I informed that my device names are used up and never to be used again. This is not intuitive or helpful.

**Comment by MasterRoot24** [comment]
I have to chime in here and say that this is pretty bad UX!

I've just rebuilt my laptop but didn't remove from Keybase before the rebuild and now I can't use the same device name.

So, I reset my Keybase account in a hope that I could "start afresh" just as the Keybase site tells me I can do, only to find that my device name is still locked and can never be used again.

Grrr 😡

**Comment by MasterRoot24** [comment]
I still have access to the backup of my laptop prior to the rebuild, so if there's some way I can retrospectively remove the old device with the name I want to use, please let me know!

**Comment by elad** [comment]
@malgorithms I'm sorry, but your reasoning as to why you don't allow device name reuse is inadequate.

On one hand, you try to improve the UX of public key encryption by making people think of devices in term of names rather than fingerprints. On the other hand, device name is something people are used to being able to change. This violates POLS and confronts people with the reality that "well, yeah, it's a device *name* but it behaves exactly like a *fingerprint*." Furthermore, it adds exactly zero security because an attacker can always use "MacBookAir" if I had revoked "MacBook Air". What will happen is that people will make mistakes as people normally do, and then end up with messed up device names, resulting in *decreased* ability to identify devices ("was it MacBookAirNEW or MacBookAirFIXED?"), hence, less security.

What you *should* be doing is keep an unmodifiable ("append only") audit trail instead of enforcing silly restrictions.

**Comment by malgorithms** [comment]
Hi @elad - we do have an unmodifiable ("append only") audit trail. It's the signature chain of announcements you've made, and you can see yours here:

https://keybase.io/elad/sigchain

In turn, that chain is in our merklee tree, to prevent against forking attacks.

As you're suggesting, I've left a bit out... it would be possible to support device name reuse inside this sig chain, and it's not even that hard.  But it isn't simple from a UX security perspective. 

 Just scratching the surface: whenever an interface presented a device name to you or someone you interacted with, that experience would need to present relevant changes. `Signed by chris using work-imac-5k` for people who care about devices would have to become: `chris's work-imac-5k is no longer the same device you dealt with previously....here are how and when the keys changed.`  Further, interfaces around managing your own devices would get more complicated and confusing. If I lose my iPhone and fear it's been compromised, I can go to my desktop and revoke my iPhone keybase key by device name. But I don't have to worry about revoking my `cc-macbook-2016` because whoever stole my phone couldn't have revoked the old one and created a new one with the same name.  It's *plausible* to solve all this through notifications and alerts that `cc-macbook-air-2016` has changed definition, but there are dozens of places across our user experience that will get a lot more complicated.  It will be many person-months of work to implement a safe device name reuse.  Right now we're faced with an incomplete app, and there's such an easy user workaround to this.

Aside, I think this is one thing Apple has gotten wrong...I always fire up a laptop and get like 5 notifications about "you've started using iMessage on a new computer: 'chris's iphone'" and I never know what half of them are because they're device recoveries followed by manual renames. Someone could be slipping an extra device in there, of course, and I wouldn't know.

You can call all this "inadequate" if you like, but just as a reminder our apps really are incomplete.  There's so much more we need to get done...and there is an easy workaround. Just pick a new device name.

Apologies to everyone who wishes this were a priority.

**Comment by elad** [comment]
@malgorithms I appreciate the explanation. You had me with the Apple analogy. Moreover, if it would take a lot of work to implement I agree there's no point (or rush). Thanks! :)

**Comment by powder** [comment]
Just chiming in, start from scratch should be just that.  I don't care if i lose all previous account data, and I understand the reasons for it, but, not being able to reuse the same name is very counterintuitive especially after I remove that device.  It's horribly annoying.

is the recommended fix just to add some numeric identifier?  'ComputerName 001' ? and count up?

**Comment by zQueal** [comment]
> Just chiming in, start from scratch should be just that. I don't care if i lose all previous account data, and I understand the reasons for it, but, not being able to reuse the same name is very counterintuitive especially after I remove that device. It's horribly annoying.

It may be annoying but a public ledger of unique device names is good for security. Just my opinion, maybe.

**Comment by nelsnelson** [comment]
I name my registered keybase devices for the hostnames of the reference machine systems to keep track of which is which.

I was recently forced to wipe and reinstall my system -- was there some sort of key or registration code which was on my device's file system which I neglected to back up and migrate to the freshly installed system in order to use the same hostname to identify the registered keybase device?

**Comment by cjb** [comment]
@nelsnelson Yes.

**Comment by nelsnelson** [comment]
So, now that I have mistakenly neglected to migrate that device key, why is it absolutely impossible to replace the device by that particular name string?

**Comment by cjb** [comment]
Here's my understanding.

Short answer: Because our software breaks if the mapping between device name<->device key changes over time.

Long answer: Lots of people have expressed frustration at not being able to reuse device names, so it's likely that we'll try to find a different design that relaxes this constraint in future.  But since we have no such design or implementation today, we can't allow device name reuse today.

Longer answer: The constraint is intentional -- we're using "<username>'s <device name>" as an immutable reference to a device key in several places.  If that's not a unique mapping anymore, we need to invent a different mapping that is unique.  We don't have a design for what that mapping would be or how we'd communicate it to users.  It would presumably have worse UI than our current design, because human friendly strings are very convenient to share with users when they work, and it sounds like this new design wouldn't be able to use human friendly strings, because when we use human friendly strings people ask us to reuse them to mean something else later, and we want a unique mapping.

**Comment by nelsnelson** [comment]
Thank you for the explanation, @cjb!  That makes a lot of sense to me.  Perhaps there could be an additional mapping to support human friendly string names as device identifiers -- one mapping from the key to a device id, and then another mapping from a device id to a name.  The user could drop the device name, and relink a different device name to the same id -> key map later.

Devices seem to be a bit of a model abstraction mismatch.  I understand the usability purposes of referring to devices, though.

Do you think it would be feasible to preserve the current approach (unique device name -> key mapping) while still augmenting the functionality with an additional mapping (unique device id -> key)?

**Comment by virtualdxs** [comment]
@malgorithms I understand what you're saying, but I'd say at least clear it when the account is reset. I think everything that happens when you reset is adequate to say that foo's device bar may not be the same device it used to be, as theoretically foo might not be the same person they used to be. I'm in the same boat where I use hostnames for device names, and that's why I think this should be changed. I wiped Keybase and started over and now cannot use k7dxs-server as the device name for k7dxs-server.

**Comment by rawkode** [comment]
I've been experimenting with Keybase alot, and that involved a lot of device add and removes.

I decided to reset my account, in the hope I wouldn't need to make up more random names for my laptop, but unfortunately the restrictions still apply after the reset.

This doesn't seem to be documented well enough :-1:

**Comment by jooize** [comment]
> reset my keys & start from scratch

That's what the button on the profile page says. Here's the prompt when pressing it:

> # Identity Reset
> ## Reset your keys?
> If you've lost all your private key(s), you can do this. You will have to prove ownership of your social identities again. If you're using the Keybase filesystem, you will lose data.
>
> Passphrase: …
> **[Reset account]**

The reset prompt needs to explain that the sigchain remains permanently and device names will not be reusable. That the button says “start from scratch” is obviously misleading, and everything in the prompt makes me think “entirely clean slate”.

All of that should be made understood earlier before setting device names, but at least improve the reset procedure so there's a chance people won't be misled to believe it's an _actual_ reset.

There's always that user friendliness balance. What should we call it instead? “decommission my keys and …” No doubt someone here can come up with better phrasing.

**Comment by omnidan** [comment]
I understand the security concerns with re-using device names, but this is a very bad UX - am I really supposed to append a new number to the device name every time I reinstall my device/keybase? Is there no way to migrate the device name if it's the exact same key and everything?

Even if there is really no way to do this in a secure manner, there should definitely be a warning when creating/deleting devices, because now that I deleted the old device, I can never name my device like the actual hostname again - which sucks.

**Comment by J08nY** [comment]
@maxtaco I'm currently facing this issue and I have a `.config/keybase/secretkeys.$USER.mpack` file but not a `.config/keybase/config.json` file. Is it possible to "recover" my device name? It's removal doesn't appear in my sigchain: https://keybase.io/j08ny/sigchain. If so, this should be documented somehow.

**Comment by maxtaco** [comment]
No, device names can't be reused after a reset. That's our policy.

**Comment by omnidan** [comment]
@maxtaco this really needs to be documented better then, e.g. a warning when setting the device name

**Comment by drdaeman** [comment]
Can you pleaseconsider adding automatic prefix or suffix to the device name? E.g. something in line of "My Laptop (2017-03-12)" when a device called "My Laptop" is added. Or actively suggest doing so manually from the device registration interface?

The current UI doesn't even hint about what would happen if the drive fails (inability to reuse the same name, etc etc) and given that device keys don't seem to be meant to be backed up, warning that device names cannot be reused should make sense.

**Comment by cjb** [comment]
We're adding a warning about the inability to reuse device names, it should be in the next release.

**Comment by elad** [comment]
@cjb thanks! In addition to the warning, I think a recommendation along the lines of @drdaeman's comment would go a long way to help. Also, unless there's a reason why slashes/spaces aren't allowed (path name constraints?), it might be helpful to relax this restriction.

E.g. "When naming your device, please keep in mind device names cannot be reused. We recommend adding the date to make it easier to identify later on. For example, MyDevice-2017-03-13."

**Comment by jbernardo95** [comment]
@cjb What about an account deletion ? If I delete my account and then create a new one ? Does this naming problem disappear ?

**Comment by cjb** [comment]
@jbernardo95 No, deleted accounts can't be reclaimed.

**Comment by maxtaco** [comment]
This policy prevents users from being tricked if keybase were to
maliciously reset or delete accounts (which we don't do but could
theoretically be coerced to do).

**Comment by jbernardo95** [comment]
What If I delete my current account and create a new one with a different username (but same email) is this allowed ?

**Comment by elgumso** [comment]
I have removed my mobile device to rename it and have ended up in the same situation. Need account reset please.

**Comment by virtualdxs** [comment]
I just thought of a possible replacement: Randomart. You can set openssh to show you the randomart of the host key of the host you're connecting to, and the idea is that you get used to seeing that image every time, and if the key changes, you notice. Could Keybase do a similar thing?

**Comment by slajax** [comment]
I accidentally deleted the keybase app and now when I try to sign in it won't let me recover the device name - super lame.

**Comment by h1nk** [comment]
-1, very unreasonable and frustrating system. Absolutely no warning of this...

**Comment by joelwreed** [comment]
I understand there are security complications here, but this is super annoying from a UX POV.

**Comment by junderw** [comment]
Anyone here use Keybase extensively? I do.

Have I ever read or care what device name my friends use? No.

If I saw "myPC1" or "myPCOopsIDeletedEverythingNewKeysSorryGuys" instead of "myPC" will I flip out at them for being unclean or whatever reason? No.

Is it annoying whenever any input field on any app turns red and tells you you can't input that thing? Yes.

IMO, Keybase should silently just add " (v2)" " (v3)" etc. after the input when it's already used. Nothing get's stopped, and no one is constantly looking at their device names and marveling at how amazingly accurate they are... and tbh, having a default string appended to mean "this is the second/third/etc time this user tried to use this name." would help people who actually look at and care about the device name.

Currently, a user trying to re-install on a device previously named "linuxbox" might hit the current error and rename it "PenguinContainer"... If I were looking at user device names every time I chat with them, having "linuxbox (v2)" would give me much more info... oh, so he re-keyed at this point, good to know.

**Comment by junderw** [comment]
Also... one problem with "device string as unique identifier for crypto keys" is something our phishing friends have figured out a while back.

"LinuxBox" and "LlnuxBox" at a glance are very similar.

I would personally like to see a gravitar-esque ID system turning the fingerprint into a colored pattern rather than relying on a user's naming sense.

**Comment by evandrix** [comment]
damn, this really sucks

**Comment by semeano** [comment]
Wow. This issue is 4+ years old...

**Comment by nomasprime** [comment]
Funny thing is if you setup a new computer from an old one, it has the same device name anyway so it's not as "set in stone" as some think.

Seems like _a lot_ of people have run into this issue, myself included some years ago. Best solution I think is to use a naming covention, eg, `<computer_name>-<year>`.

**Comment by seanfarley** [comment]
> Best solution I think is to use a naming covention, eg, `<computer_name>-<year>`.

Actually, it turned out the best solution was to not use keybase at all

**Comment by r1sk01** [comment]
8 years later, I dug up this from the depths of GitHub Issues.  
I'm disappointed at the response to this because it's still an issue nowadays.  
Every decent idea in this chain of replies has been completely ignored too.  
Disappointing.
