### ISSUE TITLE
Unable to use keybase without creating a "device"

### ISSUE THREAD

**Issue by lp0** [keybase/keybase-issues#1958]
People cannot track me because I have no devices:
```
$ keybase track simonarlott
▶ INFO Generating tracking statement for simonarlott
▶ ERROR user simonarlott has no active keys (error 916)
```

The latest client refuses to work unless I add it as a device, and I don't want to create additional signing/encryption keys as I already have PGP keys that I want to use.

Keybase needs to either accept that a user may have no devices and encrypt for the PGP key itself or allow the PGP signing/encryption subkeys to be registered as a "device" (although that will be awkward when those subkeys have their own expiry times).

**Comment by maxtaco** [comment]
this looks like a bug, we'll take a look. Thanks for your feedback.

**Comment by maxtaco** [comment]
Looking into this a bit, did you at any point try an account reset?  And/or what was your last successful action?

We're not considering changing our key model since we think it's better than the PGP secret key model that 99% of people can't figure out or implement properly.  However, your account is in an unexpected state, and people should still be able to identify and track you, even if you only have a PGP key.

**Comment by lp0** [comment]
My last successful actions were to track the person who's now trying to track me, and then to update my PGP key to change the expiration date on the keys.

If I reset my account is it going to force me to create devices?

**Comment by lp0** [comment]
I haven't reset my account but I also can't do anything at all now:
```
$ keybase track ...
error: you don't have a public key; try `keybase push` if you have a key; or `keybase gen` if you don't
```

```
$ keybase push
error: Tried to update a full-hash PGP key without a new full hash. (error #925)
```

**Comment by maxtaco** [comment]
We know.  As I said earlier your account is in a broken state and we are
trying to get to the bottom of it.  Sorry for the bug.

**Comment by maxtaco** [comment]
Ok, your account's been fixed!

**Comment by maxtaco** [comment]
The original bug was introduced on 11/2 when you updated your PGP public key.  We had a bug on our server between 10/28 and 11/2 in which a PGP key update will null our your "eldest key." The error was then picked up and inserted into the merkle tree on 12/30 when you did a track.  I've since fixed both issues and we closed the original bug in the evening on 11/2.

**Comment by lp0** [comment]
Other people can now track me, but I still can't do anything:
```
$ keybase track max
error: you don't have a public key; try `keybase push` if you have a key; or `keybase gen` if you don't
```

**Comment by maxtaco** [comment]
I'd try nuking your current install via `keybase nuke` and then logging back in.

**Comment by lp0** [comment]
That fixed it.
