### ISSUE TITLE
Unable to reset password

### ISSUE THREAD

**Issue by gkoberger** [keybase/keybase-issues#1962]
(For the record, I'm 99% sure my password is correct, but I can't log in... alas...)

When trying tor reset my password, I first tried the recommended way:

    $ keybase passphrase change
    $ keybase: error: argument "subcommand_name": Invalid choice: passphrase

So then I do it the less desirable way (since I don't want to have to redo everything), but get this:

![image](https://cloud.githubusercontent.com/assets/381393/12364571/3bdbe496-bb84-11e5-9902-541c26153590.png)

"Server failure: missing non-optional field pwh"

Any ideas?

**Comment by malgorithms** [comment]
@gkoberger  - sorry about this. seems like there are 2 separate issues here - I have no idea what "Invalid choice: passphrase" means there....someone else will have to look at that.

In the meantime, on the web, this is interesting. I hadn't seen that before and havn't been able to reproduce it. Can you walk me through the steps?

1. you request a password reset over email (from the web?)
2. you get an email with a reset link
3. the landing page asks you for a new password
4. and when you type in the new one, it gives you that error?

Is that a correct summary of what got you there?

**Comment by malgorithms** [comment]
(Aside: I just realized the first problem. you must be using an older version of keybase that doesn't have `keybase passphrase change`. ok. let's move on to solution 2....can you confirm the order of events I speculated on above?)

**Comment by gkoberger** [comment]
Nope, I'm on `keybase@0.8.25`, which is the latest release. I've deleted and reinstalled, and all that jazz. You can even see that `passphrase` isn't included in the list of subcommands:

https://github.com/keybase/node-client/blob/master/src/command/all.iced#L77

And looking through the code, the word `change` never appears:

https://github.com/keybase/node-client/search?utf8=%E2%9C%93&q=change&type=Code

Are you sure it actually works?

As for solution 2, yes, you are right. That's the exact steps. I requested a reset link twice, and got the same error both times. (One time I got a CSRF error, but I think that was because I submitted twice?)

Thanks!

**Comment by malgorithms** [comment]
We've started moving people over to the new and improved Go client, which has a lot of new features:

https://keybase.io/download

Repo: https://github.com/keybase/client

We've been telling most new users for a while to use that new one.  The go client is way faster / easier to install / has the new key support discussed in the blog here: 

https://keybase.io/blog/keybase-new-key-model

(So you should switch. But, regardless, we need to get your pw reset.)

Ok, for debugging this:

- can you try disabling any extensions you have? We shouldn't conflict with any ad blockers since all content is coming from us, but it's worth trying. And more important, if you're having LastPass or 1Password or something fill the form, try disabling that and doing it by hand. Sometimes they roll out new versions that do weird things that bring password submission forms. Our form is especially unusual since we don't send the password to the server and instead hash it locally.
 - any errors in the JS console in your browser?

**Comment by gkoberger** [comment]
Ah, I didn't realize that – the npm and github repos didn't mention a deprecation, and brew installing installed the Node version because I hadn't updated brew. Figured it all out!

Also, using a new browser fixed the password stuff. I was on Chrome Canary; maybe that broke stuff.

Thanks so much for your quick replies!

**Comment by malgorithms** [comment]
@gkoberger - regarding the browser failures, it was a bug in Chrome Canary. More info, if you care:

https://github.com/feross/buffer/issues/94

**Comment by gkoberger** [comment]
@malgorithms :+1: thanks!
