### ISSUE TITLE
Devices names are kept after account reset

### ISSUE THREAD

**Issue by jibi** [keybase/keybase-issues#1985]
After resetting my account I had to do again the login from the keybase CLI, but I was not able to reuse the old device name I was using before the account reset.

Step to reproduce:
* create a new account
* login with `keybase login` using the Keybase passphrase
* add a device (let's say "macbook")
* reset the account from the browser
* do again the login from keybase CLI
* add a device using the old device name

```
Enter a public name for this device: macbook
▶ ERROR Device name is already in use by this user (error 1408)
```

but on the `devices` tab on the browser I have

```
Active devices (0)
```

So i think this could be a bug.

**Comment by malgorithms** [comment]
not a bug, but we should update the wording. A device name * user is permanently locked, so an adversary (in cooperation with keybase) can't change the meaning of a device by swapping out a new key from another compromised device. In other words, "chris's device called foobar" is never allowed to change meaning, so you can think of it as a key.

**Comment by Tahvohck** [comment]
While I understand the thinking behind this, I feel like it should be reconsidered. A device name is a user-friendly way to identify a device and may need to be reused: a keybase/OS reinstall, replacing one machine with another that performs the same function, etc. They already have an immutable internal ID, why do they need a second immutable ID? Since you're worried about adversarial attacks, then any time a device name is displayed also indicate which "revision" of this device has been displayed, so `device` is the friendly name, `device~3` indicates that it's the third time the name has been used, and `1234567890abcdef1234567890abcdef` is the immutable ID for referencing it.

Obviously don't allow the same name to be active on two devices at the same time, but once a name has been decommissioned let us re-use it.

**Comment by weavejester** [comment]
I also think this needs to be reconsidered. If I upgrade my OS or reinstall keybase because it's broken, keybase sees my machine as an entirely new device. This is unexpected, and took me a while to work out that a keybase "device" is not what we usually think of as a device.

**Comment by cjb** [comment]
> If I upgrade my OS or reinstall keybase because it's broken, keybase sees my machine as an entirely new device.

This should only be true if you blow away the Keybase config directory in your home dir, which should be managed separately from your OS and Keybase software install.

Anyway, we're reconsidering this limitation, but getting to the point where we can allow device name reuse will involve building a bunch of UI for explaining device versions that we haven't built yet.
