### ISSUE TITLE
Website verification failed

### ISSUE THREAD

**Issue by DrKat123** [keybase/keybase-issues#2115]
I have added the keybase.txt file to my website's (http://drkat.gwiddle.co.uk) public_html directory.
Should i add the file to the root directory instead?

**Comment by DrKat123** [comment]
Hello...?

**Comment by dtiersch** [comment]
You should add the file in the appropriate directory, so that it is accessible with the address http://drkat.gwiddle.co.uk/keybase.txt. What directory that is depends on the config of the webserver, but public_html usually sound like a good idea.
In your case though it didn't seem to do the trick... You have to look where the other files are that are accessible from the web, that's probably the web root you're looking for.

**Comment by NoSubstitute** [comment]
The url mentioned by @dtiersch resolves fine. Perhaps you should ask Keybase to verify it again.

**Comment by dtiersch** [comment]
Sorry, I had a typo in the address when trying to `curl` it. Using the correct address works just fine.
Someone having access to the crawlers log should have a look into this...

**Comment by DrKat123** [comment]
@dtiersch i'm gonna try to put the keybase.txt to the root directory

**Comment by DrKat123** [comment]
Let me try to verify the keybase.txt again...

**Comment by DrKat123** [comment]
Never mind it's working now.

**Comment by oconnor663** [comment]
Thanks for the help, @dtiersch.
