### ISSUE TITLE
Problem with twitter validation (proofing)

### ISSUE THREAD

**Issue by donzooles** [keybase/keybase-issues#2153]
Hi, I have a problem with the validation of my twitter account, I tried it multiple times (https://keybase.io/donzooles/sigchain) but it wont work. 

My latest validation tweet: https://twitter.com/donzooles/status/712594264904101888

**Comment by oconnor663** [comment]
Here's what I get if I copy-paste that tweet:

```
Verifying myself: I am donzooles on Keybase.io. qm-3d0Q3uvaEehu2G-9HVM6ZHozXyKwy
Pge- / https://keybase.io/donzooles/sigs/qm-3d0Q3uvaEehu2G-9HVM6ZHozXyKwyPge- …
```

I don't think that line break in the middle is supposed to be there. Maybe that got introduced when you copied the text from your terminal? What happens if you retweet the proof without the newline?

**Comment by donzooles** [comment]
@oconnor663 Now it's working, thank you. :)

**Comment by oconnor663** [comment]
Woo :)

**Comment by oconnor663** [comment]
Let me know if you figure out how the newline got there. It sounds like it must've happened more than once.

**Comment by donzooles** [comment]
You're right, it came from the terminal.

I use Keybase on Windows 8.1.

**Comment by oconnor663** [comment]
Oh the whole block select thing that cmd.exe does? Yeah that makes sense.

@zanderz, do you think everyone on Windows is going to run into this problem? As a hacky workaround, maybe we could have the client print newlines instead of spaces, so that none of our words break on the right edge of the terminal. Hmm, or maybe have some Windows-specific code in there that automatically adds the right string to your clipboard, so that you don't have to copy it?

**Comment by dtiersch** [comment]
or ignoring line breaks in the signature since they are not valid characters in the first place?

**Comment by zanderz** [comment]
Windows 10 has a new terminal with improved select/copy, so this will eventually go away.
