### ISSUE TITLE
GPG keys generated by Keybase cannot be used for GitHub's new GPG commit verification

### ISSUE THREAD

**Issue by davidcelis** [keybase/keybase-issues#2181]
GitHub just recently [announced support for GPG Signature verification on commits](https://github.com/blog/2144-gpg-signature-verification). Part of this process involves uploading a GPG key to GitHub. However, there is an unfortunate issue between Keybase and GitHub's new GPG support: it's impossible to use a GPG key generated by Keybase as commit verification proof on GitHub. The reason for this is that Keybase uses a <username>@keybase.io email address with keys it generates, and these email addresses are not verifiable. I think Keybase used to offer an email relay service and forward emails sent to <username>@keybase.io to whatever email address the user registered with, but it looks like that was shut down some time ago.

**Comment by strib** [comment]
You can easily add your commit-by email address to your pgp key, using gpg, if you want. Github will list all of your addresses, and put the verified ones first.

![screenshot from 2016-04-05 12 22 49](https://cloud.githubusercontent.com/assets/8516691/14298784/99681a66-fb3b-11e5-8c73-5eee88b5c85f.png)

As per @jokeyrhyme here: https://github.com/keybase/keybase-issues/issues/245#issuecomment-205971314:
> For reference, I followed this guide: https://www.katescomment.com/how-to-add-additional-email-addresses-to-your-gpg-identity/
> Then I ran keybase push --update.
> Then I copied the new public key over to GitHub. Everything is fine now. :D

**Comment by zQueal** [comment]
I'm not exactly keen on how I verified all but my first address, but it seems to be working fine in my case.

![2ydnnhn](https://cloud.githubusercontent.com/assets/239193/14303975/04c40130-fb7d-11e5-898f-eb9c28407a3f.png)

I've emailed Github to ask more about the verification process, as when I added my key I never received a verification email at the listed unverified email and one has never been associated with my Github account. Not sure why it's verified.

**Comment by strib** [comment]
I don't think you get verified via an email -- you get verified by pushing a commit to github with that email address in the commit.

**Comment by zQueal** [comment]
As it turns out, it's all a manual process. By entering your Github settings and adding the desired emails from your key, then verifying them, they become "Verified" on your key.

![asjmguf](https://cloud.githubusercontent.com/assets/239193/14304068/c8535c90-fb7d-11e5-8857-0f6c89a090a5.png)

It in action:

![wgfh0x9](https://cloud.githubusercontent.com/assets/239193/14304078/e4827e28-fb7d-11e5-841f-d7c361b9714a.png)

**Comment by nikolay** [comment]
@zQueal How did you get your username@keybase.io email verified? It doesn't forward for me.

**Comment by davidcelis** [comment]
I added an email address that _is_ verifies to my Keybase key, pushed the update to Keybase, and added it to GitHub. If I sign a commit using that email address, it works.

Looks like verifying the actual @keybase.io email isn't necessary.

**Comment by nikolay** [comment]
@davidcelis Well, I did that, too, but I still wonder how to verify nikolay@keybase.io!

**Comment by zQueal** [comment]
@nikolay Mine seems to forward fine. Since I was able to get the email from `@keybase.io` proxied to my personal email, it verified with Github and then when I added my key, it was already "verified".

**Comment by davidcelis** [comment]
@nikolay If you joined too late to have the email relay service on for you, you can't verify that address. But you don't really need to anyway

**Comment by cjb** [comment]
And you could even remove the keybase.io user ID from the key and reupload

**Comment by davidcelis** [comment]
@cjb I don't think that's true. I tried removing the @keybase.io email address from my key and running `keybase push --update`; I got an error about it not being a valid Keybase key.

**Comment by maxtaco** [comment]
@oconnor663 can you fill in some details on this?  this is a security precaution...

**Comment by oconnor663** [comment]
We do still prohibit this in the API server. I'm actually having a hard time remembering all the reasons, and I strongly suspect that those reasons are obsolete now. We could rip this check out...

The underlying issue is that there are two ways to prove that a key is actually yours: either by signing a sigchain link with it, or by having you@keybase.io as one of the PGP key IDs. That second way makes removing PGP key IDs a little sensitive, because you could go from a state where your key was provably yours to a state where it isn't provably yours anymore.

In practice, a lot of changes have made that state less relevant:
- Anyone who signs up with the Go client now makes a bunch of signatures by default.
- Updating your PGP key now *also* makes a signature most of the time.
- Many new users never bother to generate PGP keys at all anymore.

I think what I'd want to do is track down all the places we reference our `self_signed` database column in the server code, and make sure I haven't overlooked anything. I'll file a task for myself.

**Comment by soundofjw** [comment]
Was this resolved? As a keybase enthusiast, I'd love to see a workaround for this issue.

What if emails to user@keybase.io ended up in their private keybase FS folder?

*shrug*

**Comment by cjb** [comment]
@soundofjw What are you trying to do? If you want a workaround for using GitHub, just add another email that you commit with to your GPG key.

**Comment by soundofjw** [comment]
@cjb apologies I figured it out - this is a good guide: https://www.ahmadnassri.com/blog/github-gpg-keybase-pgp/

**Comment by zQueal** [comment]
> What if emails to user@keybase.io ended up in their private keybase FS folder?

This would be pretty amazing, IMO. Maybe it warrants a new thread as a feature request?

**Comment by strib** [comment]
@soundofjw @zQueal: due to the truly end-to-end encryption of KBFS, no servers under our control can write anything to your private directory!  So this would either have to be some email server program run under your own control, or the emails would have to be written to a shared (private) folder between you and the keybase organization.

**Comment by soundofjw** [comment]
@strib The latter of those two would be amazing! 🎆

**Comment by zQueal** [comment]
> or the emails would have to be written to a shared (private) folder between you and the keybase organization.

This could be a happy medium, I think. Having the ability to receive email at this address and not necessarily send email would allow verification of identity, like verifying your PGP identities on Github pretty easy, IMO.

**Comment by soundofjw** [comment]
Made a feature request @ #2235.

Cheers!
