### ISSUE TITLE
recover account, no e-mail

### ISSUE THREAD

**Issue by marcb1** [keybase/keybase-issues#2190]
Hi I am trying to recover my account (i forgot my password). I have completed the 'forgot password' form and am presented with the following message:
Great, we've sent you an email with password reset instructions. (Give it a couple minutes to arrive.) Once you've clicked the link in that email, you can login.

However, I have not received an e-mail from keybase and it has been a couple of days now.
My keybase username is: https://keybase.io/marcb1 and I have not revoked my key. 
Also, I have not setup the keybase command line tool to be able to recover my password there.
Any help?

**Comment by zQueal** [comment]
Have you at any time unsubscribed (via the web interface, not through your mail provider) from Keybase emails?

**Comment by marcb1** [comment]
It's been quite a while since I have used keybase, so I don't remember. I might have unsubscripted from e-mails.

**Comment by marcb1** [comment]
is there anything that can be done to fix this?

**Comment by zQueal** [comment]
Although I don't speak for Keybase, I highly doubt it. If you unsubscribed from emails, Keybase won't send you any emails. That's what that feature is designed to do. Because of the sensitivity and trust involved with private keys, I highly doubt Keybase devs would reset your password for you without you expressly using the built in tools. Or at least, I hope they won't. If they do, that's a social engineering attack vector.

The most you could do is maybe email @maxtaco or @malgorithms and see if they will check to see what's going on.

**Comment by maxtaco** [comment]
@marcb1  you typo'ed your email address and gave us `gmail.com`

**Comment by maxtaco** [comment]
OK I manually fixed your email address and then resent your passphrase reset email.

**Comment by blattler** [comment]
I'm having the same issue - username dblattler. is there some way of checking if there's a typo in my e-mail address? @maxtaco
