### ISSUE TITLE
wrong rendered graph

### ISSUE THREAD

**Issue by dtiersch** [keybase/keybase-issues#2224]
The [graph](https://keybase.io/dtiersch/graph) for my [sigchain](https://keybase.io/dtiersch/sigchain) is not shown correctly. Instead of my first device with which I proved everything the graph shows an unnamed PGP key (which doesn't exists from keybases POV, because it was never provided). This error is in both views of the graph.
Until Chainlink `11` including, I remember the graph being rendered correctly, so either the second device or my latest reddit proof must have broke it.

**Comment by maxtaco** [comment]
Thanks @dtiersch.  We're aware of a bunch of bugs with the sigchain and graph view.  We hope to fix them soon.   The raw [chain](https://keybase.io/dtiersch/chain) is correct (but much less user-friendly).

**Comment by hybby** [comment]
Also suffering from the `unnamed` key in my graph.  I had a suspicion that this unknown key might have been generated server-side by Keybase when I joined the site, using the passphrase I joined the site with.  Then, creating per-device keypairs would link back to that "master" key.

The reason I thought this is that I signed up and created a passphrase, as was requested of me.  After that, I used my account settings to change my passphrase (the actual option was "new passphrase", so unsure whether any "changing" went on).  However, following that when I used the "sign" page, my new passphrase was declared invalid.  Only the old, original passphrase would perform a sign operation successfully.

Something doesn't seem quite right about the whole thing, so I guess I'll watch this issue to see how things go.  Hope you don't mind.

**Comment by malgorithms** [comment]
@hybby - that "unnamed" key in your graph is the device called `emmy` . (You can tell because emmy is the one that added all those other keys/proofs. You can also view source on the graph page and the key's id, and see that it matches the signature chain)  Both the graph view and the sigchain view have some display issues right now if you've done a sigchain reset, and those pages need some real TLC. Soon, I hope.

( I'll likely need @maxtaco 's help because it's not a quick fix. We have performance considerations doing this for all users, so we don't just process the signature chain on each load.)

**Comment by dtiersch** [comment]
> Both the graph view and the sigchain view have some display issues right now if you've done a sigchain reset

I started over with a new account instead of a reset. So there got to be another issue causing it as well.

**Comment by malgorithms** [comment]
I think this is fixed for both of you - can you can confirm (and the 2nd person close this issue if so?)?

**Comment by hybby** [comment]
Fixed for me.  Thanks @malgorithms - much clearer now.

**Comment by dtiersch** [comment]
Fixed for me as well, thanks :)
