### ISSUE TITLE
Removed files appear in keybase.pub and new are missing

### ISSUE THREAD

**Issue by atfornes** [keybase/keybase-issues#2239]
After erasing from terminal two files `fo` and `fo~` from my public folder, they kept visible at https://keybase.pub/atenorio/

```$ rm fo; rm fo~```

![captura de pantalla de 2016-05-08 19 42 29](https://cloud.githubusercontent.com/assets/7475584/15100341/33cce62a-156f-11e6-9a49-0a002ebb3925.png)

Trying to reproduce the issue to report it here I created a new file bar.txt by the following command:

```echo 'bar' > bar.txt```

that file is not shown at keybase.pub although it is at my public folder and the "signing and uploading" message was shown:

![captura de pantalla de 2016-05-08 22 51 04](https://cloud.githubusercontent.com/assets/7475584/15100348/60b92e3c-156f-11e6-90e1-d3d86aaeb529.png)

I have waited several hours to report this issue since it looked like a sync problem, but it is still not working.

**Comment by malgorithms** [comment]
@strib  - pulling you in.  This appears to be a KBFS client issue, not a keybase.pub issue. @atfornes attempted to delete 2 files from KBFS on their end, but it hasn't synced for some reason. here's my view of the folder.

```
08:24:11 chris warhol ~ >ls -lsah /keybase/public/atenorio
total 104
80 -rw-r--r--  1 root  wheel    40K Apr 18 10:19 Captura de pantalla de 2016-04-18 15:18:50.png
 8 -rw-r--r--  1 root  wheel    14B May  8 13:13 fo
 8 -rw-r--r--  1 root  wheel     7B May  8 13:11 fo~
 8 -rw-r--r--  1 root  wheel    11B Apr 18 10:18 holaMundo.txt
```

@atfornes - strib will probably ask you to post your logs to us by running `keybase log send`. It'll generate a hex code you can paste here.

**Comment by atfornes** [comment]
Here is the hex code: `14ff56c85a052596e018711c`

**Comment by strib** [comment]
Hi @atfornes, thanks for the report!  I found the issue.  The quick fix is for you to restart KBFS on your device, `ls /keybase/public/atenorio`, and wait a minute for it to fix itself.  Here are the gory details:

The device you're using to write to the folder got itself stuck in a "conflict" state -- that is, your device sees a different version of the folder than everyone else.  This usually only happens very transiently, and should only happen when multiple devices are writing to the same folder.  In your case, there is only one device writing to the folder.  This looks like the work of emacs -- emacs likes to cancel "idempotent" file system operations and try them immediately again.  This is supposed to be safe, and with KBFS it is usually safe, but your usage has uncovered a bug when it appears that we do not treat file truncation to 0 bytes as an idempotent operation.  I will file an internal issue for that.  So, it sees two conflicting operations (the canceled truncate, and the next truncate), and it gets into a conflict state.

That's not enough to explain the behavior though, since KBFS is designed to automatically get itself out of the conflict state.  It turns out there was a previous conflict state right before this one that your device DID resolve correctly.  Then, when it hit the NEXT conflict state, you hit a bug in our logic that got confused with some cached data leftover from the previous conflict state, and it gave up trying to do conflict resolution.

Since the messed-up cached data is soft state in memory, a restart will clear the state out and conflict resolution should be able to succeed correctly.  I will file internal issues for the two above bugs, but in the meantime you might want to avoid using emacs directly on KBFS files.  I'll update this issue once we have a client out that fixes both bugs.

Sorry for the inconvenience, and please let me know if a restart does indeed fix it.

**Comment by atfornes** [comment]
thanks @strib!

After a computer restart, the folder sync is back to normal. I guess that is equivalent to the keybase restart you proposed.

I am glad that the bug report helped to detect an issue in KBFS.

**Comment by strib** [comment]
Both of these issues are fixed, and will be in builds later this week.  Thanks again!
