### ISSUE TITLE
Website documentation is broken

### ISSUE THREAD

**Issue by kchristidis** [keybase/keybase-issues#2250]
"Getting started from the command line" section in profile page suggests running `keybase pgp select` or `keybase pgp gen`, but `pgp` is an invalid `subcommand_name`.

"Device adding + removing" section in the [documentation page](https://keybase.io/docs/command_line) lists `keybase device *` commands but —again— `device` is an invalid subcommand_name`.

Running v0.8.23 of the CLI (what `brew install keybase` gave me yesterday).

**Comment by dtiersch** [comment]
something strange happened there. You got the outdated node.js client instead of the current and documented one (at least v.1.0.15). The [homebrew recipe](https://github.com/Homebrew/homebrew-core/blob/master/Formula/keybase.rb) is correct maybe a local homebrew configuration issue?
Did you have keybase installed before
Did you tap an outdated recipe repository which could point to the old client?

**Comment by kchristidis** [comment]
Ah, odd indeed. At any rate a `brew update` took care of it. Thanks!
