### ISSUE TITLE
Error uploading to KBFS

### ISSUE THREAD

**Issue by meristem** [keybase/keybase-issues#2292]
When uploading to /azs, OS X returns this error:
The Finder can’t complete the operation because some data in “W4Svidazs” can’t be read or written.
(Error code -36)

(log file sent)

The only peculiarity of the file is that it is ASCII armored to my key.

**Comment by strib** [comment]
(Log ID: 39944448d7fb5daa62d1351c)

Hi @meristem, looks like our known big-file upload timeout issue (where big is defined as a file > 5 MB).  We're actively working on making this experience better right now.  Thanks for the report~

**Comment by meristem** [comment]
Yay!  Thanks @strib... For documentation/tracking's sake, can you give the issue # for the known upload timeout, please? I was not able to locate it.

**Comment by strib** [comment]
Sure, sorry for being lazy before.  Here's the earliest example I know of: https://github.com/keybase/client/issues/1981#issuecomment-183169104

Your error message is different because you used the Finder/GUI to copy the files, rather than the command line. But under the covers they look the same to me.

**Comment by strib** [comment]
The latest versions of KBFS for Linux and OS X (`1.0.16-20160627110020+11e6f10` and higher) include both performance improvements, and timeout avoidance, so it should be possible now to upload large amounts of data on all but the worst network connections without seeing an error.  Performance will still be pretty slow, since it involves synchronous round trips to our servers, but it should be a bit faster than before, and more importantly error-free.

Please try it out when you get a chance and let me know if things seem better.  Thanks!

**Comment by strib** [comment]
Version 1.0.20 has architectural changes that should greatly improve the large write experience.  If you're still seeing problems, please open a new issue.
