### ISSUE TITLE
Unable to prove something

### ISSUE THREAD

**Issue by tommyd3mdi** [keybase/keybase-issues#2321]
So, I'm trying to prove my github account / website, but stumble upon this:

    $ keybase prove github tommyd3mdi                                                                                                                                                                   
    WARNING Bad subkey: openpgp: invalid data: Subkey wasn't signed; expected a 'binding' signature
    ERROR Error in reverse signature: Failed to verify/extract sig: Message wasn't signed

what am I doing wrong?

**Comment by dtiersch** [comment]
Could you check that the subkeys of your key are self-signed? When you run this command you should see directly under every uid and subkey a signature by yourself.
```sh
gpg --list-sigs YOUR_GPG_ID | grep -EA1 '^(sub|uid)'
```

**Comment by tommyd3mdi** [comment]
Yes, they're all self-signed:

    $ gpg --list-sigs 160D1092 | grep -EA1 '^(sub|uid)'                                                                                                                                          uid                  Thomas Keller <me@thomaskeller.biz>
    sig          160D1092 2007-11-09  Thomas Keller <me@thomaskeller.biz>
    --
    uid                  Thomas Keller <tommyd@macports.org>
    sig 3        160D1092 2008-10-14  Thomas Keller <me@thomaskeller.biz>
    --
    sub   4096g/3976D30C 2003-03-13
    sig          160D1092 2003-03-13  Thomas Keller <me@thomaskeller.biz>

**Comment by dtiersch** [comment]
Best should be, you do a `keybase log send` and post the log id here. Then the Keybase staff can better see what's going (wr)on(g) there.

**Comment by tommyd3mdi** [comment]
Ok, my log id is 4532ef2741790e5e22c2f31c

**Comment by maxtaco** [comment]
Thanks @dtiersch for your efforts.

Uggg yet another crazy corner case with PGP keys.  There just aren't enough hours in the day to handle them all.

I'll put it into our backlog, but no guarantees as to when we can get to it, since it's a corner case that no one else is currently affected by (or it could be a bug in your key).

You might try to disassociate that PGP key with your account:

```
keybase pgp drop 0111a570665969286c8304e783ab785cc2dead911abe09ac50bd7d200e8724a4d4740a
```

You can always add it back later, after we've fixed the bug.  Likely it's a bug in Go's OpenPGP libraries.

**Comment by maxtaco** [comment]
Taking a little deeper look at it, it's likely because you signed your ElGamal subkey with your DSA primary key using a version 3 signature (back in 2003!). Go's library have very limited support for version 3 signatures, which isn't a bad thing, since version 3 signatures have a fair amount of security shortcomings.

**Comment by maxtaco** [comment]
I think I'm wrong about what I said above.

@tommyd3mdi, what happens when you:

```
keybase id deadfish
```
?

**Comment by maxtaco** [comment]
At risk of sounding like a dolt: I think we've already fixed this problem in master.  Try installing a new version of Keybase from our [downloads page](https://keybase.io/download)

**Comment by maxtaco** [comment]
Feel free to reopen if that doesn't work.

**Comment by tommyd3mdi** [comment]
With 1.0.16 (installed via homebrew) `keybase id deadfish` errors out with:

    ▶ WARNING Bad subkey: openpgp: invalid data: Subkey wasn't signed; expected a 'binding' signature
    ▶ ERROR Error in reverse signature: Failed to verify/extract sig: Message wasn't signed

I'm currently on the train, will try to get a newer version at home. Thanks for your efforts!

**Comment by maxtaco** [comment]
Ok the home brew version is behind. Should be fixed. Thanks !

**Comment by tommyd3mdi** [comment]
I can confirm that it works with the client package provided on the website, though this also identifies with 1.0.16, only using a different suffix. Thanks again for your support!
