### ISSUE TITLE
Unable to add https://codecontext.io

### ISSUE THREAD

**Issue by adriamb** [keybase/keybase-issues#2326]
I cannot proof my website https://codecontext.io.
The https certificate it's from https://letsencrypt.org/ , could it be the problem?

**Comment by BytewaveMLP** [comment]
I use a Let's Encrypt certificate on [my site](https://bw81.xyz) as well, and have been able to successfully claim it. I would doubt it's an issue with TLS unless you have something **really** finnicky set up that Keybase doesn't like.

When you say you "can't" prove your site, could you explain a bit more what you mean? Are you proving by HTTP(S) or DNS?

#### If HTTP:
- Make sure `keybase.txt` is either in the root (`/`) of your website, or in (`/.well-known`), that the permissions for it are set such that the webserver can access it, and that your webserver will serve it without error (try accessing it in your browser, that's your best bet).

#### If DNS:
- DNS propagation can take upwards of hours, maybe even a day if you're really unlucky. I haven't had too many issues with that, but your mileage may vary.

**Comment by dtiersch** [comment]
There seems to be a problem with the certificates. When I try to `curl` your website, I get the error message:
```
$ curl https://codecontext.io/
curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```
This is not true for the Website of @BytewaveMLP, so there have to be some differences.
Also I couldn't find the proof either in `/` or in `/.well-known/`.

**Comment by adriamb** [comment]
Oops!

Let's me check better my TLS configuration. It seems that is something
misconfigurated there.

Adrià

**Comment by dtiersch** [comment]
I don't think, Chrome is too lax - at least not related to this case. Chrome just has a more up to date bundle of CAs with Let's Encrypt already included. But it is still missing in a lot of official packages. To work with those the complete chain has to be provided. (and since Keybase uses such a package, a complete chain is needed for Keybase as well)

I ran both sites through the "SSL Server Test" [[codecontext.io](https://www.ssllabs.com/ssltest/analyze.html?d=codecontext.io)], [[bw81.xyz](https://www.ssllabs.com/ssltest/analyze.html?d=bw81.xyz)] and the difference is indeed that the latter one provides Let's Encrypts Certificate as part of the chain while yours doesn't.

**Comment by adriamb** [comment]
Oh, yes, it was just the certificate chain. 
F*king obvious :(

Thanks for your time!
