### ISSUE TITLE
Account recovery

### ISSUE THREAD

**Issue by sjug** [keybase/keybase-issues#2332]
Related to https://github.com/keybase/keybase-issues/issues/2189

I have emailed a few of the devs here including @malgorithms and @maxtaco to try and recover my account with no avail.

When I try to recover using the website I get the error:

> You can't reset your passphrase, since you have active device or paper keys. The following devices all have the power to change your passphrase.

I don't have access to these devices listed any longer so they are not logged in in order to recover.

Please help.

**Comment by sjug** [comment]
Can someone please let me know how I can recover my account...

**Comment by zQueal** [comment]
> Why is this so difficult?

Why didn't you do as the installer specifically pointed out that you needed to do (for this exact situation) and generate and save a paper key?

**Comment by sjug** [comment]
Yeah absolutely I should have. I put it in my password store which was encrypted with my private key which I no longer control. I've learned that one the hard way...

**Comment by sjug** [comment]
I literally lost all my passwords for everything because I lost the private key... and keybase is the **only** account I haven't been able to recover. My bank account I can get back, no problem. My various email providers I can get back, no problem. My other financial accounts I can get back, no problem.

Keybase I can email the half organization directly, start a github issue, and not have not even received any _suggestions_ as to how I can recover my account. Instead @zQueal points out the obvious a month later? Can someone **please** just do something to move this along? @maxtaco @chrisnojima  @gabriel @chromakode @mmaxim @mlsteele @jzila @patrickxb @jinyangli @oconnor663 @cjb @songgao @aalness @malgorithms @akalin-keybase @MarcoPolo @zanderz @strib

**Comment by maxtaco** [comment]
@sjug I keep trying to reach out to you, but you never reply to my emails.  You need to verify you have control of the email address we have on file for you.

**Comment by sjug** [comment]
Thank you @maxtaco I will reply to you there.

**Comment by zQueal** [comment]
> Instead @zQueal points out the obvious a month later? 

It's a little childish to lash out at me let alone Keybase like that. I don't work for Keybase and can't help you at all. My question was purely academic because I was genuinely curious why you were blaming Keybase for _you_ not creating a paper key which is the reason why you were unable to recover your account. Wasn't done maliciously (or accusatory), but maybe the incredibly succinct warning that Keybase has during the setup of an account isn't good enough for the most incredulous of users? 

> My bank account I can get back, no problem.

One would think this is more of a security issue rather than to their credit...

Either way looks like Max has your back.

**Comment by fiatjaf** [comment]
I'm curious about what has happened here. I'm afraid the same situation will happen with most of my not-very-techy friends to whom I've presented Keybase.

The question has just arisen because I didn't expect my keys to vanish from my phone after I uninstalled the Keybase app and later reinstalled it (which left me out of one device I thought I had).
