### ISSUE TITLE
Query on .army website does not work

### ISSUE THREAD

**Issue by secits** [keybase/keybase-issues#2352]
When trying to prove my website, I have the following error:

<img width="604" alt="screen shot 2016-07-08 at 10 51 05" src="https://cloud.githubusercontent.com/assets/1451321/16682309/34807c02-44fa-11e6-9398-b00ab0d7ba0f.png">
"could not query \<b\>pacmans.army\</b\>. Are you running a site there?"

_(Note the tab \<b\> being html-encoded)_

**Comment by dtiersch** [comment]
There is an error in your SSL Configuration. Your webserver is not serving the intermediate certificates, meaning the certificate chain is broken/incomplete (see [here](https://www.ssllabs.com/ssltest/analyze.html?d=pacmans.army&s=2001%3a41d0%3a52%3ad00%3a0%3a0%3a0%3a850&latest) the analysis from SSL Labs).

That being said I'm a bit unsure if that alone is gonna solve your problem, because the error appeared way earlier than when trying to find the proof. Does this error appear on the command line tool as well?

**Comment by secits** [comment]
Hi @dtiersch, thanks for the heads up, I will add the intermediate certificate but for now, when using the command line, I have the following error:

`laptop:~ user$ keybase prove web
Web site to check: https://pacmans.army
> ERROR Failed to find a connection to pacmans.army (error 229)`

**Comment by secits** [comment]
Hi @dtiersch, I uploaded the intermediate certificate, and it all works fine now!
Thanks a lot for you support.
I now have a A+ ssl rating and a proved website :)
