### ISSUE TITLE
[Windows] I've crashed Explorer about five times now

### ISSUE THREAD

**Issue by pie-flavor** [keybase/keybase-issues#2369]
When I open a Keybase folder I haven't opened before, it takes a very long time to load. Several times, Windows Explorer crashes and must be restarted from task manager. The most recent time, it created a duplicate process, and then refused to load until I killed it from command line, and then ran it from command line.

**Comment by pie-flavor** [comment]
The exact same thing just happened again. After multiple Windows Explorer crashes, it happened again where a duplicate process appeared under the System section, and had to be killed and manually reopened.

**Comment by zanderz** [comment]
Next time you notice a Keybase folder operation taking a long time, can you please issue the command `keybase log send` at the command prompt (now called Keybase Shell) and copy the resulting log ID here? Thanks.

**Comment by zanderz** [comment]
I forgot to ask: do you have any antivirus or other filesystem scanning software installed? We are getting reports of problems with BitDefender, Symantec, etc.

**Comment by zQueal** [comment]
@zanderz Just experienced this. Windows explorer crashed __hard__. The window became inactive and I could not under any circumstances get it to respond--even after attempting to force terminate the process several times. I had to physically hard reset my system (by depressing power button) to restart because the window was still active and ultimately stopped Windows from gracefully restarting and for whatever reason Windows couldn't force close it via the shutdown process.

My only guess is that even though whatever KBFS was doing failed and continued to fail, it kept attempting to try which disallowed the process to terminate. I won't say I confirmed this, but after attempting again and explorer crashing __hard__, I attempted to force terminate all running Keybase files. I was able to get all to close except for `kbfsdokan.exe` which wouldn't terminate no matter what I did.

    λ tasklist | grep kbfs
    kbfsdokan.exe                12404 Console                    1     17,788 K
    λ taskkill /PID 12404 /F
    SUCCESS: The process with PID 12404 has been terminated.

I tried to directly taskkill the process which reported that it was successfully terminated [but it was still running when I checked](https://u.nya.is/dnwlwu.png).

It forced me to restart my system again.

Log: `a016e836af114698ca44b91c`

**Comment by cjb** [comment]
Thanks, CC @taruti

**Comment by changedsoul** [comment]
I will add this also happens to me all the time. Its rare when I can get a folder to respond without crashing my system. I have begun not even using them and wish they were not auto mounted. Sadly I am new to keybase and am working out how to send logs, so no logging has been submitted under the constant crashing. On a positive note, it crashes very reliably :)

**Comment by taruti** [comment]
This seems to be due to numerous filesystem drivers conflicting on your machine.

Two solutions:
1) Find out which one causes an issue with Dokan for you by disabling some of them at a time, and update the issue so we can get debugging and solving it.
2) Don't mount KBFS by setting the mount-point to none (@zanderz is there user documentation for this?)

**Comment by changedsoul** [comment]
These instructions are quite vague. I have no idea how to mount or not mount these folders. It seems the desktop App does it behind the scenes. As for the disabling drivers too, I wouldn't even know where to start. I am going to need a little bit of help working thru this. I am pretty computer literate, but some stuff I just dont know.

**Comment by zanderz** [comment]
We don't yet officially support running Keybase separate from the filesystem, but you can just go to your control panel and uninstall the Dokan Library and that should do it. Note you can still use kbfs via client command line options (`keybase fs`) without Dokan drivers. We would be very interested to know whether that clears up your crashes.

**Comment by changedsoul** [comment]
Ok well I removed Dokan and I am not crashing, but I also dont have mapped folders anymore.
I tried keybase fs, but the help is hard for me to understand.
I tried keybase kbfsmount getall to find a list of avail letters to mount to (???)
Then did: keybase kbfsmount set Y: ( to mount fs to Y (?????)
Then did : keybase fs ls -a Y: to get a listing of whats in there, but I get an error.

Clearly I have no idea what I am doing. I was really just guessing based on what I saw.
Can I have some instructions how to gain access to the folders from command line?

**Comment by zanderz** [comment]
Sorry for the misunderstanding, but there can be no mapped folders without the Dokan driver. I assumed that would be better than crashing. The `keybase fs` commands are all command line only, such as:
`keybase fs ls /keybase/changedsoul/private` - get a listing of changedsoul's private directory
`keybase fs cp /keybase/changedsoul/private/somedir/somefile c:\destdir` - copy a private file out of kbfs to the local destdir
etc.

**Comment by changedsoul** [comment]
I try this command: "keybase fs ls /keybase/changedsoul/private" on the command line and I get 
- ERROR Invalid remote path

**Comment by zQueal** [comment]
Try;

> keybase fs ls /keybase/private/changedsoul

**Comment by changedsoul** [comment]
That seems to execute fine,

**Comment by zanderz** [comment]
Whoops, sorry for the typo
