### ISSUE TITLE
Devices don't get deleted after resetting an account!

### ISSUE THREAD

**Issue by Benzi** [keybase/keybase-issues#2373]
I had a device named "ara" prior to a reset and I couldn't add the same device with the same name after the account reset.

`keybase device list` doesn't list the old device names after the reset (as expected) but it's still assigned to my account 😕

**Comment by maxtaco** [comment]
Not a bug, this is by design.

**Comment by Benzi** [comment]
Ah, so is there no way for me to reassign a previously used device name after an account reset?

**Comment by dtiersch** [comment]
Correct, the combination of username and device name is unique. Once a name has been used in an account it can never be reused in that account again. The old device still exists in the backlog, it is just revoked and no longer directly linked to your account due to the reset. Making the same name reusable would make it ambiguous and not a safe identifier

**Comment by Benzi** [comment]
I see, thanks for clarifying!
