### ISSUE TITLE
Prove my twitter identity fails

### ISSUE THREAD

**Issue by mattr777** [keybase/keybase-issues#2400]
I used the "prove my twitter identity link", selected the "in the browser" radio button, 
used the "twitter popup" link to ensure that the correct text was tweeted, 
clicked on "Ok, I tweeted! Check for it."

![image](https://cloud.githubusercontent.com/assets/5086173/17011709/cf47fa26-4ecd-11e6-8ea4-980eb670a667.png)

And got a button saying "Failed; retry?"

![image](https://cloud.githubusercontent.com/assets/5086173/17011729/f110cbf6-4ecd-11e6-9d4e-11a3e864403e.png)

This was using Chrome on Windows 10.

Here is the twitter popup:
![image](https://cloud.githubusercontent.com/assets/5086173/17011750/22a3e194-4ece-11e6-92aa-15ae5f99535f.png)

**Comment by malgorithms** [comment]
your tweets are hidden - so no one can verify your proof...that doesn't really work with keybase. The idea is that anyone can audit the connection between a public key and a social identity.

**Comment by mattr777** [comment]
I didn't realize that preventing people from following me on Twitter without approval would also make my tweets protected.  I think they should be controlled independently, but that's a Twitter issue.

I wonder if it makes sense for Keybase to send a follower request so that it can see protected tweets?

**Comment by malgorithms** [comment]
the problem is that it's not about keybase seeing your tweets, it's about everyone. What if Keybase servers are evil and claim you've tweeted something? 

I think the simplest answer is to keep your feed private (if you want) and just don't have a twitter proof. you can still tell your twitter followers what your keybase handle is....you just can't be looked up by twitter handle on keybase.

**Comment by mattr777** [comment]
That makes sense.  Thanks.
