### ISSUE TITLE
Why is prove `gist` requiring a public gist?

### ISSUE THREAD

**Issue by weakish** [keybase/keybase-issues#2462]
What about a secret gist?

> Secret gists aren't private.
> ... if someone you don't know discovers the URL,
> they'll also be able to see your gist.

**Comment by zQueal** [comment]
The strength of Keybase is anyone is able to verify your identity using publicly available proofs--meaning I don't have to trust Keybase is doing what it's supposed to be doing in verification. I can just go check by viewing your public gist. If it were a private gist then I wouldn't be able to do that and would need to trust Keybase which is not ideal in crypto.

**Comment by malgorithms** [comment]
FYI - I think technically secret gists would work, because:

(1) given the path to one, anyone can read it
(2) the secret gist page shows who the author is, according to github

the reason we don't support them is that it's an interface difficulty. one of the things that runs on keybase's server is the "hunter" portion of proof verification that finds that tweet or gist or whatever and notes the link, so you don't have to paste a URL in.  (note that when you post a gist, keybase finds it and saves a link to it) 

so to make it work with secret gists, we'd have to ask you to (1) post the gist, and (2) come back and paste the gist's secret URL in. This is more steps to an already cumbersome UX and not high enough demand.

**Comment by weakish** [comment]
> so you don't have to paste a URL in. 

@malgorithms And I guess keybase server does not have to record the URL.

I think one advantage of public gist is others do not need to know the additional URL to verify identity.
Thus they do not need to rely on keybase.io and any other central place or distributed blockchain for this additional information.

For example:

Assuming that Bob trusted Alice's GPG key (alice@example.com),
one day Bob registered at GitHub and wanted to follow Alice at GitHub.
Bob may guess that `github.com/alice` is the account,
or he may find out that Eve's profile `github.com/eve` claimed that she is Alice (e.g. via search).

If Alice proved her identity on GitHub via a public gist in keybase format,
then Bob can just search for the keybase proof gist from `gist.github.com/{alice,eve}` to verify.

If Alice proved her identity on GitHub via a secret gist in keybase,
then Bob need to know the url to that secret gist.
No matter the url is recorded in keybase.io or distributed blockchain,
this brings in additional dependency to the system.
