### ISSUE TITLE
Password Recover Not Working

### ISSUE THREAD

**Issue by jamesward** [keybase/keybase-issues#2491]
After setting the new password I get: `ERROR could not find UID or username for self`

I'm not sure what that error means or how to recover from it.

**Comment by maxtaco** [comment]
Can you do: `keybase log send`

**Comment by jamesward** [comment]
Log ID: `82e2e42ff9fb6993a698861c`

**Comment by patrickxb** [comment]
Hi @jamesward .  I'm looking at your log file.  A few questions:

1. Are you running these commands on a device that you used keybase on previously, or is this a new device?

2. Does this file exist?

    /Volumes/Home/j.ward/Library/Application Support/Keybase/config.json

3. Did you run `keybase passphrase change` or `keybase passphrase recover`?

Thank you very much for your help!

**Comment by jamesward** [comment]
Thanks.

1. Yes, but it was with the NPM module.
2. No:

        ~ $ ls /Volumes/Home/j.ward/Library/Application\ Support/Keybase
        keybase.leveldb

3. `keybase passphrase recover`

**Comment by patrickxb** [comment]
Thanks, I was able to reproduce your error locally.  We will fix it soon so that it will prompt for a username and get past that error.

However, with your account, `keybase passphrase recover` won't work because you haven't provisioned any devices with our new system and don't have a paper key.

What you can do, though, is to use the email-based passphrase reset on the website.  Click on Login, and then "Recover account", then enter your email address.  Once you reset your passphrase using the website, `keybase login` on this device should work fine with your new passphrase.

**Comment by jamesward** [comment]
Thanks!  I'll do that.

**Comment by jamesward** [comment]
This all worked great.  Thanks again!

**Comment by MikeiLL** [comment]
Thanks. You folks are the best!
