### ISSUE TITLE
[Linux CLI] Trying to operate in user directories silently stalls

### ISSUE THREAD

**Issue by RichJeanes** [keybase/keybase-issues#2512]
When trying to `ls` (or open a file or do anything involving files, really) a user directory in `/keybase/public` or `/keybase/private`, the command just hangs indefinitely. Inspecting the logs, I find this:

```
2016-08-22T21:19:42.867867 ▶ [WARN kbfs mdserver_remote.go:134] 461 MDServerRemote: error signing authentication token: Login required: KBFS Authentication
2016-08-22T21:19:42.867900 ▶ [WARN kbfs connection.go:368] 462 (CONN MDServerRemote a6d5bd39) Connection: error calling OnConnect handler: Login required: KBFS Authentication
2016-08-22T21:19:42.867929 ▶ [WARN kbfs connection.go:519] 463 MDServerRemote: connection error: "Login required: KBFS Authentication"; retrying in 1m18.352306053s
```

This is after running `run_keybase` successfully. At no point am I prompted to login to start a session. After running `keybase login` I am able to interact with files normally. While I understand why the commands are hanging in this scenario, there should be either a prompt for the user to login immediately or a message that informs the user that they need to run `keybase login` to establish a session.

**Comment by strib** [comment]
Hi @RichJeanes -- I assume by the "[Linux CLI]" in your title that you are running a headless Linux environment with no window manager?  As you discovered, a manual `keybase login` is required in that case.  You're right it's probably not well documented right now, mostly because we don't want to encourage it as we have no way of notifying the user in that case about the proof status of the users they're sharing data with.  That aside, we also have no way to prompt a password from you on file system access without a GUI, since the file system interface is so limited.  Potentially I guess `run_keybase` could print out a warning if it figures out there's no desktop environment? But there'd still be no way to prompt interactively.

**Comment by RichJeanes** [comment]
That's correct, no window manager.
Perhaps `run_keybase` could check for an active Keybase session and warn if one isn't found? Perhaps also this warning about no way to notify the user of proof status could be communicated there as well? I'm so used to running solely in CLI on Linux that I didn't expect that to be an issue.
I do understand that KBFS is still under alpha, but it would seem that this lack of core functionality when using the terminal warrants statement somewhere relevant (especially when the doc page specifically calls out KBFS access from the terminal as a feature).
I will admit that I have no idea how Fuse interactions work, so I'll take you at your word if there's no way to communicate the authentication error to the user at command runtime.

**Comment by strib** [comment]
Yeah the file system is limited to simple, pre-existing Linux error codes to communicate things back to the shell -- we can't do anything custom there unfortunately.

We should consider updating the docs and/or `run_keybase` to be more explicit about the need for manual unlock.  Thanks!

**Comment by RichJeanes** [comment]
Thank you for the active engagement!
