### ISSUE TITLE
where does it look for lsof?

### ISSUE THREAD

**Issue by jn0** [keybase/keybase-issues#2519]
It looks for `lsof(8)` in `/usr/sbin/` while it lives merely in `/usr/bin/`.

```
jno@blackbox:~$ keybase update check-in-use
▶ WARNING Continuing despite error in lsof: Error running /usr/sbin/lsof [-w -F pcuftn /keybase]: fork/exec /usr/sbin/lsof: no such file or directory ()
{
  "in_use": false
}
jno@blackbox:~$ type lsof
lsof is hashed (/usr/bin/lsof)
```

**Comment by jn0** [comment]
hm-hm...
when I did a bad thing, it still fails
```
jno@blackbox:/usr/sbin$ sudo ln -s ../bin/lsof .
[sudo] password for jno: 
jno@blackbox:/usr/sbin$ keybase update check-in-use
▶ WARNING Continuing despite error in lsof: Error running /usr/sbin/lsof [-w -F pcuftn /keybase]: exit status 1 ()
{
  "in_use": false
}
jno@blackbox:/usr/sbin$ ls -l lsof
lrwxrwxrwx 1 root root 11 Aug 25 10:48 lsof -> ../bin/lsof
```

**Comment by oasfour** [comment]
I may have found something; but somebody with more knowledge of "Go" and experience with Keybase internals will need to take it from here.

```ShellSession
$ keybase update check-in-use
▶ WARNING Continuing despite error in lsof: Error running /usr/sbin/lsof [-w -F pcuftn /keybase]: fork/exec /usr/sbin/lsof: no such file or directory ()
{
  "in_use": false
}
```
keybase/client@37535d4bc5bcd9b00f574869702eacf2892c59b9 hard-coded /usr/sbin/lsof (line 178 of [go/lsof/lsof.go](https://github.com/keybase/client/blame/master/go/lsof/lsof.go#L178)).

The first attempt fails because /usr/sbin/lsof is not found. Some systems have it elsewhere (such as in /usr/bin but just as easily elsewhere).

Workaround attempt...
```ShellSession
$ ln -s /usr/{,s}bin/lsof
$ type lsof
lsof is /usr/sbin/lsof
$ keybase update check-in-use
▶ WARNING Continuing despite error in lsof: Error running /usr/sbin/lsof [-w -F pcuftn /keybase]: exit status 1 ()
{
  "in_use": false
}
```
Workaround attempt fails because /usr/sbin/lsof [-w -F pcuftn /keybase] fails with exit status 1 ().

That same command fails even when directly executed in a shell session.
```ShellSession
$ /usr/sbin/lsof [-w -F pcuftn /keybase]
--- WALL OF TEXT basically dumping the command usage info ---
```

Removing the square [ ] brackets outputs data that (I'm guessing) is used somewhere downstream

```ShellSession
$ /usr/sbin/lsof -w -F pcuftn /keybase
p3360
cbash
u579
fcwd
tDIR
n/keybase/public/omarasfour
```

**Comment by maxtaco** [comment]
Cc @gabriel

**Comment by gabriel** [comment]
The lsof package is only works on macOS... Would be pretty easy to get it to work on linux/unix machines. Am tracking this internally at: https://keybase.atlassian.net/browse/DESKTOP-1835

**Comment by gabriel** [comment]
lsof returns exit code  1, if the file, mount, etc is not in use. If you pass `-V` it will output wasn't found so:

If keybase is not in use:

```sh
> /usr/sbin/lsof -V -w -F pcuftn /keybase
lsof: no file system use located: /keybase
> echo $?
1
```

And yes currently we use full path as `/usr/sbin/lsof` for macOS since this is currently the only place we're using it.

**Comment by gabriel** [comment]
This isn't something we need to support, so am closing.
