### ISSUE TITLE
cp ~/Descargas/file.zip . cp: cannot create regular file './file.zip': Input/output error

### ISSUE THREAD

**Issue by ChrisFernandez** [keybase/keybase-issues#2594]
I am getting that since the last update today...

**Comment by strib** [comment]
Can you please do a `keybase log send` and let us know the ID?  Also, is this on macOS Sierra?  If so, it's known not to work there yet (will be fixed soon).

**Comment by ChrisFernandez** [comment]
No I only use Linux computers.. this is on Arch GNU/Linux(Manjaro) running blackarch repos. Thanks for the help.

```
keybase log send
This command will send recent keybase log entries to keybase.io
for debugging purposes only.

These logs don’t include your private keys or encrypted data,
but they will include filenames and other metadata keybase normally
can’t read, for debugging purposes.

Continue sending logs to keybase.io? (type 'YES' to confirm): YES
▶ WARNING error opening log "/home/cfernandez/.cache/keybase/keybase.updater.log": open /home/cfernandez/.cache/keybase/keybase.updater.log: no such file or directory


------------
Success! Your log ID is:

  f171435956c9a48b4cb4b61c

Here's a URL to submit new bug reports containing this ID:

  https://github.com/keybase/client/issues/new?body=[write%20something%20useful%20and%20descriptive%20here]%0A%0Amy%20log%20id:%20f171435956c9a48b4cb4b61c

Thanks!
------------
```

**Comment by strib** [comment]
Thanks for the logs!  Unfortunately, it seems like there's a problem with that folder, from the perspective of that device.  The device is in a "conflict" state, which means it sees a different view of the folder than the other devices, and it is trying to resolve that conflict.  (This happens when two devices try to write to the folder at the same time, and is usualy resolved quickly and automatically.) However, it is so far out of date that is cannot do the resolution.  This is likely due to a bug that we've already fixed -- your KBFS version is a month out of date.

Probably the easiest thing is for us to just reset that device to have the same view of the folder as the other devices.  However, it will mean you will lose the data that you've written to that device since it went into conflict mode. Have you made any important edits to this folder from that device that you don't see on your other devices?  If so, maybe you should copy the data out onto your hard drive, and after that we can reset the device, and then you can copy it back in.  Please let me know if that sounds ok.  Thanks, and sorry for the inconvenience!

**Comment by ChrisFernandez** [comment]
hey guys sorry took some time, new job etc.. anyways so I deleted it and I think is working now..
thanks!
