### ISSUE TITLE
SYSTEM_SERVICE_EXCEPTION on Windows 10 build 14936

### ISSUE THREAD

**Issue by cerebrate** [keybase/keybase-issues#2595]
After upgrading to build 14936 (latest Insider build), the computer bugchecks with SYSTEM_SERVICE_EXCEPTION as soon as the kbfs drive tries to mount.

This is almost certainly a Dokan issue (and disabling the Dokan driver fixes the bugcheck at the cost of disabling kbfs), but I figure it's worth reporting here for other keybase users who may run into the same problem.

**Comment by maxtaco** [comment]
Cc: @zanderz and @taruti

Please pardon my ignorance, does this mean you got a "blue screen of death" ?

**Comment by cerebrate** [comment]
Yes, that's it.

**Comment by maxtaco** [comment]
Oof, sorry for this behavior, and thanks for the report.  @zanderz what are the commands for getting a useful kernel trace on this?

**Comment by zanderz** [comment]
Hi, what version of the client was running at the time? It would be very helpful to gather the following:
- any .dmp file generated during the BSODs
- the configuration of your system, as generated by MSInfo.
- Keybase log files, located in %appdata%\Keybase

An overview of these last 2 can be found here:
http://answers.microsoft.com/en-us/windows/wiki/windows_10-update/blue-screen-of-death-bsod/1939df35-283f-4830-a4dd-e95ee5d8669d
except, of course, send them to us instead of Microsoft. Keybase logs do not reveal anything sensitive, but memory dumps might, so we recommend sharing those in some non-public fashion.

If you have Keybase working without Dokan, you should be able to do `keybase log send` for those.

**Comment by cerebrate** [comment]
Keybase version is

Client:  1.0.17-20160908172133+f09996a
Service: 1.0.17-20160908172133+f09996a

Running on top of the latest release Dokan.

And msinfo file is attached. 

[msinfo.txt](https://github.com/keybase/keybase-issues/files/502484/msinfo.txt)

I'll need to re-enable Dokan and reproduce the BSOD to get the logs and dump files to you, which I haven't had a chance to do yet, but I'll try and get them to you before the weekend's out.

**Comment by taruti** [comment]
@zanderz Does that testing build contain https://github.com/dokan-dev/dokany/commit/f1b4bc38976b85f41051c81f06c2f40cdacca413 ? It fixes a SYSTEM_CHECK_EXCEPTION that was introduced  in previous driver changes due to recursive calls into the driver from CcPurgeCacheSection.

**Comment by zanderz** [comment]
No. I will merge + build Dokan, then set the test track to those resulting drivers.

**Comment by CrosseyeJack** [comment]
Suffering from the same issue.

> any .dmp file generated during the BSODs
[dumps.zip](https://github.com/keybase/keybase-issues/files/503519/dumps.zip)
These are the dumps from my system. There are some others from someone else having the same issue here https://1drv.ms/u/s!Av6v5jiGWl-FgbpFIb0J-uUXlxmxRA - (taken from: [http://answers.microsoft.com/en-us/insider/forum/insider_wintp-insider_install/14936-upgrade-complete-but-bsod-after-login/425db7be-6a36-4a22-8c55-ac53a1dec7fe)](http://answers.microsoft.com/en-us/insider/forum/insider_wintp-insider_install/14936-upgrade-complete-but-bsod-after-login/425db7be-6a36-4a22-8c55-ac53a1dec7fe)

**Comment by dasbub** [comment]
I'm AaronGilliland from that Microsoft forum. I've attached my KeyBase logs. I can grab other Windows logs on request.

[KeybaseBSODlogs.zip](https://github.com/keybase/keybase-issues/files/503659/KeybaseBSODlogs.zip)

Sidenote: OneDrive isn't working at all for me in this latest Windows 10 build. Maybe they changed something in cldflt.sys and it's affecting KeyBase and OneDrive?

**Comment by cerebrate** [comment]
OneDrive is working fine for me, FWIW.

I have found the time to do a quick test with the dokan driver and the mirror sample provided with it, which causes the same BSOD on filesystem mount, which seems to localize the issue as outside the KeyBase code.

(I include the memory dump for that here, in case you can make use of it in reference to the dokan code.)

https://1drv.ms/u/s!AqrcZdowvFOLqLsbQypTta7rom317w

**Comment by vtknightmare** [comment]
For those suffering from this issue where within 10 seconds of logging in and it crashes with "cldflt.sys" as the reason for crashing...

As soon as you login, quickly hold down shift and click on restart.
From the advanced startup options boot into safe mode
Add the registry key necessary to turn on the msiserver service
Uninstall the keybase app
Reboot and enjoy access to your system

Then wait for the good folks at keybase to fix the issue :)

**Comment by cerebrate** [comment]
@vtknightmare Or if you want to use Keybase without kbfs in the meantime, once you're in safe mode, you can either rename kbfsdokan.exe to something else (since if it doesn't try to mount, you won't blue-screen), or else edit the dokan1 service in the registry to be disabled (set Start to 0x04). Either works.

**Comment by zanderz** [comment]
It would be a big help if someone suffering from BSODs could try this build:
https://prerelease.keybase.io/windows/Keybase_1.0.17-20160930155906%2B16ec3f6.386.exe
We believe its updated drivers address the BSODs but we haven't released more widely because it has exhibited 100% CPU spiking on certain platforms, so proceed with caution.

**Comment by CrosseyeJack** [comment]
First attempt: Ran the installer over the top of the prev install, Asked to reboot (presuming its uninstalling the old version) so rebooted, after reboot it tried to install again and BSOD'ed when trying to  to mount. After the BSOD restart it tried to install keybase again and complained about not finding keybase.msi (iirc). Will try install again and report back.

**Comment by zanderz** [comment]
sorry about that. We're just learning that it seems to be related to a recent Windows Insider version: https://github.com/dokan-dev/dokany/issues/359

**Comment by CrosseyeJack** [comment]
No worries (for me any way) as I can use KB in a VM for kbfs for the time being. Still having the issue with it trying to install "keybase apps" (may be due to it BSOD'ing before finishing the prev install). will report back once I get it installed :-)

**Comment by CrosseyeJack** [comment]
Unable to install the test build at all, getting BSOD before the install process completes. 

[dumps_testBuild.zip](https://github.com/keybase/keybase-issues/files/506942/dumps_testBuild.zip)
[Keybase_20161003193600_000_KeybasePrograms.txt](https://github.com/keybase/keybase-issues/files/506949/Keybase_20161003193600_000_KeybasePrograms.txt)
[Keybase_20161003193600.txt](https://github.com/keybase/keybase-issues/files/506950/Keybase_20161003193600.txt)

**Comment by Liryna** [comment]
Hi @CrosseyeJack ,

can you run `!analyze -v` with Windbg ?
https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#crash-report-bsod

Are you able to get your system clean ? (without dokan & kbfs) does it BSOD without it ?

**Comment by CrosseyeJack** [comment]
Not getting BSOD's until I run anything related to dokan/kbfs. I'll do as you ask and report back (Sorry I posted on the other issue before seeing your reply here).

**Comment by CrosseyeJack** [comment]
@Liryna I tried to install Dokan as you instructed in the other issue report but I didn't get (or I just didn't find) the sample mirror.exe to run the test, so I downloaded the release zip file, unpacked it and ran it from there instead. I also set "C:\PathToDokanDbg" to that folder, I hope that was correct, if not please advise and I'll rerun it. Followed the instructions and opened memory.dmp, set the debug symbols and ran !analyze -v. The attached file is the output from windbg.

Need anything else let me know (I'm heading out in a short while so I'll run what ever when I get back, worse case I'#ll just create you a user account on this machine and give you remote access and you can do it yourself :-p).

[windbg.txt](https://github.com/keybase/keybase-issues/files/507048/windbg.txt)

**Comment by cerebrate** [comment]
Fixed in latest Dokan snapshot build, at least for me: https://github.com/dokan-dev/dokany/issues/359#issuecomment-252159716 .

**Comment by x-ji** [comment]
It seems that I encountered the same issue (SYSTEM_SERVICE_EXCEPTION, `wdfilter.sys`) today after installing the latest Keybase update on my Windows 10 Insider Preview. I'm not 100% sure if it was caused by Keybase but that seemed to be the only change in my system. I tried to boot in Safe Mode to make changes but even that would immediately lead to the same exception for some reason. Later I couldn't even get to the login screen. I also have a dualboot Linux system and I'm sure if I tried a bit further I should be able to solve it. But this is not my main computer anyways and I just reinstalled Windows.

**Comment by zanderz** [comment]
@x-ji Was Keybase installed and working previously? When was the filesystem part added? Are you certain what version of Dokan was included? We haven't attempted to automatically upgrade Keybase users' Dokan in quite awhile, but the latest drivers still work. Maybe you could upgrade those if you run into this again.

**Comment by x-ji** [comment]
I'm not sure about the exact versions since I wasn't able to log into the system at all after the error occurred. Yeah, Keybase had been installed and working for a while prior to this. It'd be good if more bug reports from users encountering the same issue could be filed to confirm the issue. Might just be some unrelated issue in my Windows. Without further debugging and logging it's quite hard to look into it further.
