### ISSUE TITLE
Proof format change?

### ISSUE THREAD

**Issue by kyrias** [keybase/keybase-issues#2597]
So apparently my https proof broke, but I couldn't figure out what was broken, since it was right there and nothing had changed.  So I figure I might as well try replacing the proof at least, since hey, maybe it'll work.  Clicking the "replace proof" link on the keybase website, I get told to use the following command to replace it:

```
keybase prove web https://theos.kyriasis.com
```

But of course that errors out, complaining that a proof already exists, and the website didn't say anything about revoking the old broken proof first.  So I revoke the proof, and then create a new proof, and voilà, it works.

Summary
------------

It seems like the format of the https proofs changed and I was not notified about this change in any way other than a vague email about my proof failing, with no form of indication of what might be wrong, and the website is misleading.

**Comment by maxtaco** [comment]
CC @mlsteele can you take a look?

**Comment by mlsteele** [comment]
Hi @kyrias,

I'm glad replacing the proof worked for you, I'll definitely look at making those replace directions clearer. It would be great to get to the bottom of why it failed in the first place. Would you be willing to do a `keybase log send` and post the id here?

**Comment by kyrias** [comment]
`aec9c98dcf32694807f0fe1c`.

The old proof is [here](https://git.kyriasis.com/theos-website/tree/src/.well-known/keybase.txt?id=b944832d593683e54c216d23bb493b302b521e29) and the new one [here](https://git.kyriasis.com/theos-website/tree/src/.well-known/keybase.txt?id=6c3536e06806f0499227e9f14082f489cff0eea7)

**Comment by mlsteele** [comment]
Thanks!

The 3 most recent proofs of yours for that site are
[20 (6/26/14 6:43am)](https://keybase.io/johannes/sigchain#26fcb5884f0c32cdde800355aac5585a4670d20e64e027e3989845d0b13bd6260f)
[39 (5/11/16 1:37pm)](https://keybase.io/johannes/sigchain#b86e1bc7df44b21981a1ea6aa83810e4dc940cad00f0000229c0130e36e6aff10f)
[44 (9/30/16 6:13am)](https://keybase.io/johannes/sigchain#1f58232304f28a6a91d1c6bc97362aaa3f5c1c17d02dfb96a8a6c749b2c9faed0f)

39 is the one you reported broke unexpectedly, after which you made 44 which is working. It looks like your site repo only has commits for 20 and 44, and is missing 39. So it's hard to determine what might have caused 39 to break. Do you think you might have not committed 39 and just overwrote it with 44?

We didn't make any changes recently that should have affected the proof, and since it was found invalid by both our servers and your client at about the same time my current best guess is that your server may have been serving an empty or otherwise problematic response.

**Comment by kyrias** [comment]
Ah, that's weird.  I guess it might have somehow not have been added when re-deploying.  Sorry for the bother then!

(And I apologize if I sounded passive-aggressive earlier, I was in the middle of a couple of other things so didn't pay much attention to my writing.)

**Comment by mlsteele** [comment]
Ok, I'll close this issue and make a note to check out the replacement ui on the site.

(Don't worry about it, I didn't notice :)
