### ISSUE TITLE
Can't make a new account with a no-longer-used email.

### ISSUE THREAD

**Issue by binarySwordsman** [keybase/keybase-issues#2661]
I originally accepted an invite to Keybase using a mismatched email and username. I've since updated the email I'm using to the one that matches the name, but now I want to create an account for my other name/email pair. Whenever I try to send an invite to that other email (the one I was originally invited to Keybase through), it says that address was "invited by someone else already." That email is no longer linked to any Keybase account in any way, but it was the one that received and accepted an invite in the past.

**Comment by zQueal** [comment]
This is intentional--and a security feature. You can easily bypass it though by using an email proxy;

For example, if the email you originally used was `fname.lastname@gmail.com` you can still use it by inviting `fname.lastname+keybase@gmail.com`. It will still route correctly to `fname.lastname@gmail.com`.

**Comment by binarySwordsman** [comment]
That worked, thanks so much!
