### ISSUE TITLE
Secret key isn't protected

### ISSUE THREAD

**Issue by voanhduy1512** [keybase/keybase-issues#2676]
Hi,

After generate a pgp key on keybase, if i export the key using keybase website, the key will be protected using my keybase passphrase. But if i export using command line app, the secret isn't encrypted.

So is that mean my secret key (which generate by keybase) is store unprotected on keybase server? And why when i export using cli it doesn't have passphrase?

Thank you

**Comment by zQueal** [comment]
> So is that mean my secret key (which generate by keybase) is store unprotected on keybase server?

No. At no time is your secret key ever unencrypted when passing through Keybases' servers. I can't speak for the team because I don't know for sure, but I'm almost positive that's why, when exported via the website, your key is password protected. Because if it weren't, and it were exported in plain text, then sensitive information could be stolen via MITM. Or at least this could be one possible reasoning for it. The chances of this happening on the console are far less because everything is done locally.

But take it with a grain of salt because it might not be why it's done this way.

**Comment by voanhduy1512** [comment]
@zQueal but then why why i export the secret key using command line tool, it don't have any passphrase?

**Comment by zQueal** [comment]
Judging by [this post](https://github.com/keybase/keybase-issues/issues/1912#issuecomment-163956144) from Chris it looks like `keybase pgp export --secret` __decrypts__ your private key. So you would expect a decrypted key to be in plain text and without password.

**Comment by voanhduy1512** [comment]
Thanks. That makes sense.
