### ISSUE TITLE
Unable to verify github proof

### ISSUE THREAD

**Issue by u1735067** [keybase/keybase-issues#2687]
Hi, 

I just submitted an old proof for my github account, and while the payload and the signature is correct (I think ?), it fails to verify.
URL : `<snip>`
Something wrong in the proof I posted ?

Btw, what is the string in parenthesis on https://www.reddit.com/r/KeybaseProofs/ ? Is it documented ?

Thanks !

**Comment by Alex131089** [comment]
I figured out parenthesis string is `base64.b64encode(bytes.fromhex(sigId[:-2]))` (0f removed at the end ?)

I'm not able to verify my reddit either : https://www.reddit.com/r/KeybaseProofs/comments/5ev1a8/my_keybase_proof_redditalex131089/

Is there template of what should be the post ? Because for both GitHub and Reddit I fully copied posts from others and it fails. No precise reason in the received email ? No standalone keybase client on Windows (I'm not interested in explorer integration, nor installation) ?
