### ISSUE TITLE
Choosing which PGP key, device key, or paper key to sign proofs with

### ISSUE THREAD

**Issue by grempe** [keybase/keybase-issues#2735]
In your blog post about the new (now not so new) key model:

https://keybase.io/blog/keybase-new-key-model

You show the example of signing proofs with a paper key ('death_punch'). How would one actually go about doing this?  Bigger question, if I don't like that new proofs are signed by a device key that happens to be associated to my current machine (let's say my laptop) and instead I want that proof signed by my PGP key how would I do that?

I don't really like that all my recent proofs (and even a second PGP key I added) are signed by the device key on my laptop. If I lose that single device I would need to revoke that device key and therefore lose all my proofs right?

Instead, if my proofs could be signed by a top level PGP key, or a portable paper key of my choosing, I could lose any device without having to re-create all my proofs. I've searched the docs, CLI help, and google to no avail.

My graph:

https://keybase.io/grempe/graph

**Comment by malgorithms** [comment]
If you lose a device, the other keys/devices which it previously provisioned are considered valid. So I don't think you'll have the contagious proof losses you mention. Consider this portion of Max's graph (https://keybase.io/max) : 

![image](https://cloud.githubusercontent.com/assets/614943/21405732/ba33fe00-c795-11e6-8d67-7cb1e5f11e3f.png)

He provisioned a computer called `work imac` and then, using that, added a paper key. The paper key then provisioned `work-iMac-5k...` . But then he later revoked `work imac`. This doesn't invalidate his paper key or the work-iMac-5k he added afterwards.

It also doesn't invalidate any proofs done before the revocation.

here's why:

- all these announcements are in a signature chain and the strict ordering of all these operations is 100% provable. So anyone knows it was a legit key at the time of the provisioning. (Click the "chain" tab to see.)

second, when performing the revocation, he could've revoked any other devices or proofs he considered invalid. He provably had that power and chose not to. So by convention we say that his choosing to keep those devices/proofs while revoking their parent means he still considers them valid. If, on the other hand, he had Device1 stolen and it was used to provision Device2 and add github identity X, he wouldn't just revoke Device1. He would revoke Device2 and github identity X. So by not revoking them, he's choosing to keep them.


In answer to the first part of your question, when you provision a new device it asks you how you want to do it...one of the options should be to choose your existing paper key, if you have one. Depending on the platform you may be able to choose PGP as we're making that easier. If you use KBFS, we recommend not using PGP, since it means you won't get to unlock your files on the new device until one of your other devices comes online to unlock it.

**Comment by grempe** [comment]
Thanks @malgorithms for the explanation.

Firstly, the information about 'contagious proof losses' (I like that term!) is very good. I am glad to hear that, and I don't think I've seen that mentioned anywhere else in the keybase docs or blog posts. It should be more widely disseminated.

However, if you look at Max's graph *all* of his proofs are signed directly by his PGP key. Is that only due to the fact that he created those proofs prior to device keys being introduced? About half of my proofs are similarly signed by my PGP key, all of the newer ones are signed by my potion-factory laptop.

So again, in the new key model blog post you demonstrate that a **proof** (Twitter @foo) was signed by a paper key (death_punch).  How would I actually do that? If I want my **proofs** to be signed by my original GPG key or an arbitrary paper key I control, and not the key of the device I am using at the moment, what is the command line I would use to do that?

Or is that not actually possible? This is not really causing me an issue at the moment, but the blog post and reality seem out of sync now and I find my proofs being split between PGP key and device keys somewhat untidy (yeah I know... roll eyes).

Essentially I want to be able to re-link **proofs** from one device/paper/pgp key to another. For the sole purpose of having my graph hierarchy look the way I think it should and making it easier for humans to parse. Housecleaning.

Also, the way my current graph is show it appears that all trust derives from my original old pgp key. I've added a new one which I plan to replace the old one with and I'm thinking that the way its currently presented makes one look less important than the other. Is that just an artifact of me having an early keybase account?

Thanks

**Comment by malgorithms** [comment]
ah max's probably wasn't the best example... I was pointing out that just because he revoked a device doesn't make its previous signatures invalid.  Anything he put in his sig chain *before* the revocation (adding another device or proving something) was still considered valid. This is true for both identity proofs and device additions. it's also true for tracking people -- really, anything in your signature chain, since those announcements are well-ordered and reviewable.

so, for example:
1. you uses devices D1 and D2.
2. you prove you have a twitter account, using D1.
3. you add a third device, D3.
4. you revoke D1 with either D2 or D3.

the twitter proof is still valid. you are that twitter user on D2 and D3 - on any of your remaining devices. Hope that might be a simpler explanation.

back to your question about paper keys: we actually don't expose a way to sign a proof using a paper key (since no one had asked for it yet; probably because most people would just end up typing the paper key in again on a computer that has its own device key already, which could do the job easier with the same security exposure.)  So the example in the blog post ended up wrong, I guess, even though it's actually technically possible if someone did it by hand or something. All the clients would end up understanding it, and it would show up in the graph like that.

I probably wrote the post thinking we'd support it.

To be clear: a device key and a paper key are indistinguishable except for the fact that they're tagged as device or paper keys in the sig chain. they're really the same kind of key pair! the paper key also presents itself as a string of words, for transcription convenience...but underneath they're really the same thing.

perhaps one final point: our graph is there to show the flow of signatures, but it's not really there so you have to think about the edges. You are the sum of your proofs + devices, and you're not supposed to worry about which device did what.   The sum of the graph is you -- if D1 signed a proof, then D3 is still you, and so it still has proven that same thing, indirectly. If you want to remove a device, you never have to think about which parts of your identity get broken. Nothing will.

btw, if you want to prove things with your pgp key always, you can use the website to get instuctions to do it by hand. Start on the website, and you'll get to this modal:

![image](https://cloud.githubusercontent.com/assets/614943/21408585/c71873b8-c7a3-11e6-8077-8b0a75d876e3.png)

it will tell you what PGP command to run so the proof is done with gpg instead of keybase.

**Comment by grempe** [comment]
OK, thanks for taking the time (and so quickly!) to answer my questions. I think you addressed them pretty well. To summarize:

1) You can't sign a proof with a paper key, contrary to the blog post example image and text.
2) You don't 'lose' any proofs attached to device keys you revoke. You are the sum of all remaining proofs
3) The device/key graph top-down implied hierarchy is not really a hierarchy. If I have a chain like Account -> PGPKey1 -> DeviceKey1 -> TwitterProof, a revoked DeviceKey1 does not break TwitterProof, even though visually in the graph it looks like it would since there is a revoked device node in the graph that has edges to non-revoked nodes.
4) You **can** sign proofs with your GPG key instead of a device key, but you have to choose the right option in the proof modal dialog (options which have undocumented differing behaviors, namely signing with device nacl keys vs. an OpenPGP key)

I think I have a better understanding now. So maybe this is really a feature request to convert the blog post to living documentation that reflects the  actually implemented key model and all of the good points, and caveats, we talked about above.

Cheers

**Comment by grempe** [comment]
I'll close this issue, since its not really an issue.  But I would request that an update to the documentation and the blog post be made to reflect the info in my summary.

PS Since this issue was opened, I did revoke my eldest PGP key and all seems well as you told me it would. 

https://keybase.io/grempe/graph

Cheers
