### ISSUE TITLE
Public KBFS not syncing with keybase.pub; unclear GUI notification

### ISSUE THREAD

**Issue by dephekt** [keybase/keybase-issues#2741]
Keybase GUI Version: 1.0.18-20161219123904+7868d49

The Keybase GUI is showing an orange one (1) next to Folders, which looks like it's trying to tell me there's some sort of issue with file syncing, but nowhere can I find a way to get the client to elaborate on what it's trying to communicate to me:

![issue2](https://cloud.githubusercontent.com/assets/7564683/21472943/4d3753c8-cab6-11e6-9361-6eac3b374f0d.jpg) ![issue1](https://cloud.githubusercontent.com/assets/7564683/21472942/4959a850-cab6-11e6-8cbd-f31db2ad8805.jpg)

Another issue which is possibly related to this orange notice is that files I've deleted in my public KBFS folder do not appear to be syncing with my Keybase.pub site:

1. My Linux web server is hosting my site with the content stored on mounted public KBFS folder
2. My Windows desktop and Linux laptop also have KBFS mounted
3. From Windows I delete K:\public\dephekt\site.tar
4. My web server shows the file deleted: https://dephekt.net/site.tar
5. My Linux laptop shows the file deleted in /keybase/public/dephekt/
5. https://keybase.pub/dephekt/site.tar as well as https://dephekt.keybase.pub/site.tar still offer the file

I've also added files to the public folder recently and am not seeing them replicated on keybase.pub.

**Comment by Kajisav** [comment]
The files seem to be syncing as expected now, but the issue with the folder notification being unclear is still a thing.

**Comment by strib** [comment]
Hi @Kajisav,

The keybase.pub issue was because you reset your account on 12/24, and there's currently a known bug with keybase.pub that doesn't refresh it's view of the folder until we restart it (which we did this morning).

The notification is not about not syncing, it means you have a new folder that you haven't looked into yet.  There's also a known issue with this notification if you reset your account, which is being worked on, so if you see a folder in the app badged with "new" and can't get rid of it, that's the issue.  We're working on it.

**Comment by Kajisav** [comment]
Ah, yeah that sounds exactly like what's going on. I've reset my account several times in the past. Thanks for the reply.
