### ISSUE TITLE
Facebook browser proof failed

### ISSUE THREAD

**Issue by olegatro** [keybase/keybase-issues#2768]
Many times trying verify my facebook account.
But all times result - failed.
Can you check please ?

https://keybase.io/olegatro
https://www.facebook.com/olegatro/posts/649426738562818?pnref=story

**Comment by oconnor663** [comment]
Thanks for the report! This is an interesting bug. It turns out because you have ".com" in your name on Keybase, Facebook ends up putting an extra <a> tag around that part of your name in your post, and that confuses the part of our code that's pulling text out of those tags. We'll fix this bug soon and then your existing proof should start working without any changes on your part.

**Comment by olegatro** [comment]
Oh, now I understand what the problem is.
After fixing, can I change my name field (which has my email) to a real name?
I think, after sign up and getting access I forget to change full name field.

**Comment by oconnor663** [comment]
You can change your name on the website at any time. If you did that and then made a new FB proof, that should work around this issue. But if it's ok with you, maybe leave your existing proof up for a few more days so that we can test the fix for this? :)

**Comment by olegatro** [comment]
Sure, no problem. 
Just write when I can change my full name. I'm not hurry.

**Comment by olegatro** [comment]
Just got email what my proof on facebook was succeeded.

**Comment by oconnor663** [comment]
Yep, just pushed the fix!

**Comment by oconnor663** [comment]
If you have the very latest Linux update you should be able to `keybase id` and see your FB proof too. The macOS update will take a few days to roll out.

**Comment by olegatro** [comment]
Yep, from command line (ubuntu) working too. 
P.S. thank you for awesome project.
