### ISSUE TITLE
Web verification failed

### ISSUE THREAD

**Issue by barrykooij** [keybase/keybase-issues#2778]
Hey there,

I can't seem to verify my website while I _think_ the `keybase.txt` file is correctly there. 

URL: https://www.barrykooij.com/keybase.txt

Cheers,
Barry

**Comment by malgorithms** [comment]
hmm, I don't see anything offhand that's messed up with the proof. One thing we do is check for `.well-known/keybase.txt` first (since some people prefer that as a standard) and then we only check keybase.txt if that doesn't work. Your site is different from all others I've seen in that visiting https://www.barrykooij.com/.well-known/keybase.txt doesn't 404, it redirects. Not only that, but it goes into an infinite redirect loop to https://www.barrykooij.com/.well-known/keybase.txt/=404 which redirects back to itself. This bug (arguably on keybase's side) could be that it either considers the redirect a statement that .well-known should be used, or it gets enraged by the infinite redirect and stops there.

It's just a theory since I haven't looked at how our checker code handles a redirect to 404 in so long...if you want to try changing that behavior and then going to the site and trying the proof over again, I'd appreciate it. If not, we can eventually get to doing some more tests.  (if this is the issue, this is the first report of this I've seen....it still should eventually be fixable on our end.)

**Comment by barrykooij** [comment]
@malgorithms I'm happy to do some testing on my end/website. What is it you want me to test? Place a `/well-known/keybase.txt` file?

**Comment by malgorithms** [comment]
I have a feeling that if you do that it'll fix the problem. Note it's `.well-known` not `well-known` (see the dot?)

Alernatively tjust to make `/.well-known/keybase.txt` actually 404, that would be the most interesting test.

either way, maybe make one more new proof when you do it.

thanks!

**Comment by barrykooij** [comment]
Sorry for the silence on my end. I did some further testing and for some reason my Nginx server goes into a 302 loop because of the following line:

`location ~ /\. { access_log off; log_not_found off; deny all; }`

This line is to prevent loading/viewing of files that start with a dot but seems to be creating a 302 loop while doing so. Because keybase checks ```/.well-known/keybase.txt``` first, it gets into this loop and won't check ```/keybase.txt``` which is there.

I haven't found a solution to the problem yet as I want to keep denying access to files starting with a ```.``` but I'm closing this for now as this is an issues with my server and not Keybase. I do feel like it would be a _nice to have_ if keybase would be able to break a loop and _read_ it as a 404, therefor checking for the file in other locations :)
