### ISSUE TITLE
keybase thinks my storage is full, but nothing is in my folder

### ISSUE THREAD

**Issue by adigregorio** [keybase/keybase-issues#2790]

**Comment by strib** [comment]
Sorry about that! Did you put a lot of data in there and then delete it?  Because of the end-to-end encryption, we rely on the client to tell us when that data is no longer in use, and we don't want to overload your client, so it takes some time for this to happen.  And right now, there's a bug making it even slower than usual, so it might take a really long time.  But if this is the case, if you let your Keybase client run long enough, it should clean things up eventually (we are working on the performance bug right now.)

The other thing to note is that anything you've written in any folder, including ones shared with other people, counts towards your quota.  So just because your private home folder is empty, doesn't mean you're not using any quota.  But I'm guessing you wrote data and then deleted it, in which case the above advice should work.

And if it doesn't seem to work, I'm sure we can help you out with extra storage, at least until things get cleaned up.

**Comment by adigregorio** [comment]
Ah you know what, I did. I dumped a whole shitload of data in there. Since the client might be the issue, I'll keep it open today and see if that helps. Thanks!

**Comment by strib** [comment]
Thanks, please keep us posted.  Obviously you didn't do anything wrong, it's our stupid bug.  Oh, and if you've restarted Keybase since you last touched the folder, please look in the folder at least once today, even though it's empty, as that's what triggers cleanup.

**Comment by adigregorio** [comment]
I wasn't getting any "storage full" notifications at all this morning, then looked in my folder and now I am. Will restart it later this afternoon and report back.

**Comment by strib** [comment]
Oh hrm.  I wonder why you'd see that message if you weren't writing anything new.  I'm happy to investigate if you'd like -- if so, please do a `keybase log send` and report the resulting ID here.

**Comment by adigregorio** [comment]
still getting storage full notifications, but only every 30 min or so. here's the log id: 1b035a8f5720d9dd5789cc1c

thanks!

**Comment by strib** [comment]
Ah ok, I see it.  The process of cleaning up quota is itself using some storage.  That's another bug we're working on.  I'll see about getting you more storage in the meantime while things clean up.

**Comment by adigregorio** [comment]
ah, interesting. thanks for your help!

**Comment by strib** [comment]
I put some instructions for you in `/keybase/private/strib,digregorio/updating_your_quota.txt`.  Let me know if that helps!

**Comment by adigregorio** [comment]
YES.

awesome, thank you so much @strib. I'll close this issue now. thanks again!
