### ISSUE TITLE
ReKey is hanging and takes a paperkey but never rekeys.

### ISSUE THREAD

**Issue by linux-modder** [keybase/keybase-issues#3000]
[linuxmodder@crypto-lin]~% keybase --version
keybase version 1.0.24-20170608172739+f903fee

Logs:
d71e237893bd3fd21943fc1c

https://github.com/keybase/client/issues/new?body=[write%20something%20useful%20and%20descriptive%20here]%0A%0Amy%20log%20id:%20d71e237893bd3fd21943fc1c

**Comment by strib** [comment]
Hi @linux-modder, it looks like you have two folders that are not yet keyed for your paper key yet (which you just created yesterday).  You need to run Keybase on your `cryptodragons-20170604` to rekey those folders.

**Comment by linux-modder** [comment]
That was nuked due to issues with the host machine.  That seems pointless then if it needs rekeyed and can't take a paperkey.

**Comment by strib** [comment]
It can't take that particular paperkey, because you didn't create the paper key until after the folders were unreadable, unfortunately.

I just noticed that both of those folders are with other users.  So all you need to do to get access is to ask those other users to sign into Keybase on one of their devices, and they will do the rekeying for you.

Let me know if you can't figure out which users I'm talking about -- I don't want to say their usernames in a public forum.

**Comment by linux-modder** [comment]
That would faster, closing and will do that
