### ISSUE TITLE
[All platforms] User switch feature

### ISSUE THREAD

**Issue by dabura667** [keybase/keybase-issues#3015]
Similar to Slack's team switch option, Keybase should have a user switch option that allows for multiple logged in users on one device.

On iOS and Android, push notifications would be active for all currently logged in users.

Switching between user profiles should be a two tap process.

Just as most people have a personal email and a work email, I personally am planning on using Keybase with a personal account and a business account. But currently that is not too feasible, as I would need to log out then back in to check for messages on chat etc. manually.

Great app, though. This multiple user switch feature would make it so much better.

**Comment by Idyllei** [comment]
I would _love_ this kind of feature. I am a college student and it would be incredibly useful to have separate accounts for personal and academic use (I like to try to keep my lives separate).

I think, however, it should be just a tad more difficult than a two-tap process. That would make it too easy for a malicious user to compromise separate, though related, accounts. Instead, it might be useful to ask for a PIN, pattern, password, or another piece of information (e.g., a date; a color combination, which should take into account color blindness; a fingerprint, given a compatible device; a [Yubiko 2-Factor Auth Bluetooth/USB Key](https://www.yubico.com/), etc).

If making this kind of change could possibly lessen the security of the system, don't make it. **Security should not be compromised when making a change to the system, even if it makes it more comfortable to use--it's only comfortable until you've been compromised.**

**N.B.:** I would love to be allowed to use multiple layers of security. For example, being asked for a password and then a PIN, or vice versa, to make sure that it really is me. I say this because sometimes couples share PIN numbers or account information, and--in an extreme case--if one person is convinced to give out one of those pieces of shared information, all hope is not lost when it comes to security of your account.

**Comment by zQueal** [comment]
> I am a college student and it would be incredibly useful to have separate accounts for personal and academic use (I like to try to keep my lives separate).

Keybase attempts to tie identities to a single person. Why not just make one key with multiple sub-keys, one for private and one for academic usage, and use them on the same Keybase user?

IMO, that more closely aligns with what Keybase is meant to do. Then you wouldn't need to juggle multiple accounts, either.

Additionally, 2FA is something I'm passionate about and I'd really love to see it sometime soon.

**Comment by dabura667** [comment]
> Keybase attempts to tie identities to a single person

I would argue a "single persona" would suffice. ie. I have 3 major GPG keyrings attached to three personas I have online. My interactions on all personas are fine, and one of them is connected with my irl name.

Perhaps keybase's vision is different, but I am viewing keybase as "GPG but with a modern SNS feel"... which means I would want to import my 3 personas and switch them freely.

> I think, however, it should be just a tad more difficult than a two-tap process.

Currently, the keybase app allows anyone with physical access to the unlocked device to read all messages and perform all actions without a password or PIN... what you are asking for should be a separate issue, and how that issue would integrate into my suggestion is a topic for that issue imo.

I agree there should be an option for a PIN setting to thwart the layman phone snooper... but you should lock your smart phone and never give your unlocked smartphone to someone unsupervised in general.

**Comment by heronhaye** [comment]
In Keybase 5.0 you can switch users without logging out.
