### ISSUE TITLE
<username>.keybase.pub 404

### ISSUE THREAD

**Issue by lukebarton** [keybase/keybase-issues#3024]
https://lukebarton.keybase.pub/ssh_keys/id_rsa.pub is now giving me `Not Found`

In the keybase app, when I click `Open Folder` viewing my public files I can see the files I expect to see however I can't see my public files via my keybase profile any more: 
https://keybase.io/lukebarton

https://keybase.pub/lukebarton/ also gives 404, opposed to
https://keybase.pub/marcopolo/ which seems to work

This is affecting 10 other members of my team (we were using these public urls to share our ssh keys).

**Comment by maxtaco** [comment]
cc: @malgorithms @cjb @strib

**Comment by malgorithms** [comment]
back up very shortly - apologies

**Comment by malgorithms** [comment]
and the site should be back up

**Comment by ghalfacree** [comment]
I am aware that this issue is from July 2017, but it appears to have reared its ugly head again (or a different issue with the same symptom): despite having an ```index.md``` in my public folder, I'm getting a 404 on the keybase.pub site whatever way I try:

https://keybase.pub/ghalfacree/ - "not found"
https://ghalfacree.keybase.pub/ - 404, "there is not an index.html or index.md here."
"ghalfacree" manually entered into keybase.pub search box - "not found."

The two accounts linked from the keybase.pub homepage - marcopolo and chris - seem to still be working fine.

**Comment by maxtaco** [comment]
Cc: @strib

**Comment by strib** [comment]
@ghalfacree your report is a dup of keybase/kbfs#1578.  See there for more details.

**Comment by strib** [comment]
Should be fixed now.
