### ISSUE TITLE
Question: What if Keybase is/goes down?

### ISSUE THREAD

**Issue by carterworks** [keybase/keybase-issues#3089]
**TL;DR** What happens to my files if Keybase is down (temporarily, permanently)?

This is a problem inherit in all SaaS platforms, but it seems a little more serious here. 
If Keybase goes down, how can I get my files?
Are they somewhere cached on my machine so that I may decrypt them somehow?
If that is just pgp encryption, what is my passphrase? My Keybase passphrase?
Does the Keybase client work offline?

**Comment by hach-que** [comment]
This is a major concern for us before we migrate from existing services to Keybase.

There's no active paid plans for Keybase, and I'm assuming the server infrastructure costs for running this system with all the storage and compute it requires is likely to be in the 5 or 6 digit figure a month range. There's no open source equivalent of the Keybase server, so if it goes down and the client software is heavily coupled to it, then you've lost all of your encrypted data because you can't use the client software to access it any more.

Services like Google Drive are a lot less secure in the sense they're not encrypted, but Google is a big company, and Google Drive isn't going anywhere due to the number of corporations that are paying for that service today.

**Comment by sks7g** [comment]
That is also a very important point for me. Backup, export, restore chat history and the files it contains. This also includes the KBFS! What's the point of using this service if I have to save everything again. As an alternative to KBFS there is the integration of GIT, but the chats are very important. When I talk about projects and exchange files with each other, I'm always forced to back up the files to another location, but I can't back up the conversation! Here a PDF integration would be very helpful and also the "offline" availability.

BTW: There is an interesting website for backup: https://wiki.chotaire.net/keybase
BTW2: I have switched my phone completely offline, I can call the (downloaded) chats, that seems to work.

**Comment by carterworks** [comment]
Well, I guess we'll all find out.
