### ISSUE TITLE
Able to see any other user's device names just by typing in their username when prompted to log in

### ISSUE THREAD

**Issue by x-ji** [keybase/keybase-issues#3103]
I'm not sure if this has been reported before or if this is considered a problem at all. When I'm prompted to log in, I can practically type in any existing username and I'll be prompted "which device would you like to connect with", thereby immediately seeing all the devices of this user that has Keybase activated. 

For example, if I type in `songgao`, I can immediately see that he has an iPhone, two MBPs, and a Thinkpad, with the devices' names also displayed.

Shouldn't this be a privacy concern? Sure you probably can't hack anybody just by knowing what devices they own, but I'd rather not let any stranger know what devices I have so easily. Though I guess maybe Keybase considers this a part of a user's public identity?

**Comment by malgorithms** [comment]
good question - device names are public by design. You can see every statement I've ever made about my identity, including my device names, here:

https://keybase.io/chris/sigchain#fefa480de72f25ca568b5939ce7b56903dd38e4f1b9e43b3218caefbff67575d0f

The goal is for a device name to equate to a key without ever sharing a fingerprint or or public key. This is also why we don't ever let you reuse a device name in your signature chain.

(note that when we ask you to name your device, we say that it's a public name.)

**Comment by vetras** [comment]
can we rename devices, at least?
