### ISSUE TITLE
How to reset everything and start over completetly?

### ISSUE THREAD

**Issue by rfgamaral** [keybase/keybase-issues#3158]
I know about the `Reset your keys & start from scratch` option - which I've already used - and it was my understanding that this would completely reset everything, but it didn't.

I mean, I tried to setup my account again and I tried to name my devices with the same names as before, which was not allowed. But I really wanted to use that name, and now I can't.

The chain doesn't seem to be reset. Why isn't the chain reset?

I barely did anything with Keybase, never proved any of my identities, never used the generated PGP key for anything, etc... Is there way for me to really start over like I had never registered with Keybase?

**Comment by lemonforest** [comment]
It's my understanding that everything is immutable by design.  As such, right to vanish does not apply. `DELETE ME` also mentions that you cannot make a new account with the same name, in which case, you have to become someone else. 

Assuming a matching GitHub real name with a Keybase real name means this is you, here's a thing;

- json formatted proof your account is immutable
https://keybase.io/_/api/1.0/user/lookup.json?usernames=rfgamaral
- beautified proof your account is immutable
https://keybase.io/rfgamaral/sigchain

You appear to still have access to the account and have not nuked it, so you might try revoking the device such as you would if it were stolen. Even if the device is revoked, you may still be restricted from creating a newly signed device from using a revoked name. Were I a lot smarter, and I wanted to pretend to be you and I was able to take control of your account, perhaps I would authorize a new, rogue device using the same name of a device you'd previously used to try and trick someone that my `Glorious PC` was in fact really yours because it used to be yours, I could then have all the cryptokitties they'd meant to send to you sent to me.

**Comment by rfgamaral** [comment]
I see your point but this is a newly created account which I haven't used it for anything yet... I just wanted to erase everything and start over with the same username. It bothers me that I can't, it's triggering my OCD. I would understand if I had verified myself already or if I had used some PGP keys for something, but I didn't. 

> so you might try revoking the device such as you would if it were stolen

I think I did that already: 
![image](https://user-images.githubusercontent.com/96476/35218479-bc218854-ff66-11e7-9bd9-b953cd05099d.png)

**Comment by junderw** [comment]
@rfgamaral Blockchains can't delete records, only add a record that you removed data... but the record of the old data remains.

Similarly the sigchain of Keybase is permanent, if you connect two Social medias to one keybase account and quickly realize OH NO I DON'T WANT PEOPLE TO KNOW I AM BOTH OF THOSE, then it is too late... there is nothing you can do.

**Comment by lemonforest** [comment]
![image](https://user-images.githubusercontent.com/6238050/35261826-8b90ba72-ffd7-11e7-8c01-926654763788.png)

https://keybase.io/docs
Keybase uses merkle tree for sigchain and signs merkle root to bitcoin blockchain.
