### ISSUE TITLE
segfault with latest amd64 deb package

### ISSUE THREAD

**Issue by merwok** [keybase/keybase-issues#3176]
After updating to version 1.0.40-20180129170044.02aaf2cfc

```
/usr/bin/run_keybase: line 122: 12847 Segmentation fault
      keybase-mount-helper -user-mount "$mountdir"
```

**Comment by strib** [comment]
@merwok do you have a custom `$LD_LIBRARY_PATH` set in the environment where you ran `run_keybase`?  (See keybase/client#10487.)

**Comment by merwok** [comment]
I don’t.

**Comment by strib** [comment]
Ok thanks.  What about `$LD_PRELOAD` or any other variable that might interact weirdly with setuid?  I can't repro the issue.

**Comment by merwok** [comment]
No there is nothing like that in my environment.  Operating system is Debian testing.

**Comment by brianmay** [comment]
Also seeing this on Debian/stretch.

According to https://github.com/keybase/client/issues/10487#issuecomment-365073599 this could be because golang still uses VSYSCALLS, which are disabled by default in modern kernels.

If so, this would explain why I haven't seen any problems on my other computer, where I have added "vsyscall=emulate" to my kernel command line. While this fixes the problem, it could have security issues.

**Comment by merwok** [comment]
That makes sense, I may have updated my kernel around the same as keybase and rebooted.

**Comment by strib** [comment]
I'm going to close one this in favor of consolidating the discussion to keybase/client#10487, where there has been more details posted so far.  Please follow over there and re-post anything you think might be relevant from this discussion.
