### ISSUE TITLE
kbfs not working on Arch Linux

### ISSUE THREAD

**Issue by theduke** [keybase/keybase-issues#3280]
I've tried to get kbfs to work on Arch Linux for an hour and I'm giving up.

I tried both the `keybase-bin` package from AUR and then the official packages (keybase, kbfs, keybase-gui).
(Note that I wiped the install in-between by deleting `~/{.config,.cache,.local/share}keybase` in-between).

Keybase itself and the GUI work perfectly.

But with keybase-bin: `/keybase` is created, but remains empty.
With community/kbfs: the mount point is not even created.

Note that in both cases `/run/user/UID/keybase/kbfs` also remains empty.

I've checked the logs for both the `keybase` and `kbfs` services and they don't report anything of note. 

```
Sep 25 08:53:25 xxx systemd[567]: Starting Keybase Filesystem service...
Sep 25 08:53:26 xxx sh[32035]: fusermount: entry for /home/theduke/kb not found in /etc/mtab
Sep 25 08:53:26 xxx systemd[567]: Started Keybase Filesystem service.
```

**Comment by strib** [comment]
If you run `keybase log send`, we might be able to find more answers.

I'm not sure what's up with the `/home/theduke/kb` mountpoint, which is non-standard.  It seems like you might have set that via `keybase config set mountdir` and forgot to mention it above?

In any case, on Arch, unless you're using the official `run_keybase` script, you need to create the mountpoint yourself.  And we recommend you don't use the default `/run/user/$UID/keybase/kbfs` one, since it gets wiped on every restart.

**Comment by theduke** [comment]
Yeah I had configured the mountdir beforehand.

Anyway, after a reboot it all started working magically.

Still, it would be nice to have some more detailed logs for what's going on in the kbfs service.
