### ISSUE TITLE
printf is not a valid keybase user

### ISSUE THREAD

**Issue by Voronenko** [keybase/keybase-issues#3294]
Ubuntu 18.04 LTS

keybase --version
keybase version 2.8.0-20181023124437+06221a8264

KBFS used with std /keybase entry point. 

On first entry to /keybase/... either via console, midnight commander or file manager, I observe system notification "Keybase: user not found"  - "printf is not a Keybase user"

and to be honest, "printf" seems not a very cool candidate for user name :)

**Comment by strib** [comment]
This has already been fixed in today's Linux update, `2.9.0-20181030145358.ea86aa30e5`.

But this probably indicates something weird going on with your shell environment, it means it's looking up a `printf` file in your current working directory.  Depending on what's going on, that could indicate a bad security vulnerability in your setup.

**Comment by Voronenko** [comment]
@strib  Can you provide more hints to check?
