### ISSUE TITLE
Right to be forgotten & sigchain

### ISSUE THREAD

**Issue by ManuRS** [keybase/keybase-issues#3309]
Right now if you revoked a signature (like twitter, web, etc.) the name of the account remain public in the user chain.

Why not allow the user to select not to show that events on the chain? If is not possible to complety remove this at least allow to hide the account name.

Example with a social web:
Right now: ~~claimed ownership of reddit account nick~~
Remove completly: (just an empty/private signature)
Not show concrete information: ~~claimed ownership [revoked in signature #]~~
Show the platform but not nicks: ~~claimed ownership of reddit account  [revoked in signature #]~~

For webs:
Right now: ~~claimed ownership of site.com via dns~~
Remove completly: (just an empty/private signature)
Not show concrete information: ~~claimed ownership via dns [revoked in signature #]~~

I think the **right to be forgotten** is very important and should be taking into account. If the remove completly option is not possible at least the "Not show concrete information" option.

Thanks for the amazing platform!

**Comment by plttn** [comment]
The issue is that the chain itself contains the account name. Even if you could hide the account name in the deletion chain, you wouldn't be able to modify the sigchain link that had your account name created.

**Comment by wnereiz** [comment]
I want to confirm, if user's account has been deleted, the sigchain is still there so all accounts name are still existed in the chain. Only they will not be shown in the web/client interface, so anyone will not be access them, right?

If so I think it is still violate "Right to be Forgotten" principle.

My suggestion is to consider abandon current merkle tree database, and to consider using a new approach to avoid the cracking of history events and at same time protect user privacy. I know it will not be happened. Just show my opinion here.

**Comment by maxtaco** [comment]
> I want to confirm, if user's account has been deleted, the sigchain is still there so all accounts name are still existed in the chain. Only they will not be shown in the web/client interface, so anyone will not be access them, right?

Deleted user accounts are hidden

> 
> If so I think it is still violate "Right to be Forgotten" principle.
> 
> My suggestion is to consider abandon current merkle tree database, and to consider using a new approach to avoid the cracking of history events and at same time protect user privacy. I know it will not be happened. Just show my opinion here.

We're not going to make this change.

**Comment by wnereiz** [comment]
> Deleted user accounts are hidden

Still have two questions here:
1. Why don't delete signature chain? Technically it should be possible (each account have it's own chain).
2. Does Keybase allow an untrusted mirror to fork all signature chains (from API) event for the accounts which have been deleted?

**Comment by maxtaco** [comment]
> > Deleted user accounts are hidden
> 
> Still have two questions here:
> 
> 1. Why don't delete signature chain? Technically it should be possible (each account have it's own chain).

If 5 people are in a team and one deletes, the team still needs to be reconstructed, and it cannot if we delete the data. Again, this is just sigchain data. All data not crucial to the reconstruction of teams is both private and deleted. Though of course we can't prove to you it's deleted, but it is.

> 2. Does Keybase allow an untrusted mirror to fork all signature chains (from API) event for the accounts which have been deleted?

The mirror should throw it out. This problem is inherent in any computer technology. Nothing can be actually deleted, it's just best effort all around. This goes for any kind of data. For this reason, we think technology like keybase is crucial, since users can delete their keys making the encrypted cloud data undecipherable.

We've thought a lot about this. Our current architecture is a good compromise between lots of competing design goals. If users really don't want their sigchain to say "max's iphone" they can type "i1" or whatnot. If users don't want their Twitter accounts associated, they don't have to.  Users have the trade-off to make the decisions that they think are best for their use case.
