### ISSUE TITLE
login page lists all devices for an account w/o needing a password

### ISSUE THREAD

**Issue by kargakis** [keybase/keybase-issues#3317]
When I try to login via a new device, keybase lists all of my existing devices and requests me to use an existing device in order to authorize the new device. This is problematic from a privacy standpoint, because I can figure out all devices used by anyone else on keybase. keybase should either not show the list of devices or require me to do basic auth.

**Comment by junderw** [comment]
This is how Keybase works.

Your devices are listed on your public profile. When you name your device you are warned "this name will be public"

**Comment by kargakis** [comment]
@junderw is there a technical limitation and devices cannot be hidden? It would be nice if I had the option to hide my own devices so consider this a feature request.

**Comment by halilim** [comment]
I support this ⬆️feature request. I didn't know/notice that the device names were going to be public. And worse yet, all history of devices are available at https://keybase.io/USER/sigchain, even after they are removed. So I can't just simply remove and re-add them. This is a part privacy, part security problem; i.e. I don't want some script kiddie (or a serious adversary, or a curious someone) to have a bit more info on me.

**Comment by Lucky225** [comment]
This is how keybase works, it's part of the merkle tree and it tells you this when you name a device. Device names are part of the sigchain, and in fact every message you type in keybase chat says which device was used. I vote for #wontfix :P

**Comment by halilim** [comment]
I'd still consider some solutions. Not sure if possible/overkill but I'd think about making them private (& storing separately) and generating a random public name. Or at least making the fact that the device name will be public more "visible" :)

**Comment by junderw** [comment]
you are missing the whole point of device names.

instead of remembering your public key fingerprint, all I need is your username and device name, and the sigchain lets me verify that there can only be one key and it is tied to human readable words.

You can name your device "rainbow charlie" if you want.

changing this behavior greatly increases phishing risk on the platform, and will not be changed without an alternative that is sufficient.

it is apparent and obvious that this information is public.

**Comment by tintinweb** [comment]
I just learned about this by accident. Not a single person I talked to was aware and it looks like almost everyone exposes [more than a generic device name](https://keybase.io/chris/devices) in that list. This is a security and privacy concern. Especially as there is no way to change a device name (I understand due to technical reasons).

Is there any reason for my devices to be exposed on the website? (I didn't find other peoples devices in the keybase app for example)
Is there any chance one can opt-out of this information leakage? (I'd also support the feature request raised by @kargakis; You can proof that a device key belongs to my handle without sharing all my devices beforehand.)

I am concerned.

**Comment by halilim** [comment]
I understand that this is built into the sigchain. My concern is mainly the widespread information harvesters that could use this for spam/profiling/exploits. I'd guess it's not a large attack surface. But still, maybe it can at least be named to "Device nickname", along with some notice like "(this will be public)" for now?

**Comment by wnereiz** [comment]
I agree it is a big concern about user data. Keybase does a good work on security, but not on privacy. Sigchain should be able to removed and re-created if it is separated by user. Merkle tree is global but it contain only hashes(?) to my understanding.

**Comment by maxtaco** [comment]
![image](https://user-images.githubusercontent.com/866815/75156340-ec471a80-56df-11ea-8d35-4bfbb82d5fb5.png)
