### ISSUE TITLE
Can't access to the spacedrop chat

### ISSUE THREAD

**Issue by DjigoLab** [keybase/keybase-issues#3549]
Hello, I can't access to the Spacedrop chat, as I just did a reset on my account right after they spoke to me and now I'm locked out of the conversation and I cannot redeem the Lumens :C

Any advice you guys can give me?

**Comment by teflontoni** [comment]
I'm interested in that as well
![grafik](https://user-images.githubusercontent.com/6845171/65022673-a799a500-d931-11e9-945f-237e97108119.png)

my handle is **tulek**

**Comment by kenorb** [comment]
See: https://twitter.com/malgorithms/status/1173785764544569345

> And just had to turn off new GitHub Space Drop registrations also, due to bad actors. Even after all these years, the Internet can find a way to let ya down. http://keybase.io/airdrop

**Comment by teflontoni** [comment]
My account wasn't hacked, I've read about the offer and because of an OS reinstall I've lost my initial keybase installation and therefore gone through a reset.

I can't see me being a bad actor here...

**Comment by DjigoLab** [comment]
Is there any solution to this?

**Comment by plttn** [comment]
@DjigoLab okay so just looking at it, you did not have your Stellar wallet on your reset chain. At some point, Keybase employees will be going though and accepting the chats of users who reset but *did not* have a Stellar wallet prior to the reset. To be clear: this does mean you will be receiving Drop 0 (the one that came to all active Keybase users as of 9/9) at some point.

@teflontoni: since your Github isn't linked to Keybase, I can't see your sig chain. as long as you do not have a stellar wallet in the portion of the sigchain that has been reset, looking something like this

![image](https://user-images.githubusercontent.com/7369280/65292287-a0c68a00-db0b-11e9-9cd5-d22e92fe8639.png)

once employees do go through and reset the chats you will be able to claim your Drop 0. If you however had a Stellar wallet created prior to the reset, the coins that were sent went to an actual wallet and are completely irrecoverable by you resetting your Keybase account.

**Comment by smartins** [comment]
> My account wasn't hacked, I've read about the offer and because of an OS reinstall I've lost my initial keybase installation and therefore gone through a reset.
> 
> I can't see me being a bad actor here...

Same here, shame we get to loose the drop 0 by resetting the account but it's my fault for not backing up the keys properly.

**Comment by DjigoLab** [comment]
Well, got it now, I'm now allowed to be in the chat, here is what the account/bot told me: 

`Hi @djigo - you recently reset your account, and I am letting you back into our chat. You can qualify for all future monthly giveaways (October 15, onward) by visiting your wallet tab and registering. That is, if you haven't already.

              Also, if I previously sent you Lumens and you had not yet activated your Stellar wallet, you may be able to retrieve those by visiting your wallet tab now. If you don't see them, there's nothing I can do, as you've lost your old keys. Either way, hope to see you next month.`

Thanks for the answers
