### ISSUE TITLE
deleted issue

### ISSUE THREAD

**Issue by jugi1** [keybase/keybase-issues#3553]
deleted

**Comment by junderw** [comment]
Not sure what is funnier:

1. Keybase doing the airdrop and failing horribly as predicted.
2. All the accounts posting Github proofs on keybase issue instead of a gist like they were told.
3. All the people after the shutdown coming out of their clickfarms to say "but I wasn't a bot! everyone else was but not me!"
4. Conspiracy theories

Too bad for all the clickfarmers, XLM is up 15% in a day.

IMO, the whole airdrop ordeal set Keybase way back on dev time they could have used towards their main goal.

It'd be like Tesla doing a JV with windshield washer fluid company, and suddenly the next update will randomly shoot out fluid and do a few wipes for no reason every now and then, and then Tesla announces you can get 2L of FREE washer fluid if you just opt-in to this thing! Meanwhile, people just want to drive their car.

**Comment by jugi1** [comment]
I have no idea what where develoeprs thinking messing with Hackernews?
Did they expected to invite friendly hackers to the party so we can all have fun?

With this action and this Fakedrop they ruined all future for Keybase.

First time I heard about it and invited few good friends to try it,now I have to explain everyone that Keybase devs are child amateurs that can't handle airdrop scammer.

Failed misearbly....
but it will be nice story for my blog and forum.

Cheers

**Comment by maxtaco** [comment]
@junderw, closing down this issue, it's not an appropriate bug report.

**Comment by jugi1** [comment]
I beg your pardon?

**Comment by jugi1** [comment]
Why did you delete the text content?
