### ISSUE TITLE
Airdrop: All boxes checked but not qualified

### ISSUE THREAD

**Issue by prachetasp** [keybase/keybase-issues#3603]
First screen - qualified!

![qualified](https://user-images.githubusercontent.com/3642289/66618256-1919eb80-eb9e-11e9-8d6c-f9a32edcc669.png)

Next screen - not qualified :(

![unqualified](https://user-images.githubusercontent.com/3642289/66618261-1cad7280-eb9e-11e9-93b3-0bc6872508ac.png)

**Comment by psylox01** [comment]
I have the same problem, error code 4207. first it was accepted, then the error came. from the support. came no answer

**Comment by aawheatley** [comment]
Same problem here as well. This may be for lots of volunteers.

**Comment by psylox01** [comment]
> Same problem here as well. This may be for lots of volunteers.
from which country do you come ? is it qualified for the airtrop?

**Comment by psylox01** [comment]
https://ibb.co/jTKm5N3

**Comment by loseirdo** [comment]
I'm having the same issue. I'm in the US, and I have a US phone number. As you can see in @prachetasp's screenshot, it recognizes that the phone number is in an approved country, but it still gives an error code. This seems to be a fairly common issue.

**Comment by On3-Ey3dW1lly** [comment]
Yepp same stuff from Finland...

**Comment by mrmalachai** [comment]
I'm having the same issue precisely, with the same error code, confirmed on three machines: Windows 10, Linux Mint 19.2 MATE 64-bit, and Android 9 arm64. I'm seeing lots and lots of people having this same issue, and the counter on the website doesn't seem to be incrementing (between last night and this morning, anyway) so I'm assuming the issue is server-side and unfixable from the client end.

For what it's worth, I meet all of the requirements for the airdrop, and while it's not important to me that I receive it, (as truly it's just a bonus,) I'd like to add my voice to the issue.

**Comment by FloodSpeaker** [comment]
Same error code. Confirmed on: Win7, Linux Mint 19.2, Manjaro, Android 6

**Comment by mrmalachai** [comment]
> I'm having the same issue precisely, with the same error code, confirmed on three machines: Windows 10, Linux Mint 19.2 MATE 64-bit, and Android 9 arm64. I'm seeing lots and lots of people having this same issue, and the counter on the website doesn't seem to be incrementing (between last night and this morning, anyway) so I'm assuming the issue is server-side and unfixable from the client end.
> 
> For what it's worth, I meet all of the requirements for the airdrop, and while it's not important to me that I receive it, (as truly it's just a bonus,) I'd like to add my voice to the issue.

I just identified _my_ issue, that's not to say that it's going to be _your_ issue. I had been using a Google Voice number for my account, as it's the business number I associate with this profile. As it turns out, they're scanning for those VOIP numbers specifically, and blocking them. Ensure you're using an actual, **real** phone number from a country in the "approved" list, and it may (or may not!) improve your chances of getting in on the drop.

**Comment by loseirdo** [comment]
@mrmalachai It would be unfortunate if people were being denied based solely on carrier. I switched from Verizon to FreedomPop within the last year just to save money, and it's already been a big hassle for a lot of things. If that's the issue, it's a pretty misguided one, I think. I would have been better off with them just accepting applicants based on a pre-existing github account.

**Comment by PFCM** [comment]
I'm having the same issue from Australia; the only thing I can think of is that I'm using a a pre-paid phone number. There was some mention in the announcement about Canada being excluded because of an inability to verify phone numbers weren't purchased at scaled so presumably there are some deeper checks than the country code.

It's not a big deal but it would be nicer to have been told up front

**Comment by jors68** [comment]
Me too, from italy, 
Everythig is setup and it says I am ok to receive, bu...
I tried both from PC and from mobile phone but still it says I am not qualified.
my phone is real I am not using vpn or VOIP or other stuff like that

**Comment by rptb1** [comment]
![Screenshot 2019-10-20 at 00 28 21](https://user-images.githubusercontent.com/419807/67152613-12902000-f2d2-11e9-8014-d14ed1539801.png)

**Comment by stefan-popescu** [comment]
Same issue here. On Android I was qualified, hit the "Become a lucky airdropee" button, but then got an error (which I've reported). The airdrop no longer appears at all on Android.
On Windows, I see the option to join and I'm qualified, but when I hit the button to join, I'm told that I'm not qualified.
Happens from Telekom (ISP and mobile #) in Germany. My friends and family were able to join, except me. :(

**Comment by caitlynmeeks** [comment]
US phone number.  Three devices.  Says I'm qualified, on the check, and then says I'm not, without giving a reason or a channel for support,  when I click "Become a lucky airdrop-ee"...

:( :( :( :(

I'd like to try out Keybase and the airdrop is a generous offer, but it just feels patently unfair.

**Comment by andybiss** [comment]
+1, also have this issue on Windows, Linux, and Android clients

**Comment by prachetasp** [comment]
anyone from keybase?

love the app and the offer but very frustrating to be rejected without any explanation...

**Comment by ACGeek** [comment]
Same issue, everything is checked, but it then says I'm not qualified.  Trying to figure out if that means the account is already enrolled?  Or maybe not since https://github.com/keybase/keybase-issues/issues/3603#issuecomment-541384033 said it worked after removing their Google Voice number (tried that too btw, but same error).

**Comment by RobFraza** [comment]
Same here:  "Sorry, you are not qualified to join"
 What can i do????

**Comment by zhangwenhua-tron** [comment]
I have the same problem.

**Comment by zhangwenhua-tron** [comment]
@maxtaco , this issue was closed?! why?

**Comment by mrmalachai** [comment]
> @maxtaco , this issue was closed?! why?

My assumption is that the issue isn't an actual issue, but instead an artifact of the fight against spam. They have some list of unpublished requirements - such as no VoIP numbers - to combat spam, and if you don't meet them, it won't work, even though it's passing the visible checks.

If it's not an actual issue, there's no reason to keep it open.
