### ISSUE TITLE
Impossible to fully reconnect graph after pgp key deletion

### ISSUE THREAD

**Issue by mitchjmac** [keybase/keybase-issues#3627]
Under the "new key model" if you have a device key, you cannot add a new pgp key directly linking to your keybase profile like the old days. It must instead be verified using one of your existing devices.

I had a pgp key connecting my keybase profile to the rest of my proofs. That PGP key expired, so I deleted it from keybase. Now, I can only link a new PGP key to existing devices, the same goes for adding new devices. My graph looks like the following.

<img width="475" alt="kb_graph" src="https://user-images.githubusercontent.com/16813805/67608681-f582a380-f74e-11e9-9493-69d61384f4e2.png">

It is impossible for me to reconnect the keybase profile node without resetting the entire account. This is poor design.

**Comment by junderw** [comment]
"Reconnect"?

Yes, you're right. That image is poorly designed. The system is not.

IMO, the graph page should be removed, as it is not useful and causes people to try and make it "aesthetically pleasing" by signing devices and revoking devices in some special order as to make it "look nice"

**Comment by mitchjmac** [comment]
But that’s the thing. The Mac was originally registered using that expired key. That is still the “source” of verification for the Mac as far as I’m aware. Unless I’m gravely misunderstanding things.

**Comment by Brianetta** [comment]
That's correct. If you look at [your sigchain](https://keybase.io/mitchmac/sigchain), you will see your PGP key was added in chainlink 1, and revoked in chainlink 30. It is, and will remain, valid for all signatures made until chainlink 30, and cannot be valid in any subsequent links. Since it's not possible to add links anywhere but the end of the chain, the revocation of your PGP key has ensured that it can't be used in future, without destroying everything that it had already been legitimately used for.

**Comment by mitchjmac** [comment]
Awesome thanks for explaining!
