### ISSUE TITLE
i can not join the airdrop

### ISSUE THREAD

**Issue by danihermosoo** [keybase/keybase-issues#3700]
i can not join the airdrop, it tells me that im qualify but when i press become alucky airdropee it tells me that i am not qualify

**Comment by benjaminchodroff** [comment]
My wife is facing the same issue. I'm guessing it's because we used our Google Voice number? It's a shame... because she is a real person. I wish keybase would adopt a better way of fighting spam (perhaps age of account and some gps data?) - it's leaving a bad impression.

**Comment by exegg** [comment]
That's quite interesting @benjaminchodroff I don't think they allow numbers coming from these kind of services.

**Comment by benjaminchodroff** [comment]
@exegg I registered with my phone number which is a Google Voice account based in USA. Same with my wife - also a USA google voice number. My keybase account is from 2018... but hers was made today. Not sure what the issue is, but unfortunate that they aren't being more transparent on why she can't join?

**Comment by GlitchMasta47** [comment]
I signed up with a Google Voice number as well. After removing it from my account and adding my mobile phone number, it worked just fine.

**Comment by Patol11** [comment]
No response from Keybase, no response at all in this error, disqualifies me for this airdrop. You can speculate on what is going on, until there is no answer, it is a great deception. Can be rejected due to bad IP, wrong pool of mobile operator numbers, but there should be some answer. The silence in this matter is surprising. Has no administrator read these posts? Lack of professionalism.

**Comment by GlitchMasta47** [comment]
@Patol11 maybe you didn't see my message above, the reason it's not working is because of Google Voice phone numbers. I myself have confirmed this. Immediately after removing my Google Voice number and adding my actual phone number it immediately allowed me to join the airdrop.

Try this out, and if it still doesn't work leave another comment.
