### ISSUE TITLE
How to decrypt from command line with paper key?

### ISSUE THREAD

**Issue by Engelberg** [keybase/keybase-issues#3785]
Let's say I've encrypted a file for a user alfred from the command line, using 
```
keybase encrypt alfred -i file.txt -o file.txt.encrypted
```

My understanding is that this effectively encrypts the file for all the device keys associated with alfred at the time I've encrypted the file.

A few years go by, and alfred has replaced all the computers that he had at the time I encrypted the file. He now wants to decrypt my file. He has none of the same device keys that he had at the time I encrypted it, but fortunately, he still has the paper key that he had at the time I encrypted it.

How would he decrypt the file from the command line using his paper key?

**Comment by mlsteele** [comment]
Assuming alfred is using a computer he owns he could provision the computer as a new Keybase device using the paper key and then decrypt using `keybase decrypt`.

**Comment by Engelberg** [comment]
I'm not clear what it means to "provision the computer as a new keybase device using the paper key". Does that mean the computer will use the paper key as its device key rather than generating its own?

I was under the impression that adding a device always generated a new device-specific key, and that this would trigger the keybase filesystem to re-encrypt the header of any file on the filesystem, adding the new device-specific key as one of the things that can decrypt it. But if the file doesn't reside on the keybase filesystem, I don't see how adding a new device can help, unless the device retains info about the paper key used to provision it, or adopts the paper key as its own device key.

But perhaps my mental model is totally wrong.

**Comment by maxtaco** [comment]
Try `keybase encrypt --help` for a fuller picture. That's a pretty good description.

When you encrypt for alfred, you encrypt for all of his devices, and also for his **per-user-key**.  The secret half of this key is gossiped to new devices as they are provisioned.  So in this sense, *future* devices should be able to decrypt the message, so long as they are an uninterrupted chain of devices.

**Comment by maxtaco** [comment]
Also, as another answer to your question, `keybase decrypt --paperkey` should work. I guess that should work logged out.

**Comment by Engelberg** [comment]
Thanks, `keybase decrypt --paperkey` answers my question (I regret that I missed that option in the help). But now I realize my mental model is slightly flawed, and now that I know that information is gossiped from one device to the next, it makes me wonder if there's good docs on what happens if you use the advanced options during encrypt like --no-paper-keys, --no-device-keys, or --no-entity-keys. It's clear what these do during the initial encryption, but it's not clear to me what kind of spreading happens to new keys. For example, if there's an entity key and you said --no-paper-keys, would new paper keys get the info they needed from the entity key, or does --no-paper-keys block all future paper keys?

**Comment by maxtaco** [comment]
You only get future-proofing with the "entity keys", be they "per-team-keys" or "per-user-keys." Encrypting for device keys and paper keys just encrypts for the set of known keys at the time of encryption.

To answer your question, lets considering this sequence of events:

1. Bob makes a device key pair (d,D) and a paper key pair (p,P).  Bob has a per-user-key (u,U).  When he provisions the device and paper key, he uploads Enc(D, u) and Enc(P, u). That is, he encrypts the secret half of his per-user-key for the device public key D and the paper public key P.
1. Alice does:  `keybase encrypt -m hi --no-paper-keys --no-device-keys --no-self-encrypt  bob`.  This basically encrypts the message for U.
1. Bob adds a new paper key (q, Q).  In so doing, he also uploads Enc(Q, u).
1. Bob provisions a new device (c,C) using his paper key, (q,Q). Using q, he can decrypt u. Now he uploads Enc(C, u).
1. Bob can decrypt the message alice sent in step 2 either by using his new paper key, or his new device, since both can see u, and the message was originally encrypted for u.

**Comment by Engelberg** [comment]
Thanks, I've almost got it now. 

When you provision something with your paper key, your per-user-key has to come from somewhere though -- it's not embedded into the paper key, right?  In which case, I'm assuming the keybase server is storing Enc(P,u) and when you provision a new device with your paper key, it will prompt you for your password to retrieve Enc(P,u) from the server. Is that accurate?

**Comment by maxtaco** [comment]
Correct, but one important point is that you don't need a password on Keybase anymore, and you don't need a password in the flow you described. You can authenticate with your paper key. Your client signs a challenge with a key derived from your paper key, which proves to the server that you know the paper key without sharing the paper key with the server.

**Comment by Engelberg** [comment]
Thanks.
