### ISSUE TITLE
Access to access logs for files?

### ISSUE THREAD

**Issue by Mezzle** [keybase/keybase-issues#3975]
We've had a member of one of our teams put a file into a public folder, when it really should've been private.

Is it possible to find out (possibly with admin help? I see https://github.com/keybase/kbfs/issues/1497 mentions that there might be something @strib can do?) whether this file has been accessed?  This'll help us find out whether it's actually a data breach or not (We think, due to circumstances, probably not, but we have to treat it as one if we don't have evidence otherwise!)

Thanks in advance for the help!

**Comment by strib** [comment]
We cannot tell if a particular file has been accessed, because on our end we don't know anything about file names or which data blocks map to which files (even for public folders).  In the issue you linked, we could probably look up whether a particular user looked inside that folder at all (but not which files they saw). Very sorry!
