### ISSUE TITLE
Password reset/account recovery not working

### ISSUE THREAD

**Issue by deoxxa** [keybase/keybase-issues#40]
Pretty much what it says on the tin.

Steps:
1. open https://keybase.io/ in a browser
2. click login
3. click recover account
4. enter email (or username, same result)
5. click reset password
6. cry deeply while waiting for an email that never comes

**Comment by NuVivo314** [comment]
Hello,
I reopen this issue. I never receive the email for recovery process.
And my email isn't verified and the control email never received.

**Comment by pressurehead** [comment]
@malgorithms is there a help section for Keybase? I signed up last night and started verifying, but my Keepass didn't save my password. I have tried to reset it at the website but get: You can't reset your passphrase, since you have active device or paper keys. The following devices all have the power to change your passphrase.
Mobile Device
If you have lost all these devices, please contact max@keybase.io

In looking for a place on the iOS app to change my passphrase I logged out. :(

Could you or anyone at Keybase give me any direction to fix my situation?

**Comment by maxtaco** [comment]
Did you explicitly click the "sign off" button in the keybase app?

**Comment by pressurehead** [comment]
I have, yes.

**Comment by maxtaco** [comment]
Ok I don't think this is a bug meaning the app is working as intended.
Unfortunately the only thing we can do is to reset your account.  This is
by design because otherwise someone who had stolen your phone could collude
with someone who has compromised keybase's database to own your account.

When I get back to the office on Tuesday I can reset your account. Send me
an email at that address.

**Comment by pressurehead** [comment]
Thank you very much Max. Especially for responding so quickly on a Saturday morning!

**Comment by musicogeek** [comment]
Good morning. Greets from Venezuela.

Could you please reset my account? lost all devices and need to stablish new ones. My user is @musicogeek.

Thanks in advance.
