### ISSUE TITLE
Describe approx business model?

### ISSUE THREAD

**Issue by timmc** [keybase/keybase-issues#788]
Before investing time, personal information, and identity into this site, I'd like to have a rough idea of your business model. Is this something you plan to run out of the kindness of your hearts and the money in your wallets, or will it need a funding source at some point?

Your two previous projects have involved a buyout as exit plan, so you'll understand if I want a little assurance.

**Comment by pfalcon** [comment]
Update on business model: https://keybase.io/blog/2015-07-15/keybase-raises-series-a

**Comment by anko** [comment]
Another update on business model: https://keybase.io/blog/keybase-joins-zoom

**Comment by djunzu** [comment]
> Max and I are happy in a world where we never try to sell a company again, and only build things we like.

And now, it is sold!

**Comment by wkunker** [comment]
> 
> 
> Hi Tim - unlike SparkNotes or OkCupid (our previous 2 businesses), Keybase has no clear, approx business model. Previously, we knew exactly what we were doing.
> 
> With Keybase, we're not sure. It's just the two of us right now, and while we are putting money into it (serving, some office space for ourselves, other small expenses), it is primarily sucking on our time, money. It feels like a passion project, and we're driven forward without a lot of concern for where money could come from.
> 
> What this means: a clear business model is basically irrelevant because our decision to pursue this is personal.
> 
> While that means there is no promise it will exist in a couple years, we are certainly trying. But if I had a clearer answer - say there were some obvious business model - that risk would still be there for you. Businesses fail all the time.
> 
> Probably the simplest thing is for you to pick some small amount of time (30 minutes?) and use Keybase as long as you're enjoying it or until the 30 minutes are up, whichever is shorter. This minimizes risk. I think you'll find that since we're using PGP keys, and teaching people about crypto, the net result of Keybase will be a positive, regardless of what happens. The keys and fingerprints people share and sync through Keybase will live on in their GPG installations, gists, etc.
> 
> As for fears of our doing something unethical to our users, I can only say we're not like that.
> 
> Yes, we sold our previous 2 businesses. But I want to point out that (1) neither of those sales ever hurt (and arguably both sales greatly helped) our users, (2) Keybase deserves special consideration which we are aware of, and (3) both Max and I are happy in a world where we never try to sell a company again, and only build things we like.

You, sir, are a liar.

**Comment by balupton** [comment]
> You, sir, are a liar.

Or someone who grows beyond an internet comment posted 6 years ago.

**Comment by wkunker** [comment]
> 
> 
> > You, sir, are a liar.
> 
> Or someone who grows beyond an internet comment posted 6 years ago.

I, like the author of this thread, based my decision to use KeyBase around this internet comment made 6 years ago by a founder of the company. As far as I'm aware, founders of companies have no expiration period after which they are no longer responsible for public statements they make in regards to their companies.

**Comment by pfalcon** [comment]
> based my decision to use KeyBase

If your decision was positive, what changes now? It was owned by one company, now is owned by different. Do you expect any different outcome for anything else owned by any company in the past, present, or future? Then better just assume such a scenario, forever, and there will be one less bad news for you to hear.

And in all fairness, if you guys have gripes with "a company", there're so many grassroot projects around... But let me guess, you want a website with comics painted for you. Well, of course, just be prepared to sell your soul for it. Again, it's old news.

**Comment by wkunker** [comment]
> > based my decision to use KeyBase
> 
> If your decision was positive, what changes now? It was owned by one company, now is owned by different. Do you expect any different outcome for anything else owned by any company in the past, present, or future? Then better just assume such a scenario, forever, and there will be one less bad news for you to hear.

Not sure I follow this line of reasoning. I think there are plenty of companies which have not sold out to the highest bidder. The company could have been sold in a way that doesn't legitimately harm its users (in this case the eventual discontinuation of Keybase in favor of Zoom enhancements), and it simply wasn't. This goes against what was said above.

> And in all fairness, if you guys have gripes with "a company", there're so many grassroot projects around... But let me guess, you want a website with comics painted for you. Well, of course, just be prepared to sell your soul for it. Again, it's old news.

For the sake of others that might discover this thread in the future, what is your definition of a grassroots project? No funding source or specific types of funding sources? Specifically individuals who have not previously founded a company? Is there a specific subset of open source licenses which make a project grassroots? Or does it simply come down to the project website not having comics? I think defining a specific set of criteria here could help people (including myself) to avoid using such software in the future.

**Comment by timmc** [comment]
> I, like the author of this thread, based my decision to use KeyBase around this internet comment made 6 years ago by a founder of the company.

And if you're like me, you took the response at face value: There's no business model, it's exploratory, etc. "Happy to never sell again" is aspirational, not a promise, and anyway not particularly meaningful without a business model. If you pinned your hopes on this, I don't know what to tell you.

I really appreciated Chris's honesty in that reply, regardless of how I feel about this sale.

**Comment by wkunker** [comment]
> > I, like the author of this thread, based my decision to use KeyBase around this internet comment made 6 years ago by a founder of the company.
> 
> And if you're like me, you took the response at face value: There's no business model, it's exploratory, etc. "Happy to never sell again" is aspirational, not a promise, and anyway not particularly meaningful without a business model. If you pinned your hopes on this, I don't know what to tell you.
> 
> I really appreciated Chris's honesty in that reply, regardless of how I feel about this sale.

I think that is a fair point. I certainly did not anticipate a sale to Zoom, but it is fair to say I likely misinterpreted the spirit of the original reply. Thanks for clarifying this.

**Comment by pfalcon** [comment]
> Not sure I follow this line of reasoning. I think there are plenty of companies which have not sold out to the highest bidder.

Yet.

> The company could have been sold in a way that doesn't legitimately harm its users (in this case the eventual discontinuation of Keybase in favor of Zoom enhancements), and it simply wasn't. This goes against what was said above.

I have to admit I haven't read that "press release" yet, so draw a picture based on common knowledge, and it's: Zoom got explosive growth due to pandemic lockout, followed by some pretty bad PR regarding their privacy/security side. Zoom decided to ~~whiten their image~~ improve their technology by buying a company specializing on "sekuritee". So far, all feels like a win-win (for a comicland), and I don't smell immediate discontinuation of keybase. As for "eventual", well, nobody can say for sure about that. And who does, draws you a comic, so ask for bright colors.
 
> For the sake of others that might discover this thread in the future, what is your definition of a grassroots project?

That's hard indeed. I actually would suggest to concentrate on your needs and feelings, and not on the colorfulness of the picture drawn. For example, if you want full control of your data and sustainability, then if someone promises central server with comics where you *potentially* upload your stuff in plaintext, it's ok to feel wrong.

To give a nice example of a "grassroot" project spotted recently (everyone heard about Freenet, IPFS, etc.), is https://urbit.org/ (that's not an advertisement, the project is absolutely nuts, actually, I'd argue that's one of the criteria of "grassrootness" ;-). There're clearly no middle-ground so far, so choose your poison).

**Comment by chindraba-work** [comment]
Have to chime in on a couple things. First off, I was blind-sided by the sale (or aqui-hire) to Zoom. "Of all places?!" was part of my initial response. I've since relaxed and determined to enjoy Keybase for as long as we have left, whether that is a few more weeks, or several more years. I have previously concluded that no single project, service, product, or website, should become indispensable in my business or personal efforts, unless it was under my direct control, _in toto_. Keybase is no exception, even though I have used it for business, it is not the only channel I have available for communication with clients, and it is not the totality of my networking efforts.

---
## Discussion Points:

> While that means there is no promise it will exist in a couple years, we are certainly trying.

A couple of years after 2014 has gone by, as has a few more years after that. With no promise of even two years, a five-year run is pretty good.

 > It feels like a passion project, and we're driven forward without a lot of concern for where money could come from.
 
Having built, grown, and sold a couple other businesses they were in a position to be able to pursue a passion, something many others would love to do. I know I would enjoy the prospect of coding what I wanted to code because I wanted to solve a problem I though existed, rather than what I needed to code to pay the rent and utilities.

> Max and I are happy in a world where we never try to sell a company again, and only build things we like.

As above, the need for money, or to get the business ready to sell, has been removed. They were able work to make the project what they wanted it to be without having to look at the sales potential of every decision. There's nothing there saying they wouldn't sell, only that they didn't have to _try_ to sell. Two very different concepts.

---

I bear no animosity, nor ill will, towards the founders of Keybase, or any of the team they built, from the sale of Keybase. I don't consider it a "sell-out" or a betrayal in any fashion. If anything, I'm jealous of their prospects. 

Consider this: they likened Keybase to a "passion project." If the passion was for doing secure communications well, then they succeeded here. Next, Zoom shows up with a much larger project, and a bigger security challenge. Not counting other elements of the offer, the developers were offered the chance to take on a much larger challenge. In short terms, the developers were offered the chance to get paid to play.

I've been in such a position, once, and accepted a greatly lower salary than I normally would, merely because what I was going to work on would be complete "fun", and getting paid for it as well was like a bonus.

I do suspect that, with the urgency and severity of the situation with Zoom, the team was also offered a generous package as well. Given the success of two prior projects, and statements made here years ago, I doubt the size of the check was nearly as persuasive as the size of the challenge.

Hoping Keybase survives, and thrives, I still wish the team great success with the new challenge.
